#
include
"
nsISupports
.
idl
"
interface
nsIScriptElement
;
interface
nsIURI
;
[
scriptable
uuid
(
7b787204
-
76fb
-
4764
-
96f1
-
fb7a666db4f4
)
]
interface
nsIScriptLoaderObserver
:
nsISupports
{
void
scriptAvailable
(
in
nsresult
aResult
in
nsIScriptElement
aElement
in
boolean
aIsInlineClassicScript
in
nsIURI
aURI
in
int32_t
aLineNo
)
;
[
can_run_script
]
void
scriptEvaluated
(
in
nsresult
aResult
in
nsIScriptElement
aElement
in
boolean
aIsInline
)
;
}
;
