#
include
"
nsISupports
.
idl
"
interface
nsIURI
;
interface
nsIDomainSet
;
%
{
C
+
+
namespace
mozilla
{
namespace
dom
{
class
DomainPolicyClone
;
}
}
%
}
[
ptr
]
native
DomainPolicyClonePtr
(
mozilla
:
:
dom
:
:
DomainPolicyClone
)
;
[
ptr
]
native
DomainPolicyCloneConstPtr
(
const
mozilla
:
:
dom
:
:
DomainPolicyClone
)
;
[
scriptable
builtinclass
uuid
(
82b24a20
-
6701
-
4d40
-
a0f9
-
f5dc7321b555
)
]
interface
nsIDomainPolicy
:
nsISupports
{
readonly
attribute
nsIDomainSet
blocklist
;
readonly
attribute
nsIDomainSet
superBlocklist
;
readonly
attribute
nsIDomainSet
allowlist
;
readonly
attribute
nsIDomainSet
superAllowlist
;
void
deactivate
(
)
;
[
noscript
notxpcom
]
void
cloneDomainPolicy
(
in
DomainPolicyClonePtr
aClone
)
;
[
noscript
notxpcom
]
void
applyClone
(
in
DomainPolicyCloneConstPtr
aClone
)
;
}
;
[
scriptable
builtinclass
uuid
(
665c981b
-
0a0f
-
4229
-
ac06
-
a826e02d4f69
)
]
interface
nsIDomainSet
:
nsISupports
{
void
add
(
in
nsIURI
aDomain
)
;
void
remove
(
in
nsIURI
aDomain
)
;
void
clear
(
)
;
boolean
contains
(
in
nsIURI
aDomain
)
;
boolean
containsSuperDomain
(
in
nsIURI
aDomain
)
;
}
;
