#
include
"
nsISupports
.
idl
"
interface
nsIURI
;
interface
nsILoadInfo
;
typedef
unsigned
long
nsContentPolicyType
;
[
scriptable
uuid
(
caad4f1f
-
d047
-
46ac
-
ae9d
-
dc598e4fb91b
)
]
interface
nsIContentPolicy
:
nsISupports
{
const
nsContentPolicyType
TYPE_INVALID
=
0
;
const
nsContentPolicyType
TYPE_OTHER
=
1
;
const
nsContentPolicyType
TYPE_SCRIPT
=
2
;
const
nsContentPolicyType
TYPE_IMAGE
=
3
;
const
nsContentPolicyType
TYPE_STYLESHEET
=
4
;
const
nsContentPolicyType
TYPE_OBJECT
=
5
;
const
nsContentPolicyType
TYPE_DOCUMENT
=
6
;
const
nsContentPolicyType
TYPE_SUBDOCUMENT
=
7
;
const
nsContentPolicyType
TYPE_REFRESH
=
8
;
const
nsContentPolicyType
TYPE_PING
=
10
;
const
nsContentPolicyType
TYPE_XMLHTTPREQUEST
=
11
;
const
nsContentPolicyType
TYPE_DATAREQUEST
=
11
;
const
nsContentPolicyType
TYPE_OBJECT_SUBREQUEST
=
12
;
const
nsContentPolicyType
TYPE_DTD
=
13
;
const
nsContentPolicyType
TYPE_FONT
=
14
;
const
nsContentPolicyType
TYPE_MEDIA
=
15
;
const
nsContentPolicyType
TYPE_WEBSOCKET
=
16
;
const
nsContentPolicyType
TYPE_CSP_REPORT
=
17
;
const
nsContentPolicyType
TYPE_XSLT
=
18
;
const
nsContentPolicyType
TYPE_BEACON
=
19
;
const
nsContentPolicyType
TYPE_FETCH
=
20
;
const
nsContentPolicyType
TYPE_IMAGESET
=
21
;
const
nsContentPolicyType
TYPE_WEB_MANIFEST
=
22
;
const
nsContentPolicyType
TYPE_INTERNAL_SCRIPT
=
23
;
const
nsContentPolicyType
TYPE_INTERNAL_WORKER
=
24
;
const
nsContentPolicyType
TYPE_INTERNAL_SHARED_WORKER
=
25
;
const
nsContentPolicyType
TYPE_INTERNAL_EMBED
=
26
;
const
nsContentPolicyType
TYPE_INTERNAL_OBJECT
=
27
;
const
nsContentPolicyType
TYPE_INTERNAL_FRAME
=
28
;
const
nsContentPolicyType
TYPE_INTERNAL_IFRAME
=
29
;
const
nsContentPolicyType
TYPE_INTERNAL_AUDIO
=
30
;
const
nsContentPolicyType
TYPE_INTERNAL_VIDEO
=
31
;
const
nsContentPolicyType
TYPE_INTERNAL_TRACK
=
32
;
const
nsContentPolicyType
TYPE_INTERNAL_XMLHTTPREQUEST
=
33
;
const
nsContentPolicyType
TYPE_INTERNAL_EVENTSOURCE
=
34
;
const
nsContentPolicyType
TYPE_INTERNAL_SERVICE_WORKER
=
35
;
const
nsContentPolicyType
TYPE_INTERNAL_SCRIPT_PRELOAD
=
36
;
const
nsContentPolicyType
TYPE_INTERNAL_IMAGE
=
37
;
const
nsContentPolicyType
TYPE_INTERNAL_IMAGE_PRELOAD
=
38
;
const
nsContentPolicyType
TYPE_INTERNAL_STYLESHEET
=
39
;
const
nsContentPolicyType
TYPE_INTERNAL_STYLESHEET_PRELOAD
=
40
;
const
nsContentPolicyType
TYPE_INTERNAL_IMAGE_FAVICON
=
41
;
const
nsContentPolicyType
TYPE_INTERNAL_WORKER_IMPORT_SCRIPTS
=
42
;
const
nsContentPolicyType
TYPE_SAVEAS_DOWNLOAD
=
43
;
const
nsContentPolicyType
TYPE_SPECULATIVE
=
44
;
const
nsContentPolicyType
TYPE_INTERNAL_MODULE
=
45
;
const
nsContentPolicyType
TYPE_INTERNAL_MODULE_PRELOAD
=
46
;
const
nsContentPolicyType
TYPE_INTERNAL_DTD
=
47
;
const
nsContentPolicyType
TYPE_INTERNAL_FORCE_ALLOWED_DTD
=
48
;
const
nsContentPolicyType
TYPE_INTERNAL_AUDIOWORKLET
=
49
;
const
nsContentPolicyType
TYPE_INTERNAL_PAINTWORKLET
=
50
;
const
nsContentPolicyType
TYPE_INTERNAL_FONT_PRELOAD
=
51
;
const
nsContentPolicyType
TYPE_INTERNAL_CHROMEUTILS_COMPILED_SCRIPT
=
52
;
const
nsContentPolicyType
TYPE_INTERNAL_FRAME_MESSAGEMANAGER_SCRIPT
=
53
;
const
short
REJECT_REQUEST
=
-
1
;
const
short
REJECT_TYPE
=
-
2
;
const
short
REJECT_SERVER
=
-
3
;
const
short
REJECT_OTHER
=
-
4
;
const
short
ACCEPT
=
1
;
short
shouldLoad
(
in
nsIURI
aContentLocation
in
nsILoadInfo
aLoadInfo
in
ACString
aMimeTypeGuess
)
;
short
shouldProcess
(
in
nsIURI
aContentLocation
in
nsILoadInfo
aLoadInfo
in
ACString
aMimeType
)
;
}
;
