#
include
"
nsISupports
.
idl
"
interface
nsIChannel
;
interface
nsIRequest
;
interface
nsIFrame
;
interface
nsIPluginTag
;
interface
nsIURI
;
webidl
BrowsingContext
;
[
scriptable
builtinclass
uuid
(
2eb3195e
-
3eea
-
4083
-
bb1d
-
d2d70fa35ccb
)
]
interface
nsIObjectLoadingContent
:
nsISupports
{
const
unsigned
long
TYPE_LOADING
=
0
;
const
unsigned
long
TYPE_IMAGE
=
1
;
const
unsigned
long
TYPE_FALLBACK
=
2
;
const
unsigned
long
TYPE_FAKE_PLUGIN
=
3
;
const
unsigned
long
TYPE_DOCUMENT
=
4
;
const
unsigned
long
TYPE_NULL
=
5
;
const
unsigned
long
PLUGIN_ACTIVE
=
0xFF
;
const
unsigned
long
PLUGIN_PERMISSION_PROMPT_ACTION_QUIET
=
8
;
readonly
attribute
ACString
actualType
;
readonly
attribute
unsigned
long
displayedType
;
unsigned
long
getContentTypeForMIMEType
(
in
AUTF8String
aMimeType
)
;
void
reload
(
in
boolean
aClearActivation
)
;
[
noscript
]
void
stopPluginInstance
(
)
;
[
noscript
]
void
syncStartPluginInstance
(
)
;
[
noscript
]
void
asyncStartPluginInstance
(
)
;
[
noscript
]
void
initializeFromChannel
(
in
nsIRequest
request
)
;
readonly
attribute
nsIURI
srcURI
;
void
skipFakePlugins
(
)
;
[
noscript
]
BrowsingContext
upgradeLoadToDocument
(
in
nsIChannel
channel
)
;
}
;
