#
include
"
nsISupports
.
idl
"
#
include
"
domstubs
.
idl
"
interface
mozIDOMWindowProxy
;
interface
nsIEditor
;
%
{
C
+
+
class
mozIDOMWindowProxy
;
namespace
mozilla
{
class
HTMLEditor
;
}
%
}
[
scriptable
builtinclass
uuid
(
24f963d1
-
e6fc
-
43ea
-
a206
-
99ac5fcc5265
)
]
interface
nsIEditingSession
:
nsISupports
{
const
long
eEditorOK
=
0
;
const
long
eEditorCreationInProgress
=
1
;
const
long
eEditorErrorCantEditMimeType
=
2
;
const
long
eEditorErrorFileNotFound
=
3
;
const
long
eEditorErrorCantEditFramesets
=
8
;
const
long
eEditorErrorUnknown
=
9
;
readonly
attribute
unsigned
long
editorStatus
;
[
can_run_script
]
void
makeWindowEditable
(
in
mozIDOMWindowProxy
window
in
string
aEditorType
in
boolean
doAfterUriLoad
in
boolean
aMakeWholeDocumentEditable
in
boolean
aInteractive
)
;
boolean
windowIsEditable
(
in
mozIDOMWindowProxy
window
)
;
nsIEditor
getEditorForWindow
(
in
mozIDOMWindowProxy
window
)
;
[
noscript
]
void
tearDownEditorOnWindow
(
in
mozIDOMWindowProxy
window
)
;
%
{
C
+
+
mozilla
:
:
HTMLEditor
*
GetHTMLEditorForWindow
(
mozIDOMWindowProxy
*
aWindow
)
;
%
}
}
;
