#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
c7e7fc54
-
4133
-
4191
-
bd40
-
cc2b77fd21bc
)
]
interface
nsIPrivateAttributionService
:
nsISupports
{
void
onAttributionEvent
(
in
ACString
sourceHost
in
ACString
type
in
uint32_t
index
in
AString
ad
in
ACString
targetHost
)
;
void
onAttributionConversion
(
in
ACString
sourceHost
in
AString
task
in
uint32_t
histogramSize
in
uint32_t
loopbackDays
in
ACString
impressionType
in
Array
<
AString
>
ads
in
Array
<
ACString
>
sourceHosts
)
;
}
;
