#
include
"
nsISupports
.
idl
"
#
include
"
nsICookie
.
idl
"
[
builtinclass
scriptable
uuid
(
bf049b1e
-
8a05
-
481f
-
a120
-
332ea1bd65ef
)
]
interface
nsICookieRule
:
nsISupports
{
readonly
attribute
nsICookie
cookie
;
readonly
attribute
int64_t
expiryRelative
;
readonly
attribute
AUTF8String
unsetValue
;
}
;
