#
include
"
nsISupports
.
idl
"
#
include
"
nsICookieRule
.
idl
"
[
builtinclass
scriptable
uuid
(
eb1904db
-
e0d1
-
4760
-
a721
-
db76b1ca3e94
)
]
interface
nsICookieBannerRule
:
nsISupports
{
attribute
ACString
domain
;
readonly
attribute
Array
<
nsICookieRule
>
cookiesOptOut
;
readonly
attribute
Array
<
nsICookieRule
>
cookiesOptIn
;
void
clearCookies
(
)
;
void
addCookie
(
in
boolean
aIsOptOut
in
AUTF8String
aHost
in
ACString
aName
in
AUTF8String
aValue
[
optional
]
in
AUTF8String
aPath
[
optional
]
in
int64_t
aExpiryRelative
[
optional
]
in
AUTF8String
aUnsetValue
[
optional
]
in
boolean
aIsSecure
[
optional
]
in
boolean
aIsHttpOnly
[
optional
]
in
boolean
aIsSession
[
optional
]
in
int32_t
aSameSite
[
optional
]
in
nsICookie_schemeType
aSchemeMap
)
;
}
;
