#
include
"
nsISupports
.
idl
"
#
include
"
nsIClickRule
.
idl
"
#
include
"
nsICookieRule
.
idl
"
[
builtinclass
scriptable
uuid
(
eb1904db
-
e0d1
-
4760
-
a721
-
db76b1ca3e94
)
]
interface
nsICookieBannerRule
:
nsISupports
{
attribute
ACString
domain
;
readonly
attribute
Array
<
nsICookieRule
>
cookiesOptOut
;
readonly
attribute
Array
<
nsICookieRule
>
cookiesOptIn
;
void
clearCookies
(
)
;
void
addCookie
(
in
boolean
aIsOptOut
in
ACString
aName
in
AUTF8String
aValue
in
AUTF8String
aHost
in
AUTF8String
aPath
in
int64_t
aExpiryRelative
in
AUTF8String
aUnsetValue
in
boolean
aIsSecure
in
boolean
aIsHttpOnly
in
boolean
aIsSession
in
int32_t
aSameSite
in
nsICookie_schemeType
aSchemeMap
)
;
readonly
attribute
nsIClickRule
clickRule
;
void
addClickRule
(
in
ACString
aPresence
[
optional
]
in
ACString
aHide
[
optional
]
in
ACString
aOptOut
[
optional
]
in
ACString
aOptIn
)
;
void
clearClickRule
(
)
;
}
;
