#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
5d58bf99
-
9539
-
49d7
-
aa76
-
c5a262476e5a
)
]
interface
nsILimitedAccessFeature
:
nsISupports
{
readonly
attribute
ACString
featureId
;
readonly
attribute
ACString
token
;
readonly
attribute
ACString
attestation
;
boolean
unlock
(
)
;
}
;
[
scriptable
uuid
(
115f4862
-
f302
-
42a2
-
a58c
-
d09f636ab601
)
]
interface
nsILimitedAccessFeatureService
:
nsISupports
{
readonly
attribute
ACString
taskbarPinFeatureId
;
nsILimitedAccessFeature
generateLimitedAccessFeature
(
in
ACString
featureId
)
;
}
;
