#
include
"
nsIShellService
.
idl
"
[
scriptable
uuid
(
387fdc80
-
0077
-
4b60
-
a0d9
-
d9e80a83ba64
)
]
interface
nsIMacShellService
:
nsIShellService
{
void
showDesktopPreferences
(
)
;
void
showSecurityPreferences
(
in
ACString
aPaneID
)
;
}
;
