#
include
"
nsISupports
.
idl
"
interface
nsIFile
;
interface
imgIContainer
;
webidl
Element
;
[
scriptable
uuid
(
2d1a95e4
-
5bd8
-
4eeb
-
b0a8
-
c1455fd2a357
)
]
interface
nsIShellService
:
nsISupports
{
boolean
isDefaultBrowser
(
[
optional
]
in
boolean
aForAllTypes
)
;
void
setDefaultBrowser
(
in
boolean
aForAllUsers
)
;
const
long
BACKGROUND_TILE
=
1
;
const
long
BACKGROUND_STRETCH
=
2
;
const
long
BACKGROUND_CENTER
=
3
;
const
long
BACKGROUND_FILL
=
4
;
const
long
BACKGROUND_FIT
=
5
;
const
long
BACKGROUND_SPAN
=
6
;
void
setDesktopBackground
(
in
Element
aElement
in
long
aPosition
in
ACString
aImageName
)
;
attribute
unsigned
long
desktopBackgroundColor
;
readonly
attribute
ACString
iconExtension
;
[
implicit_jscontext
]
Promise
createIcon
(
in
nsIFile
aFile
in
imgIContainer
aContainer
)
;
}
;
