#
include
"
nsISupports
.
idl
"
#
include
"
nsIPrincipal
.
idl
"
[
scriptable
uuid
(
9e32a7b6
-
c4d1
-
4d9a
-
87b9
-
1ef6b75c27a9
)
]
interface
nsIConsoleAPIStorage
:
nsISupports
{
jsval
getEvents
(
[
optional
]
in
AString
aId
)
;
void
addLogEventListener
(
in
jsval
aListener
in
nsIPrincipal
aPrincipal
)
;
void
removeLogEventListener
(
in
jsval
aListener
)
;
void
recordEvent
(
in
AString
aId
in
jsval
aEvent
)
;
void
clearEvents
(
[
optional
]
in
AString
aId
)
;
}
;
