#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
d74c96b2
-
65b3
-
4e39
-
9e39
-
c577de5d7a73
)
]
interface
nsIWebSocketListener
:
nsISupports
{
[
must_use
]
void
onStart
(
in
nsISupports
aContext
)
;
[
must_use
]
void
onStop
(
in
nsISupports
aContext
in
nsresult
aStatusCode
)
;
[
must_use
]
void
onMessageAvailable
(
in
nsISupports
aContext
in
AUTF8String
aMsg
)
;
[
must_use
]
void
onBinaryMessageAvailable
(
in
nsISupports
aContext
in
ACString
aMsg
)
;
[
must_use
]
void
onAcknowledge
(
in
nsISupports
aContext
in
uint32_t
aSize
)
;
[
must_use
]
void
onServerClose
(
in
nsISupports
aContext
in
unsigned
short
aCode
in
AUTF8String
aReason
)
;
[
must_use
]
void
OnError
(
)
;
}
;
