Classes
=
[
]
if
defined
(
'
MOZ_BITS_DOWNLOAD
'
)
:
Classes
+
=
[
{
'
cid
'
:
'
{
495d6f3d
-
9748
-
4d30
-
8ce5
-
0290c0001edf
}
'
'
contract_ids
'
:
[
'
mozilla
.
org
/
bits
;
1
'
]
'
singleton
'
:
True
'
constructor
'
:
'
GetBitsService
'
'
headers
'
:
[
'
Bits
.
h
'
]
}
]
