#
include
"
ISimpleDOMNode
.
idl
"
#
include
"
ISimpleDOMDocument
.
idl
"
#
include
"
ISimpleDOMText
.
idl
"
[
uuid
(
a6245497
-
9c0b
-
4449
-
85a5
-
bd6ad07df8ea
)
helpstring
(
"
ISimpleDOM
Type
Library
"
)
]
library
ISimpleDOM
{
interface
ISimpleDOMNode
;
interface
ISimpleDOMText
;
interface
ISimpleDOMDocument
;
}
;
