#
include
"
nsISupports
.
idl
"
#
include
"
nsrootidl
.
idl
"
[
uuid
(
de4f460b
-
94fd
-
442c
-
9002
-
1637beb2185a
)
]
interface
nsINamedPipeDataObserver
:
nsISupports
{
void
onDataAvailable
(
in
unsigned
long
aBytesTransferred
in
voidPtr
aOverlapped
)
;
void
onError
(
in
unsigned
long
aError
in
voidPtr
aOverlapped
)
;
}
;
[
uuid
(
1bf19133
-
5625
-
4ac8
-
836a
-
80b1c215f72b
)
]
interface
nsINamedPipeService
:
nsISupports
{
void
addDataObserver
(
in
voidPtr
aHandle
in
nsINamedPipeDataObserver
aObserver
)
;
void
removeDataObserver
(
in
voidPtr
aHandle
in
nsINamedPipeDataObserver
aObserver
)
;
boolean
isOnCurrentThread
(
)
;
}
;
