#
include
"
nsISupports
.
idl
"
interface
nsIX509Cert
;
%
{
C
+
+
namespace
IPC
{
class
Message
;
}
class
PickleIterator
;
%
}
[
ptr
]
native
IpcMessagePtr
(
IPC
:
:
Message
)
;
[
ptr
]
native
PickleIteratorPtr
(
PickleIterator
)
;
[
builtinclass
scriptable
uuid
(
216112d3
-
28bc
-
4671
-
b057
-
f98cc09ba1ea
)
]
interface
nsITransportSecurityInfo
:
nsISupports
{
readonly
attribute
unsigned
long
securityState
;
readonly
attribute
long
errorCode
;
readonly
attribute
AString
errorCodeString
;
readonly
attribute
Array
<
nsIX509Cert
>
failedCertChain
;
readonly
attribute
nsIX509Cert
serverCert
;
readonly
attribute
Array
<
nsIX509Cert
>
succeededCertChain
;
[
must_use
]
readonly
attribute
ACString
cipherName
;
[
must_use
]
readonly
attribute
unsigned
long
keyLength
;
[
must_use
]
readonly
attribute
unsigned
long
secretKeyLength
;
[
must_use
]
readonly
attribute
ACString
keaGroupName
;
[
must_use
]
readonly
attribute
ACString
signatureSchemeName
;
const
short
SSL_VERSION_3
=
0
;
const
short
TLS_VERSION_1
=
1
;
const
short
TLS_VERSION_1_1
=
2
;
const
short
TLS_VERSION_1_2
=
3
;
const
short
TLS_VERSION_1_3
=
4
;
[
must_use
]
readonly
attribute
unsigned
short
protocolVersion
;
const
short
CERTIFICATE_TRANSPARENCY_NOT_APPLICABLE
=
0
;
const
short
CERTIFICATE_TRANSPARENCY_POLICY_COMPLIANT
=
5
;
const
short
CERTIFICATE_TRANSPARENCY_POLICY_NOT_ENOUGH_SCTS
=
6
;
const
short
CERTIFICATE_TRANSPARENCY_POLICY_NOT_DIVERSE_SCTS
=
7
;
[
must_use
]
readonly
attribute
unsigned
short
certificateTransparencyStatus
;
[
must_use
]
readonly
attribute
boolean
isAcceptedEch
;
[
must_use
]
readonly
attribute
boolean
isDelegatedCredential
;
[
must_use
]
readonly
attribute
boolean
isDomainMismatch
;
[
must_use
]
readonly
attribute
boolean
isNotValidAtThisTime
;
[
must_use
]
readonly
attribute
boolean
isUntrusted
;
[
must_use
]
readonly
attribute
boolean
isExtendedValidation
;
[
notxpcom
noscript
]
void
SerializeToIPC
(
in
IpcMessagePtr
aMsg
)
;
[
notxpcom
noscript
]
bool
DeserializeFromIPC
(
[
const
]
in
IpcMessagePtr
aMsg
in
PickleIteratorPtr
aIter
)
;
readonly
attribute
ACString
negotiatedNPN
;
readonly
attribute
boolean
resumed
;
attribute
boolean
isBuiltCertChainRootBuiltInRoot
;
}
;
