#
include
"
nsISupports
.
idl
"
interface
nsILoadGroup
;
interface
nsIChannel
;
interface
nsIURI
;
interface
nsIWebProgress
;
interface
nsIRequest
;
[
scriptable
uuid
(
bbe961ee
-
59e9
-
42bb
-
be50
-
0331979bb79f
)
]
interface
nsIDocumentLoader
:
nsISupports
{
void
stop
(
)
;
readonly
attribute
nsISupports
container
;
readonly
attribute
nsILoadGroup
loadGroup
;
readonly
attribute
nsIChannel
documentChannel
;
}
;
