#
include
"
nsIWebProgressListener2
.
idl
"
interface
nsIArray
;
interface
nsIURI
;
interface
nsICancelable
;
interface
nsIMIMEInfo
;
interface
nsIFile
;
webidl
BrowsingContext
;
[
scriptable
uuid
(
37ec75d3
-
97ad
-
4da8
-
afaa
-
eabe5b4afd73
)
]
interface
nsITransfer
:
nsIWebProgressListener2
{
const
unsigned
long
DOWNLOAD_ACCEPTABLE
=
0
;
const
unsigned
long
DOWNLOAD_FORBIDDEN
=
1
;
const
unsigned
long
DOWNLOAD_POTENTIALLY_UNSAFE
=
2
;
void
init
(
in
nsIURI
aSource
in
nsIURI
aTarget
in
AString
aDisplayName
in
nsIMIMEInfo
aMIMEInfo
in
PRTime
startTime
in
nsIFile
aTempFile
in
nsICancelable
aCancelable
in
boolean
aIsPrivate
in
long
aDownloadClassification
)
;
void
initWithBrowsingContext
(
in
nsIURI
aSource
in
nsIURI
aTarget
in
AString
aDisplayName
in
nsIMIMEInfo
aMIMEInfo
in
PRTime
startTime
in
nsIFile
aTempFile
in
nsICancelable
aCancelable
in
boolean
aIsPrivate
in
long
aDownloadClassification
in
BrowsingContext
aBrowsingContext
in
boolean
aHandleInternally
)
;
void
setSha256Hash
(
in
ACString
aHash
)
;
void
setSignatureInfo
(
in
Array
<
Array
<
Array
<
uint8_t
>
>
>
aSignatureInfo
)
;
void
setRedirects
(
in
nsIArray
aRedirects
)
;
}
;
%
{
C
+
+
#
define
NS_TRANSFER_CONTRACTID
"
mozilla
.
org
/
transfer
;
1
"
%
}
