#
include
"
nsISupports
.
idl
"
interface
nsIURIContentListener
;
interface
nsIURI
;
interface
nsILoadGroup
;
interface
nsIProgressEventSink
;
interface
nsIChannel
;
interface
nsIRequest
;
interface
nsIStreamListener
;
interface
nsIInputStream
;
interface
nsIInterfaceRequestor
;
[
scriptable
uuid
(
8762c4e7
-
be35
-
4958
-
9b81
-
a05685bb516d
)
]
interface
nsIURILoader
:
nsISupports
{
const
unsigned
long
IS_CONTENT_PREFERRED
=
1
<
<
0
;
const
unsigned
long
DONT_RETARGET
=
1
<
<
1
;
void
registerContentListener
(
in
nsIURIContentListener
aContentListener
)
;
void
unRegisterContentListener
(
in
nsIURIContentListener
aContentListener
)
;
void
openURI
(
in
nsIChannel
aChannel
in
unsigned
long
aFlags
in
nsIInterfaceRequestor
aWindowContext
)
;
nsIStreamListener
openChannel
(
in
nsIChannel
aChannel
in
unsigned
long
aFlags
in
nsIInterfaceRequestor
aWindowContext
)
;
void
stop
(
in
nsISupports
aLoadCookie
)
;
}
;
