Classes
=
[
{
'
cid
'
:
'
{
1a817186
-
357a
-
47cd
-
8aea
-
2850d60e959e
}
'
'
contract_ids
'
:
[
'
mozilla
.
org
/
jsreflect
;
1
'
]
'
type
'
:
'
mozilla
:
:
reflect
:
:
Module
'
'
headers
'
:
[
'
/
toolkit
/
components
/
reflect
/
reflect
.
h
'
]
}
]
