#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
15686f9d
-
483e
-
4361
-
98cd
-
37f1e8f1e61d
)
]
interface
nsIFinalizationWitnessService
:
nsISupports
{
[
implicit_jscontext
]
jsval
make
(
in
string
aTopic
in
wstring
aString
)
;
}
;
%
{
C
+
+
#
define
FINALIZATIONWITNESSSERVICE_CID
{
0x15686f9d
0x483e
0x4361
{
0x98
0xcd
0x37
0xf1
0xe8
0xf1
0xe6
0x1d
}
}
#
define
FINALIZATIONWITNESSSERVICE_CONTRACTID
"
mozilla
.
org
/
toolkit
/
finalizationwitness
;
1
"
%
}
