#
include
"
nsISupports
.
idl
"
#
include
"
nsIPaymentActionResponse
.
idl
"
[
scriptable
uuid
(
01f8bd55
-
9017
-
438b
-
85ec
-
7c15d2b35cdc
)
]
interface
nsIPaymentUIService
:
nsISupports
{
void
showPayment
(
in
AString
requestId
)
;
void
abortPayment
(
in
AString
requestId
)
;
void
completePayment
(
in
AString
requestId
)
;
void
updatePayment
(
in
AString
requestId
)
;
void
closePayment
(
in
AString
requestId
)
;
}
;
%
{
C
+
+
#
define
NS_PAYMENT_UI_SERVICE_CONTRACT_ID
\
"
mozilla
.
org
/
dom
/
payments
/
payment
-
ui
-
service
;
1
"
%
}
