#
include
"
nsISupports
.
idl
"
#
include
"
nsIVariant
.
idl
"
#
include
"
nsIPaymentRequest
.
idl
"
#
include
"
nsIPaymentActionResponse
.
idl
"
#
include
"
nsIPaymentAddress
.
idl
"
#
include
"
nsISimpleEnumerator
.
idl
"
#
include
"
nsIPaymentUIService
.
idl
"
[
scriptable
builtinclass
uuid
(
cccd665f
-
edf3
-
41fc
-
ab9b
-
fc55b37340aa
)
]
interface
nsIPaymentRequestService
:
nsISupports
{
nsIPaymentRequest
getPaymentRequestById
(
in
AString
aRequestId
)
;
nsISimpleEnumerator
enumerate
(
)
;
void
respondPayment
(
in
nsIPaymentActionResponse
aResponse
)
;
void
changeShippingAddress
(
in
AString
requestId
in
nsIPaymentAddress
aAddress
)
;
void
changeShippingOption
(
in
AString
requestId
in
AString
option
)
;
void
changePayerDetail
(
in
AString
requestId
in
AString
aPayerName
in
AString
aPayerEmail
in
AString
aPayerPhone
)
;
void
changePaymentMethod
(
in
AString
requestId
in
AString
aMethodName
in
nsIMethodChangeDetails
aMethodDetails
)
;
void
cleanup
(
)
;
void
setTestingUIService
(
in
nsIPaymentUIService
aUIService
)
;
}
;
%
{
C
+
+
#
define
NS_PAYMENT_REQUEST_SERVICE_CONTRACT_ID
\
"
mozilla
.
org
/
dom
/
payments
/
payment
-
request
-
service
;
1
"
%
}
