#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
745e1eac
-
e449
-
4342
-
bca1
-
ee0e6ead09fc
)
]
interface
nsIU2FTokenManager
:
nsISupports
{
void
resumeRegister
(
in
uint64_t
aTransactionID
in
bool
aForceNoneAttestation
)
;
void
cancel
(
in
uint64_t
aTransactionID
)
;
}
;
