#
include
"
nsISupports
.
idl
"
typedef
long
COSEAlgorithmIdentifier
;
[
uuid
(
2fc8febe
-
a277
-
11ed
-
bda2
-
8f6495a5e75c
)
]
interface
nsIWebAuthnRegisterArgs
:
nsISupports
{
readonly
attribute
AString
origin
;
readonly
attribute
Array
<
octet
>
challenge
;
readonly
attribute
ACString
clientDataJSON
;
readonly
attribute
Array
<
octet
>
clientDataHash
;
readonly
attribute
AString
rpId
;
[
must_use
]
readonly
attribute
AString
rpName
;
[
must_use
]
readonly
attribute
Array
<
octet
>
userId
;
[
must_use
]
readonly
attribute
AString
userName
;
[
must_use
]
readonly
attribute
AString
userDisplayName
;
[
must_use
]
readonly
attribute
Array
<
COSEAlgorithmIdentifier
>
coseAlgs
;
readonly
attribute
Array
<
Array
<
octet
>
>
excludeList
;
readonly
attribute
Array
<
octet
>
excludeListTransports
;
[
must_use
]
readonly
attribute
boolean
credProps
;
[
must_use
]
readonly
attribute
boolean
hmacCreateSecret
;
[
must_use
]
readonly
attribute
boolean
minPinLength
;
readonly
attribute
AString
residentKey
;
readonly
attribute
AString
userVerification
;
[
must_use
]
readonly
attribute
AString
authenticatorAttachment
;
readonly
attribute
uint32_t
timeoutMS
;
[
must_use
]
readonly
attribute
AString
attestationConveyancePreference
;
}
;
[
uuid
(
2e621cf4
-
a277
-
11ed
-
ae00
-
bf41a54ef553
)
]
interface
nsIWebAuthnSignArgs
:
nsISupports
{
readonly
attribute
AString
origin
;
readonly
attribute
AString
rpId
;
readonly
attribute
Array
<
octet
>
challenge
;
readonly
attribute
ACString
clientDataJSON
;
readonly
attribute
Array
<
octet
>
clientDataHash
;
readonly
attribute
Array
<
Array
<
octet
>
>
allowList
;
readonly
attribute
Array
<
octet
>
allowListTransports
;
[
must_use
]
readonly
attribute
boolean
hmacCreateSecret
;
[
must_use
]
readonly
attribute
AString
appId
;
[
must_use
]
readonly
attribute
AString
userVerification
;
readonly
attribute
unsigned
long
timeoutMS
;
readonly
attribute
boolean
conditionallyMediated
;
}
;
