#
include
"
nsISupports
.
idl
"
#
include
"
nsIWebAuthnArgs
.
idl
"
#
include
"
nsIWebAuthnPromise
.
idl
"
[
scriptable
uuid
(
6c4ecd9f
-
57c0
-
4d7d
-
8080
-
bf6e4d499f8f
)
]
interface
nsICredentialParameters
:
nsISupports
{
readonly
attribute
ACString
credentialId
;
readonly
attribute
boolean
isResidentCredential
;
readonly
attribute
ACString
rpId
;
readonly
attribute
ACString
privateKey
;
readonly
attribute
ACString
userHandle
;
readonly
attribute
uint32_t
signCount
;
}
;
[
scriptable
uuid
(
686d552e
-
a39d
-
4ba2
-
8127
-
faca54274039
)
]
interface
nsIWebAuthnAutoFillEntry
:
nsISupports
{
const
octet
PROVIDER_UNKNOWN
=
0
;
const
octet
PROVIDER_TEST_TOKEN
=
1
;
const
octet
PROVIDER_PLATFORM_WINDOWS
=
2
;
const
octet
PROVIDER_PLATFORM_MACOS
=
3
;
const
octet
PROVIDER_PLATFORM_ANDROID
=
4
;
readonly
attribute
octet
provider
;
readonly
attribute
AString
userName
;
readonly
attribute
AString
rpId
;
readonly
attribute
Array
<
uint8_t
>
credentialId
;
}
;
[
scriptable
uuid
(
e236a9b4
-
a26f
-
11ed
-
b6cc
-
07a9834e19b1
)
]
interface
nsIWebAuthnService
:
nsISupports
{
readonly
attribute
boolean
isUVPAA
;
[
noscript
]
void
makeCredential
(
in
uint64_t
aTransactionId
in
uint64_t
browsingContextId
in
nsIWebAuthnRegisterArgs
args
in
nsIWebAuthnRegisterPromise
promise
)
;
[
noscript
]
void
getAssertion
(
in
uint64_t
aTransactionId
in
uint64_t
browsingContextId
in
nsIWebAuthnSignArgs
args
in
nsIWebAuthnSignPromise
promise
)
;
[
noscript
]
void
reset
(
)
;
void
cancel
(
in
uint64_t
aTransactionId
)
;
uint64_t
hasPendingConditionalGet
(
in
uint64_t
aBrowsingContextId
in
AString
aOrigin
)
;
Array
<
nsIWebAuthnAutoFillEntry
>
getAutoFillEntries
(
in
uint64_t
aTransactionId
)
;
void
selectAutoFillEntry
(
in
uint64_t
aTransactionId
in
Array
<
uint8_t
>
aCredentialId
)
;
void
resumeConditionalGet
(
in
uint64_t
aTransactionId
)
;
void
pinCallback
(
in
uint64_t
aTransactionId
in
AUTF8String
aPin
)
;
void
setHasAttestationConsent
(
in
uint64_t
aTransactionId
in
boolean
aHasConsent
)
;
void
selectionCallback
(
in
uint64_t
aTransactionId
in
uint64_t
aIndex
)
;
ACString
addVirtualAuthenticator
(
in
ACString
protocol
in
ACString
transport
in
boolean
hasResidentKey
in
boolean
hasUserVerification
in
boolean
isUserConsenting
in
boolean
isUserVerified
)
;
void
removeVirtualAuthenticator
(
in
ACString
authenticatorId
)
;
void
addCredential
(
in
ACString
authenticatorId
in
ACString
credentialId
in
boolean
isResidentCredential
in
ACString
rpId
in
ACString
privateKey
in
ACString
userHandle
in
uint32_t
signCount
)
;
Array
<
nsICredentialParameters
>
getCredentials
(
in
ACString
authenticatorId
)
;
void
removeCredential
(
in
ACString
authenticatorId
in
ACString
credentialId
)
;
void
removeAllCredentials
(
in
ACString
authenticatorId
)
;
void
setUserVerified
(
in
ACString
authenticatorId
in
boolean
isUserVerified
)
;
void
listen
(
)
;
void
runCommand
(
in
ACString
aCommand
)
;
}
;
