#
include
"
nsISupports
.
idl
"
#
include
"
nsIWebAuthnArgs
.
idl
"
#
include
"
nsIWebAuthnPromise
.
idl
"
[
scriptable
uuid
(
6c4ecd9f
-
57c0
-
4d7d
-
8080
-
bf6e4d499f8f
)
]
interface
nsICredentialParameters
:
nsISupports
{
readonly
attribute
ACString
credentialId
;
readonly
attribute
bool
isResidentCredential
;
readonly
attribute
ACString
rpId
;
readonly
attribute
ACString
privateKey
;
readonly
attribute
ACString
userHandle
;
readonly
attribute
uint32_t
signCount
;
}
;
[
scriptable
uuid
(
e236a9b4
-
a26f
-
11ed
-
b6cc
-
07a9834e19b1
)
]
interface
nsIWebAuthnService
:
nsISupports
{
void
makeCredential
(
in
uint64_t
aTransactionId
in
uint64_t
browsingContextId
in
nsIWebAuthnRegisterArgs
args
in
nsIWebAuthnRegisterPromise
promise
)
;
void
getAssertion
(
in
uint64_t
aTransactionId
in
uint64_t
browsingContextId
in
nsIWebAuthnSignArgs
args
in
nsIWebAuthnSignPromise
promise
)
;
[
noscript
]
void
reset
(
)
;
void
cancel
(
in
uint64_t
aTransactionId
)
;
void
pinCallback
(
in
uint64_t
aTransactionId
in
ACString
aPin
)
;
void
resumeMakeCredential
(
in
uint64_t
aTransactionId
in
bool
aForceNoneAttestation
)
;
void
selectionCallback
(
in
uint64_t
aTransactionId
in
uint64_t
aIndex
)
;
uint64_t
addVirtualAuthenticator
(
in
ACString
protocol
in
ACString
transport
in
bool
hasResidentKey
in
bool
hasUserVerification
in
bool
isUserConsenting
in
bool
isUserVerified
)
;
void
removeVirtualAuthenticator
(
in
uint64_t
authenticatorId
)
;
void
addCredential
(
in
uint64_t
authenticatorId
in
ACString
credentialId
in
bool
isResidentCredential
in
ACString
rpId
in
ACString
privateKey
in
ACString
userHandle
in
uint32_t
signCount
)
;
Array
<
nsICredentialParameters
>
getCredentials
(
in
uint64_t
authenticatorId
)
;
void
removeCredential
(
in
uint64_t
authenticatorId
in
ACString
credentialId
)
;
void
removeAllCredentials
(
in
uint64_t
authenticatorId
)
;
void
setUserVerified
(
in
uint64_t
authenticatorId
in
bool
isUserVerified
)
;
void
listen
(
)
;
}
;
