#
include
"
nsISupports
.
idl
"
[
uuid
(
0567c384
-
a728
-
11ed
-
85f7
-
030324a370f0
)
]
interface
nsIWebAuthnRegisterResult
:
nsISupports
{
readonly
attribute
ACString
clientDataJSON
;
readonly
attribute
Array
<
octet
>
attestationObject
;
readonly
attribute
boolean
attestationConsentPromptShown
;
readonly
attribute
Array
<
octet
>
credentialId
;
readonly
attribute
Array
<
AString
>
transports
;
readonly
attribute
boolean
hmacCreateSecret
;
[
must_use
]
attribute
boolean
credPropsRk
;
readonly
attribute
boolean
largeBlobSupported
;
readonly
attribute
boolean
prfEnabled
;
readonly
attribute
Array
<
octet
>
prfResultsFirst
;
readonly
attribute
Array
<
octet
>
prfResultsSecond
;
[
must_use
]
readonly
attribute
AString
authenticatorAttachment
;
boolean
hasIdentifyingAttestation
(
)
;
void
anonymize
(
)
;
}
;
[
uuid
(
05fff816
-
a728
-
11ed
-
b9ac
-
ff38cc2c8c28
)
]
interface
nsIWebAuthnSignResult
:
nsISupports
{
readonly
attribute
ACString
clientDataJSON
;
readonly
attribute
Array
<
octet
>
credentialId
;
readonly
attribute
Array
<
octet
>
authenticatorData
;
readonly
attribute
Array
<
octet
>
signature
;
[
must_use
]
readonly
attribute
Array
<
octet
>
userHandle
;
[
must_use
]
readonly
attribute
ACString
userName
;
[
must_use
]
attribute
boolean
usedAppId
;
readonly
attribute
Array
<
octet
>
largeBlobValue
;
readonly
attribute
boolean
largeBlobWritten
;
readonly
attribute
boolean
prfMaybe
;
readonly
attribute
Array
<
octet
>
prfResultsFirst
;
readonly
attribute
Array
<
octet
>
prfResultsSecond
;
[
must_use
]
readonly
attribute
AString
authenticatorAttachment
;
}
;
