#
include
"
nsISupports
.
idl
"
interface
nsIFile
;
[
scriptable
uuid
(
2f977d4e
-
5485
-
11d4
-
87e2
-
0010a4e75ef2
)
]
interface
nsIRelativeFilePref
:
nsISupports
{
attribute
nsIFile
file
;
attribute
ACString
relativeToKey
;
}
;
