#
include
"
nsISupports
.
idl
"
webidl
Range
;
[
scriptable
uuid
(
40aba110
-
2a56
-
4678
-
be90
-
e2c17a9ae7d7
)
]
interface
nsIFind
:
nsISupports
{
attribute
boolean
findBackwards
;
attribute
boolean
caseSensitive
;
attribute
boolean
entireWord
;
attribute
boolean
matchDiacritics
;
Range
Find
(
in
AString
aPatText
in
Range
aSearchRange
in
Range
aStartPoint
in
Range
aEndPoint
)
;
}
;
