#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
cd9f33c5
-
460d
-
4bbf
-
a459
-
f375ca9566d8
)
]
interface
nsISessionStoreRestoreData
:
nsISupports
{
attribute
AUTF8String
url
;
attribute
AString
innerHTML
;
attribute
ACString
scroll
;
void
addTextField
(
in
boolean
aIsXPath
in
AString
aIdOrXPath
in
AString
aValue
)
;
void
addCheckbox
(
in
boolean
aIsXPath
in
AString
aIdOrXPath
in
boolean
aValue
)
;
void
addFileList
(
in
boolean
aIsXPath
in
AString
aIdOrXPath
in
AString
aType
in
Array
<
AString
>
aFileList
)
;
void
addSingleSelect
(
in
boolean
aIsXPath
in
AString
aIdOrXPath
in
unsigned
long
aSelectedIndex
in
AString
aValue
)
;
void
addMultipleSelect
(
in
boolean
aIsXPath
in
AString
aIdOrXPath
in
Array
<
AString
>
aValues
)
;
void
addChild
(
in
nsISessionStoreRestoreData
aChild
in
unsigned
long
aIndex
)
;
}
;
