#
include
"
nsISupports
.
idl
"
webidl
BrowsingContext
;
webidl
Element
;
[
scriptable
uuid
(
1A060FBA
-
A19D
-
11E9
-
B7EB
-
580D0EDD8E6F
)
]
interface
nsISessionStoreFunctions
:
nsISupports
{
void
UpdateSessionStore
(
in
Element
aBrowser
in
BrowsingContext
aBrowsingContext
in
uint32_t
aFlushId
in
boolean
aIsFinal
in
uint32_t
aEpoch
in
jsval
aData
in
boolean
aCollectSHistory
)
;
void
RestoreTabContentComplete
(
in
Element
aBrowser
)
;
}
;
