#
include
"
nsISupports
.
idl
"
interface
nsIURI
;
interface
nsIPrincipal
;
[
scriptable
uuid
(
78e42d37
-
a34c
-
4d96
-
b901
-
25385669aba4
)
]
interface
nsILoadURIDelegate
:
nsISupports
{
nsIURI
handleLoadError
(
in
nsIURI
aURI
in
nsresult
aError
in
short
aErrorModule
)
;
}
;
