#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
2e530956
-
6054
-
464f
-
9f4c
-
0ae6f8de5523
)
]
interface
nsITabUnloader
:
nsISupports
{
void
unloadTabAsync
(
)
;
}
;
[
scriptable
uuid
(
b0b5701e
-
239d
-
49db
-
9009
-
37e89f86441c
)
]
interface
nsIAvailableMemoryWatcherBase
:
nsISupports
{
void
registerTabUnloader
(
in
nsITabUnloader
aTabUnloader
)
;
void
onUnloadAttemptCompleted
(
in
nsresult
aResult
)
;
}
;
