#
include
"
nsISupports
.
idl
"
[
builtinclass
scriptable
uuid
(
88c3f4a6
-
6f9a
-
4f6b
-
9a4b
-
5c1b1b0c2ad3
)
]
interface
nsIAvailableMemoryWatcherTestingLinux
:
nsISupports
{
void
setPSIPathForTesting
(
in
ACString
aPSIPath
)
;
}
;
