#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
3aba9617
-
10e2
-
4839
-
83ae
-
2e6fc4df428b
)
]
interface
nsIConsoleMessage
:
nsISupports
{
const
uint32_t
debug
=
0
;
const
uint32_t
info
=
1
;
const
uint32_t
warn
=
2
;
const
uint32_t
error
=
3
;
readonly
attribute
uint32_t
logLevel
;
readonly
attribute
long
long
timeStamp
;
readonly
attribute
long
long
microSecondTimeStamp
;
[
binaryname
(
MessageMoz
)
]
readonly
attribute
AString
message
;
attribute
boolean
isForwardedFromContentProcess
;
AUTF8String
toString
(
)
;
}
;
%
{
C
+
+
#
define
NS_CONSOLEMESSAGE_CID
\
{
0x024efc9e
0x54dc
0x4844
{
0x80
0x4b
0x41
0xd3
0xf3
0x69
0x90
0x73
}
}
%
}
