#
include
"
nsISupports
.
idl
"
interface
nsIConsoleListener
;
interface
nsIConsoleMessage
;
[
scriptable
builtinclass
uuid
(
0eb81d20
-
c37e
-
42d4
-
82a8
-
ca9ae96bdf52
)
]
interface
nsIConsoleService
:
nsISupports
{
void
logMessage
(
in
nsIConsoleMessage
message
)
;
cenum
OutputMode
:
8
{
SuppressLog
=
0
OutputToLog
}
;
void
logMessageWithMode
(
in
nsIConsoleMessage
message
in
nsIConsoleService_OutputMode
mode
)
;
void
logStringMessage
(
in
wstring
message
)
;
Array
<
nsIConsoleMessage
>
getMessageArray
(
)
;
void
registerListener
(
in
nsIConsoleListener
listener
)
;
void
unregisterListener
(
in
nsIConsoleListener
listener
)
;
void
reset
(
)
;
void
resetWindow
(
in
uint64_t
windowInnerId
)
;
}
;
%
{
C
+
+
#
define
NS_CONSOLESERVICE_CID
\
{
0x7e3ff85c
0x1dd2
0x11b2
{
0x8d
0x4b
0xeb
0x45
0x2c
0xb0
0xff
0x40
}
}
#
define
NS_CONSOLESERVICE_CONTRACTID
"
mozilla
.
org
/
consoleservice
;
1
"
%
}
