#
include
"
nsISupports
.
idl
"
%
{
C
+
+
#
include
"
nsDependentString
.
h
"
#
include
<
stdio
.
h
>
%
}
interface
nsIFile
;
[
ptr
]
native
FILE
(
FILE
)
;
[
scriptable
uuid
(
6bd5642c
-
1b90
-
4499
-
ba4b
-
199f27efaba5
)
]
interface
nsIGZFileWriter
:
nsISupports
{
[
must_use
]
void
init
(
in
nsIFile
file
)
;
[
noscript
must_use
]
void
initANSIFileDesc
(
in
FILE
file
)
;
[
must_use
]
void
write
(
in
AUTF8String
str
)
;
%
{
C
+
+
[
[
nodiscard
]
]
nsresult
Write
(
const
char
*
str
)
{
return
Write
(
str
strlen
(
str
)
)
;
}
[
[
nodiscard
]
]
nsresult
Write
(
const
char
*
str
uint32_t
len
)
{
return
Write
(
nsDependentCSubstring
(
str
len
)
)
;
}
%
}
void
finish
(
)
;
}
;
