#
include
"
nsISupports
.
idl
"
interface
nsIRunnable
;
[
builtinclass
scriptable
uuid
(
3E8C58E8
-
E52C
-
43E0
-
8E66
-
669CA788FF5F
)
]
interface
nsIMessageLoop
:
nsISupports
{
void
postIdleTask
(
in
nsIRunnable
task
in
uint32_t
ensureRunsAfterMS
)
;
}
;
