#
include
"
nsISupports
.
idl
"
interface
nsIFile
;
interface
nsICycleCollectorLogSink
;
[
scriptable
function
uuid
(
2dea18fc
-
fbfa
-
4bf7
-
ad45
-
0efaf5495f5e
)
]
interface
nsIFinishDumpingCallback
:
nsISupports
{
void
callback
(
in
nsISupports
data
)
;
}
;
[
scriptable
uuid
(
dc1b2b24
-
65bd
-
441b
-
b6bd
-
cb5825a7ed14
)
]
interface
nsIDumpGCAndCCLogsCallback
:
nsISupports
{
void
onDump
(
in
nsIFile
aGCLog
in
nsIFile
aCCLog
in
bool
aIsParent
)
;
void
onFinish
(
)
;
}
;
[
scriptable
builtinclass
uuid
(
48541b74
-
47ee
-
4a62
-
9557
-
7f4b809bda5c
)
]
interface
nsIMemoryInfoDumper
:
nsISupports
{
void
dumpMemoryReportsToNamedFile
(
in
AString
aFilename
in
nsIFinishDumpingCallback
aFinishDumping
in
nsISupports
aFinishDumpingData
in
boolean
aAnonymize
in
boolean
aMinimizeMemoryUsage
)
;
void
dumpMemoryInfoToTempDir
(
in
AString
aIdentifier
in
boolean
aAnonymize
in
boolean
aMinimizeMemoryUsage
)
;
void
dumpGCAndCCLogsToFile
(
in
AString
aIdentifier
in
bool
aDumpAllTraces
in
bool
aDumpChildProcesses
in
nsIDumpGCAndCCLogsCallback
aCallback
)
;
void
dumpGCAndCCLogsToSink
(
in
bool
aDumpAllTraces
in
nsICycleCollectorLogSink
aSink
)
;
}
;
