#
include
"
nsISupports
.
idl
"
[
uuid
(
1e004834
-
6d8f
-
425a
-
bc9c
-
a2812ed43bb7
)
]
interface
nsIMemory
:
nsISupports
{
void
heapMinimize
(
in
boolean
immediate
)
;
boolean
isLowMemoryPlatform
(
)
;
}
;
