#
include
"
nsISupports
.
idl
"
[
uuid
(
5E9072D7
-
FF95
-
455E
-
9466
-
8AF9841A72EC
)
]
interface
nsIMacUtils
:
nsISupports
{
readonly
attribute
AString
architecturesInBinary
;
readonly
attribute
boolean
isTranslated
;
}
;
