#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
048a24f6
-
c4d6
-
47bc
-
bea2
-
f6038d1db80a
)
]
interface
nsIAutoplay
:
nsISupports
{
const
uint32_t
ALLOWED
=
0
;
const
uint32_t
BLOCKED
=
1
;
const
uint32_t
BLOCKED_ALL
=
5
;
}
;
