#
include
"
nsISupports
.
idl
"
webidl
Element
;
webidl
PictureInPictureWindow
;
[
scriptable
uuid
(
b6d8b8d7
-
8b81
-
493d
-
806d
-
fb10072e3afd
)
]
interface
nsIMediaPictureInPictureProvider
:
nsISupports
{
[
implicit_jscontext
]
Promise
openMediaPictureInPictureWindow
(
in
Element
videoElement
in
PictureInPictureWindow
pictureInPictureWindow
)
;
[
implicit_jscontext
]
Promise
closeMediaPictureInPictureWindow
(
in
Element
videoElement
)
;
}
;
