#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
ea51e0b8
-
871c
-
4b85
-
92da
-
6f400394c5ec
)
]
interface
nsIHTTPHeaderListener
:
nsISupports
{
void
newResponseHeader
(
in
string
headerName
in
string
headerValue
)
;
void
statusLine
(
in
string
line
)
;
}
;
