#
include
"
nsIInputStream
.
idl
"
#
include
"
nspluginroot
.
idl
"
[
uuid
(
af160530
-
542a
-
11d2
-
8164
-
006008119d7a
)
]
interface
nsIPluginInputStream
:
nsIInputStream
{
void
getLastModified
(
out
unsigned
long
aResult
)
;
void
requestRead
(
out
NPByteRange
aRangeList
)
;
}
;
