#
include
"
nsISupports
.
idl
"
interface
nsIScriptError
;
[
scriptable
uuid
(
01f681af
-
0f22
-
4725
-
a914
-
0d396114daf0
)
]
interface
nsIExpatSink
:
nsISupports
{
void
HandleStartElement
(
in
wstring
aName
[
array
size_is
(
aAttsCount
)
]
in
wstring
aAtts
in
unsigned
long
aAttsCount
in
unsigned
long
aLineNumber
in
unsigned
long
aColumnNumber
)
;
void
HandleEndElement
(
in
wstring
aName
)
;
void
HandleComment
(
in
wstring
aCommentText
)
;
void
HandleCDataSection
(
[
size_is
(
aLength
)
]
in
wstring
aData
in
unsigned
long
aLength
)
;
void
HandleDoctypeDecl
(
in
AString
aSubset
in
AString
aName
in
AString
aSystemId
in
AString
aPublicId
in
nsISupports
aCatalogData
)
;
void
HandleCharacterData
(
[
size_is
(
aLength
)
]
in
wstring
aData
in
unsigned
long
aLength
)
;
void
HandleProcessingInstruction
(
in
wstring
aTarget
in
wstring
aData
)
;
void
HandleXMLDeclaration
(
in
wstring
aVersion
in
wstring
aEncoding
in
long
aStandalone
)
;
boolean
ReportError
(
in
wstring
aErrorText
in
wstring
aSourceText
in
nsIScriptError
aError
)
;
}
;
