#
include
"
nsISupports
.
idl
"
interface
nsIRunnable
;
%
{
C
+
+
template
<
class
T
>
struct
already_AddRefed
;
#
define
DEFAULT_TIMEZONE_CHANGED_OBSERVER_TOPIC
"
default
-
timezone
-
changed
"
%
}
[
uuid
(
7cd5c71d
-
223b
-
4afe
-
931d
-
5eedb1f2b01f
)
]
interface
nsIAppShell
:
nsISupports
{
void
run
(
)
;
void
exit
(
)
;
void
favorPerformanceHint
(
in
boolean
favorPerfOverStarvation
in
unsigned
long
starvationDelay
)
;
void
suspendNative
(
)
;
void
resumeNative
(
)
;
readonly
attribute
unsigned
long
eventloopNestingLevel
;
}
;
