#
include
"
nsISupports
.
idl
"
[
builtinclass
scriptable
uuid
(
288dae24
-
76e2
-
43a3
-
befe
-
9d9fabe8014e
)
]
interface
nsIBidiKeyboard
:
nsISupports
{
void
reset
(
)
;
boolean
isLangRTL
(
)
;
readonly
attribute
boolean
haveBidiKeyboards
;
}
;
