#
include
"
nsISupports
.
idl
"
interface
mozIDOMWindowProxy
;
[
scriptable
uuid
(
d2ce78d1
-
40b5
-
49d1
-
b66d
-
5801fcb9a385
)
]
interface
nsIColorPickerShownCallback
:
nsISupports
{
void
update
(
in
AString
color
)
;
void
done
(
in
AString
color
)
;
}
;
[
scriptable
uuid
(
de229d37
-
a8a6
-
46f1
-
969a
-
0c1de33d0ad7
)
]
interface
nsIColorPicker
:
nsISupports
{
void
init
(
in
mozIDOMWindowProxy
parent
in
AString
title
in
AString
initialColor
in
Array
<
AString
>
defaultColors
)
;
void
open
(
in
nsIColorPickerShownCallback
aColorPickerShownCallback
)
;
}
;
