#
include
"
nsISupports
.
idl
"
interface
nsIURI
;
[
scriptable
uuid
(
5769F08D
-
0303
-
4E38
-
8FE6
-
86B5473022F6
)
]
interface
nsIJumpListBuilder
:
nsISupports
{
AString
obtainAndCacheFavicon
(
in
nsIURI
faviconURL
)
;
[
implicit_jscontext
]
Promise
obtainAndCacheFaviconAsync
(
in
nsIURI
faviconURL
)
;
[
implicit_jscontext
]
Promise
isAvailable
(
)
;
[
implicit_jscontext
]
Promise
checkForRemovals
(
)
;
[
implicit_jscontext
]
Promise
populateJumpList
(
in
jsval
aTaskDescriptions
in
AString
aCustomTitle
in
jsval
aCustomDescriptions
)
;
[
implicit_jscontext
]
Promise
clearJumpList
(
)
;
}
;
