#
include
"
nsISupports
.
idl
"
interface
nsIURI
;
interface
nsILocalHandlerApp
;
interface
nsIMutableArray
;
[
scriptable
uuid
(
ACB8FB3C
-
E1B0
-
4044
-
8A50
-
E52C3E7C1057
)
]
interface
nsILegacyJumpListItem
:
nsISupports
{
const
short
JUMPLIST_ITEM_EMPTY
=
0
;
const
short
JUMPLIST_ITEM_SEPARATOR
=
1
;
const
short
JUMPLIST_ITEM_LINK
=
2
;
const
short
JUMPLIST_ITEM_SHORTCUT
=
3
;
readonly
attribute
short
type
;
boolean
equals
(
in
nsILegacyJumpListItem
item
)
;
}
;
[
scriptable
uuid
(
69A2D5C5
-
14DC
-
47da
-
925D
-
869E0BD64D27
)
]
interface
nsILegacyJumpListSeparator
:
nsILegacyJumpListItem
{
}
;
[
scriptable
uuid
(
76EA47B1
-
C797
-
49b3
-
9F18
-
5E740A688524
)
]
interface
nsILegacyJumpListLink
:
nsILegacyJumpListItem
{
attribute
nsIURI
uri
;
attribute
AString
uriTitle
;
}
;
[
scriptable
uuid
(
CBE3A37C
-
BCE1
-
4fec
-
80A5
-
5FFBC7F33EEA
)
]
interface
nsILegacyJumpListShortcut
:
nsILegacyJumpListItem
{
attribute
nsILocalHandlerApp
app
;
attribute
long
iconIndex
;
attribute
nsIURI
faviconPageUri
;
}
;
