#
include
"
nsISupports
.
idl
"
%
{
C
+
+
#
include
"
windows
.
h
"
%
}
[
ptr
]
native
nsDevMode
(
DEVMODEW
)
;
native
nsHdc
(
HDC
)
;
[
uuid
(
c63eed41
-
6ac5
-
459e
-
8a64
-
033eb9ad770a
)
]
interface
nsIPrintSettingsWin
:
nsISupports
{
[
noscript
]
attribute
AString
deviceName
;
[
noscript
]
attribute
AString
driverName
;
[
noscript
]
attribute
nsDevMode
devMode
;
[
notxpcom
]
void
copyFromNative
(
in
nsHdc
hdc
in
nsDevMode
devMode
)
;
[
notxpcom
]
void
copyToNative
(
in
nsDevMode
devMode
)
;
}
;
