#
include
"
nsISupports
.
idl
"
#
include
"
nsIPrinter
.
idl
"
#
include
"
nsIPrintSettings
.
idl
"
[
scriptable
uuid
(
5e738fff
-
404c
-
4c94
-
9189
-
e8f2cce93e94
)
]
interface
nsIPrinterList
:
nsISupports
{
void
initPrintSettingsFromPrinter
(
in
AString
aPrinterName
in
nsIPrintSettings
aPrintSettings
)
;
readonly
attribute
AString
systemDefaultPrinterName
;
[
implicit_jscontext
]
Promise
getNamedPrinter
(
in
AString
aPrinterName
)
;
[
implicit_jscontext
]
Promise
getNamedOrDefaultPrinter
(
in
AString
aPrinterName
)
;
[
implicit_jscontext
]
readonly
attribute
Promise
printers
;
[
implicit_jscontext
]
readonly
attribute
Promise
fallbackPaperList
;
}
;
