#
include
"
nsISupports
.
idl
"
#
include
"
nsIWebProgressListener
.
idl
"
#
include
"
nsIPrintSettings
.
idl
"
#
include
"
nsIObserver
.
idl
"
interface
mozIDOMWindowProxy
;
[
scriptable
uuid
(
88af6712
-
a9fd
-
4393
-
9af3
-
3ffbb1f2caaf
)
]
interface
nsIPrintDialogService
:
nsISupports
{
void
init
(
)
;
void
showPrintDialog
(
in
mozIDOMWindowProxy
aParent
in
boolean
aHaveSelection
in
nsIPrintSettings
aPrintSettings
)
;
void
showPageSetupDialog
(
in
mozIDOMWindowProxy
aParent
in
nsIPrintSettings
aPrintSettings
)
;
}
;
