#
include
"
nsIPaper
.
idl
"
#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
d2dde9bb
-
df86
-
469c
-
bfcc
-
fd95a44b1db8
)
]
interface
nsIPrinter
:
nsISupports
{
readonly
attribute
AString
name
;
[
implicit_jscontext
]
readonly
attribute
Promise
paperList
;
[
implicit_jscontext
]
readonly
attribute
Promise
supportsDuplex
;
[
implicit_jscontext
]
readonly
attribute
Promise
supportsColor
;
[
implicit_jscontext
]
readonly
attribute
Promise
supportsCollation
;
}
;
