#
include
"
nsISupports
.
idl
"
interface
nsIPrintSettings
;
interface
nsIWebBrowserPrint
;
%
{
C
+
+
namespace
mozilla
{
namespace
embedding
{
class
PrintData
;
}
}
%
}
[
ref
]
native
PrintDataRef
(
const
mozilla
:
:
embedding
:
:
PrintData
)
;
[
ptr
]
native
PrintDataPtr
(
mozilla
:
:
embedding
:
:
PrintData
)
;
[
scriptable
uuid
(
841387C8
-
72E6
-
484b
-
9296
-
BF6EEA80D58A
)
]
interface
nsIPrintSettingsService
:
nsISupports
{
readonly
attribute
nsIPrintSettings
globalPrintSettings
;
[
noscript
]
readonly
attribute
nsIPrintSettings
defaultPrintSettingsForPrinting
;
readonly
attribute
nsIPrintSettings
newPrintSettings
;
readonly
attribute
AString
lastUsedPrinterName
;
void
initPrintSettingsFromPrinter
(
in
AString
aPrinterName
in
nsIPrintSettings
aPrintSettings
)
;
void
initPrintSettingsFromPrefs
(
in
nsIPrintSettings
aPrintSettings
in
boolean
aUsePrinterNamePrefix
in
unsigned
long
aFlags
)
;
void
savePrintSettingsToPrefs
(
in
nsIPrintSettings
aPrintSettings
in
boolean
aUsePrinterNamePrefix
in
unsigned
long
aFlags
)
;
[
noscript
]
void
SerializeToPrintData
(
in
nsIPrintSettings
aPrintSettings
in
PrintDataPtr
data
)
;
[
noscript
]
void
DeserializeToPrintSettings
(
in
PrintDataRef
data
in
nsIPrintSettings
aPrintSettings
)
;
}
;
%
{
C
+
+
#
define
NS_PRINTSETTINGSSERVICE_IID
\
{
0x841387c8
0x72e6
0x484b
{
0x92
0x96
0xbf
0x6e
0xea
0x80
0xd5
0x8a
}
}
%
}
