#
include
"
nsISupports
.
idl
"
%
{
C
+
+
#
include
"
nsMargin
.
h
"
#
include
"
nsTArray
.
h
"
namespace
mozilla
{
struct
PrintSettingsInitializer
;
}
%
}
native
nsNativeIntMargin
(
nsIntMargin
)
;
[
ref
]
native
nsNativeIntMarginRef
(
nsIntMargin
)
;
native
PrintSettingsInitializer
(
mozilla
:
:
PrintSettingsInitializer
)
;
interface
nsIOutputStream
;
[
scriptable
builtinclass
uuid
(
ecc5cbad
-
57fc
-
4731
-
b0bd
-
09e865bd62ad
)
]
interface
nsIPrintSettings
:
nsISupports
{
const
unsigned
long
kInitSaveHeaderLeft
=
0x00000002
;
const
unsigned
long
kInitSaveHeaderCenter
=
0x00000004
;
const
unsigned
long
kInitSaveHeaderRight
=
0x00000008
;
const
unsigned
long
kInitSaveFooterLeft
=
0x00000010
;
const
unsigned
long
kInitSaveFooterCenter
=
0x00000020
;
const
unsigned
long
kInitSaveFooterRight
=
0x00000040
;
const
unsigned
long
kInitSaveBGColors
=
0x00000080
;
const
unsigned
long
kInitSaveBGImages
=
0x00000100
;
const
unsigned
long
kInitSavePaperSize
=
0x00000200
;
const
unsigned
long
kInitSaveDuplex
=
0x00000800
;
const
unsigned
long
kInitSaveUnwriteableMargins
=
0x00004000
;
const
unsigned
long
kInitSaveEdges
=
0x00008000
;
const
unsigned
long
kInitSaveReversed
=
0x00010000
;
const
unsigned
long
kInitSaveInColor
=
0x00020000
;
const
unsigned
long
kInitSaveOrientation
=
0x00040000
;
const
unsigned
long
kInitSavePrinterName
=
0x00100000
;
const
unsigned
long
kInitSavePrintToFile
=
0x00200000
;
const
unsigned
long
kInitSaveToFileName
=
0x00400000
;
const
unsigned
long
kInitSavePageDelay
=
0x00800000
;
const
unsigned
long
kInitSaveMargins
=
0x01000000
;
const
unsigned
long
kInitSaveNativeData
=
0x02000000
;
const
unsigned
long
kInitSaveShrinkToFit
=
0x08000000
;
const
unsigned
long
kInitSaveScaling
=
0x10000000
;
const
unsigned
long
kInitSaveAll
=
0xFFFFFFFF
;
const
unsigned
long
kGlobalSettings
=
kInitSaveHeaderLeft
|
kInitSaveHeaderCenter
|
kInitSaveHeaderRight
|
kInitSaveFooterLeft
|
kInitSaveFooterCenter
|
kInitSaveFooterRight
|
kInitSaveEdges
|
kInitSaveReversed
|
kInitSaveInColor
|
kInitSaveBGColors
|
kInitSaveBGImages
|
kInitSaveShrinkToFit
;
const
long
kJustLeft
=
0
;
const
long
kJustCenter
=
1
;
const
long
kJustRight
=
2
;
const
short
kPaperSizeInches
=
0
;
const
short
kPaperSizeMillimeters
=
1
;
const
short
kPortraitOrientation
=
0
;
const
short
kLandscapeOrientation
=
1
;
const
short
kOutputFormatNative
=
0
;
const
short
kOutputFormatPDF
=
2
;
cenum
OutputDestinationType
:
8
{
kOutputDestinationPrinter
=
0
kOutputDestinationFile
=
1
kOutputDestinationStream
=
2
}
;
const
short
kDuplexNone
=
0
;
const
short
kDuplexFlipOnLongEdge
=
1
;
const
short
kDuplexFlipOnShortEdge
=
2
;
void
GetEffectivePageSize
(
out
double
aWidth
out
double
aHeight
)
;
[
noscript
notxpcom
nostdcall
]
void
GetEffectiveSheetSize
(
out
double
aWidth
out
double
aHeight
)
;
[
noscript
notxpcom
nostdcall
]
long
GetSheetOrientation
(
)
;
[
noscript
notxpcom
nostdcall
]
bool
HasOrthogonalSheetsAndPages
(
)
;
nsIPrintSettings
clone
(
)
;
void
assign
(
in
nsIPrintSettings
aPS
)
;
bool
equivalentTo
(
in
nsIPrintSettings
aPrintSettings
)
;
attribute
double
edgeTop
;
attribute
double
edgeLeft
;
attribute
double
edgeBottom
;
attribute
double
edgeRight
;
attribute
double
marginTop
;
attribute
double
marginLeft
;
attribute
double
marginBottom
;
attribute
double
marginRight
;
attribute
double
unwriteableMarginTop
;
attribute
double
unwriteableMarginLeft
;
attribute
double
unwriteableMarginBottom
;
attribute
double
unwriteableMarginRight
;
attribute
double
scaling
;
[
infallible
]
attribute
boolean
printBGColors
;
[
infallible
]
attribute
boolean
printBGImages
;
[
infallible
]
attribute
boolean
honorPageRuleMargins
;
[
infallible
]
attribute
boolean
ignoreUnwriteableMargins
;
[
infallible
]
attribute
boolean
showMarginGuides
;
[
infallible
]
attribute
boolean
printSelectionOnly
;
attribute
AString
title
;
attribute
AString
docURL
;
attribute
AString
headerStrLeft
;
attribute
AString
headerStrCenter
;
attribute
AString
headerStrRight
;
attribute
AString
footerStrLeft
;
attribute
AString
footerStrCenter
;
attribute
AString
footerStrRight
;
attribute
boolean
printSilent
;
[
infallible
]
attribute
boolean
shrinkToFit
;
attribute
AString
paperId
;
attribute
double
paperWidth
;
attribute
double
paperHeight
;
attribute
short
paperSizeUnit
;
attribute
boolean
printReversed
;
[
infallible
]
attribute
boolean
printInColor
;
attribute
long
orientation
;
attribute
long
numCopies
;
attribute
long
numPagesPerSheet
;
[
infallible
]
attribute
nsIPrintSettings_OutputDestinationType
outputDestination
;
[
infallible
]
attribute
short
outputFormat
;
attribute
AString
printerName
;
attribute
AString
toFileName
;
attribute
nsIOutputStream
outputStream
;
[
infallible
]
attribute
long
printPageDelay
;
[
infallible
]
attribute
long
resolution
;
[
infallible
]
attribute
long
duplex
;
attribute
boolean
isInitializedFromPrinter
;
attribute
boolean
isInitializedFromPrefs
;
[
noscript
]
void
SetMarginInTwips
(
in
nsNativeIntMarginRef
aMargin
)
;
[
noscript
]
void
SetEdgeInTwips
(
in
nsNativeIntMarginRef
aEdge
)
;
[
noscript
notxpcom
nostdcall
]
nsNativeIntMargin
GetMarginInTwips
(
)
;
[
noscript
notxpcom
nostdcall
]
nsNativeIntMargin
GetEdgeInTwips
(
)
;
[
noscript
]
void
SetUnwriteableMarginInTwips
(
in
nsNativeIntMarginRef
aEdge
)
;
[
noscript
notxpcom
nostdcall
]
nsNativeIntMargin
GetUnwriteableMarginInTwips
(
)
;
attribute
Array
<
long
>
pageRanges
;
[
notxpcom
nostdcall
]
PrintSettingsInitializer
getSettingsInitializer
(
)
;
%
{
C
+
+
static
bool
IsPageSkipped
(
int32_t
aPageNum
const
nsTArray
<
int32_t
>
&
aRanges
)
;
%
}
}
;
%
{
C
+
+
already_AddRefed
<
nsIPrintSettings
>
CreatePlatformPrintSettings
(
const
mozilla
:
:
PrintSettingsInitializer
&
)
;
%
}
