#
include
"
nsIPaper
.
idl
"
#
include
"
nsIPrintSettings
.
idl
"
#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
855ae9dd
-
62a4
-
64aa
-
9c60
-
b1078ff028f1
)
]
interface
nsIPrinterInfo
:
nsISupports
{
readonly
attribute
Array
<
nsIPaper
>
paperList
;
readonly
attribute
nsIPrintSettings
defaultSettings
;
}
;
[
scriptable
uuid
(
d2dde9bb
-
df86
-
469c
-
bfcc
-
fd95a44b1db8
)
]
interface
nsIPrinter
:
nsISupports
{
readonly
attribute
AString
name
;
readonly
attribute
AString
systemName
;
[
implicit_jscontext
]
readonly
attribute
Promise
printerInfo
;
[
implicit_jscontext
]
readonly
attribute
Promise
supportsDuplex
;
[
implicit_jscontext
]
readonly
attribute
Promise
supportsColor
;
[
implicit_jscontext
]
readonly
attribute
Promise
supportsMonochrome
;
[
implicit_jscontext
]
readonly
attribute
Promise
supportsCollation
;
}
;
