#
include
"
nsISupports
.
idl
"
#
include
"
nsIWebProgressListener
.
idl
"
#
include
"
nsIPrintSettings
.
idl
"
#
include
"
nsIObserver
.
idl
"
interface
mozIDOMWindowProxy
;
[
scriptable
uuid
(
88af6712
-
a9fd
-
4393
-
9af3
-
3ffbb1f2caaf
)
]
interface
nsIPrintDialogService
:
nsISupports
{
void
init
(
)
;
void
showPrintDialog
(
in
mozIDOMWindowProxy
aParent
in
nsIPrintSettings
aPrintSettings
)
;
void
showPageSetupDialog
(
in
mozIDOMWindowProxy
aParent
in
nsIPrintSettings
aPrintSettings
)
;
}
;
%
{
C
+
+
#
define
NS_PRINTDIALOGSERVICE_IID
\
{
0x88af6712
0xa9fd
0x4393
{
0x9a
0xf3
0x3f
0xfb
0xb1
0xf2
0xca
0xaf
}
}
#
define
NS_PRINTDIALOGSERVICE_CONTRACTID
\
(
"
mozilla
.
org
/
widget
/
printdialog
-
service
;
1
"
)
%
}
