#
include
"
nsIPaper
.
idl
"
#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
d2dde9bb
-
df86
-
469c
-
bfcc
-
fd95a44b1db8
)
]
interface
nsIPrinter
:
nsISupports
{
readonly
attribute
AString
name
;
readonly
attribute
Array
<
nsIPaper
>
paperList
;
readonly
attribute
boolean
supportsDuplex
;
readonly
attribute
boolean
supportsColor
;
}
;
