#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
a4dd9675
-
6311
-
45a9
-
a547
-
44e0127304a6
)
]
interface
nsIPaper
:
nsISupports
{
readonly
attribute
AString
id
;
readonly
attribute
AString
name
;
readonly
attribute
double
width
;
readonly
attribute
double
height
;
[
implicit_jscontext
]
readonly
attribute
Promise
unwriteableMargin
;
}
;
