#
include
"
nsITaskbarPreview
.
idl
"
interface
nsITaskbarPreviewButton
;
[
scriptable
uuid
(
EC67CC57
-
342D
-
4064
-
B4C6
-
74A375E07B10
)
]
interface
nsITaskbarWindowPreview
:
nsITaskbarPreview
{
const
long
NUM_TOOLBAR_BUTTONS
=
7
;
nsITaskbarPreviewButton
getButton
(
in
unsigned
long
index
)
;
attribute
boolean
enableCustomDrawing
;
}
;
