#
include
"
nsISupports
.
idl
"
interface
imgIContainer
;
[
scriptable
uuid
(
CED8842D
-
FE37
-
4767
-
9A8E
-
FDFA56510C75
)
]
interface
nsITaskbarPreviewButton
:
nsISupports
{
attribute
AString
tooltip
;
attribute
boolean
dismissOnClick
;
attribute
boolean
hasBorder
;
attribute
boolean
disabled
;
attribute
imgIContainer
image
;
attribute
boolean
visible
;
}
;
