#
include
"
nsITaskbarPreview
.
idl
"
interface
imgIContainer
;
[
scriptable
builtinclass
uuid
(
11E4C8BD
-
5C2D
-
4E1A
-
A9A1
-
79DD5B0FE544
)
]
interface
nsITaskbarTabPreview
:
nsITaskbarPreview
{
attribute
AString
title
;
attribute
imgIContainer
icon
;
void
move
(
in
nsITaskbarTabPreview
aNext
)
;
[
notxpcom
]
nativeWindow
GetHWND
(
)
;
[
notxpcom
]
void
EnsureRegistration
(
)
;
}
;
