#
include
"
nsISupports
.
idl
"
#
include
"
nsIBaseWindow
.
idl
"
interface
nsITaskbarPreviewController
;
[
scriptable
uuid
(
CBFDF766
-
D002
-
403B
-
A3D9
-
B091C9AD465B
)
]
interface
nsITaskbarPreview
:
nsISupports
{
attribute
nsITaskbarPreviewController
controller
;
attribute
AString
tooltip
;
attribute
boolean
visible
;
attribute
boolean
active
;
void
invalidate
(
)
;
}
;
