#
include
"
nsISupports
.
idl
"
#
include
"
nsIBaseWindow
.
idl
"
interface
nsIDocShell
;
interface
nsITaskbarTabPreview
;
interface
nsITaskbarWindowPreview
;
interface
nsITaskbarPreviewController
;
interface
nsITaskbarProgress
;
interface
nsITaskbarOverlayIconController
;
interface
nsIJumpListBuilder
;
interface
mozIDOMWindow
;
[
scriptable
uuid
(
11751471
-
9246
-
4c72
-
a80f
-
0c7df765d640
)
]
interface
nsIWinTaskbar
:
nsISupports
{
readonly
attribute
boolean
available
;
readonly
attribute
AString
defaultGroupId
;
nsITaskbarTabPreview
createTaskbarTabPreview
(
in
nsIDocShell
shell
in
nsITaskbarPreviewController
controller
)
;
nsITaskbarWindowPreview
getTaskbarWindowPreview
(
in
nsIDocShell
shell
)
;
nsITaskbarProgress
getTaskbarProgress
(
in
nsIDocShell
shell
)
;
nsITaskbarOverlayIconController
getOverlayIconController
(
in
nsIDocShell
shell
)
;
nsIJumpListBuilder
createJumpListBuilder
(
)
;
void
setGroupIdForWindow
(
in
mozIDOMWindow
aParent
in
AString
aIdentifier
)
;
void
prepareFullScreen
(
in
mozIDOMWindow
aWindow
in
boolean
aFullScreen
)
;
[
noscript
]
void
prepareFullScreenHWND
(
in
voidPtr
aWindow
in
boolean
aFullScreen
)
;
}
;
