#
include
"
nsISupports
.
idl
"
interface
mozIDOMWindowProxy
;
interface
imgIContainer
;
[
scriptable
uuid
(
aa8a0ecf
-
96a1
-
418c
-
b80e
-
f24ae18bbedc
)
]
interface
nsIWindowsUIUtils
:
nsISupports
{
readonly
attribute
long
systemSmallIconSize
;
readonly
attribute
long
systemLargeIconSize
;
void
setWindowIcon
(
in
mozIDOMWindowProxy
aWindow
in
imgIContainer
aSmallIcon
in
imgIContainer
aLargeIcon
)
;
void
setWindowIconNoData
(
in
mozIDOMWindowProxy
aWindow
)
;
readonly
attribute
boolean
inTabletMode
;
void
updateTabletModeState
(
)
;
void
shareUrl
(
in
AString
shareTitle
in
AString
urlToShare
)
;
}
;
