#
include
"
nsISupports
.
idl
"
[
scriptable
builtinclass
uuid
(
47B82B60
-
A36F
-
4167
-
8072
-
6F421151ED50
)
]
interface
nsIControllerContext
:
nsISupports
{
void
setCommandContext
(
in
nsISupports
aCommandContext
)
;
}
;
