#
include
"
nsISupports
.
idl
"
%
{
C
+
+
class
nsCommandParams
;
%
}
[
scriptable
builtinclass
uuid
(
b1fdf3c4
-
74e3
-
4f7d
-
a14d
-
2b76bcf53482
)
]
interface
nsICommandParams
:
nsISupports
{
const
short
eNoType
=
0
;
const
short
eBooleanType
=
1
;
const
short
eLongType
=
2
;
const
short
eDoubleType
=
3
;
const
short
eWStringType
=
4
;
const
short
eISupportsType
=
5
;
const
short
eStringType
=
6
;
short
getValueType
(
in
string
name
)
;
boolean
getBooleanValue
(
in
string
name
)
;
long
getLongValue
(
in
string
name
)
;
double
getDoubleValue
(
in
string
name
)
;
AString
getStringValue
(
in
string
name
)
;
ACString
getCStringValue
(
in
string
name
)
;
nsISupports
getISupportsValue
(
in
string
name
)
;
void
setBooleanValue
(
in
string
name
in
boolean
value
)
;
void
setLongValue
(
in
string
name
in
long
value
)
;
void
setDoubleValue
(
in
string
name
in
double
value
)
;
void
setStringValue
(
in
string
name
in
AString
value
)
;
void
setCStringValue
(
in
string
name
in
ACString
value
)
;
void
setISupportsValue
(
in
string
name
in
nsISupports
value
)
;
void
removeValue
(
in
string
name
)
;
%
{
C
+
+
inline
nsCommandParams
*
AsCommandParams
(
)
;
inline
const
nsCommandParams
*
AsCommandParams
(
)
const
;
%
}
}
;
