#
include
"
nsISupports
.
idl
"
#
include
"
nsICommandParams
.
idl
"
[
scriptable
uuid
(
0eae9a46
-
1dd2
-
11b2
-
aca0
-
9176f05fe9db
)
]
interface
nsIControllerCommand
:
nsISupports
{
boolean
isCommandEnabled
(
in
string
aCommandName
in
nsISupports
aCommandContext
)
;
void
getCommandStateParams
(
in
string
aCommandName
in
nsICommandParams
aParams
in
nsISupports
aCommandContext
)
;
[
can_run_script
]
void
doCommand
(
in
string
aCommandName
in
nsISupports
aCommandContext
)
;
[
can_run_script
]
void
doCommandParams
(
in
string
aCommandName
in
nsICommandParams
aParams
in
nsISupports
aCommandContext
)
;
}
;
