#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
cdeca40d
-
74f4
-
44a2
-
beb3
-
84cd0bbc7785
)
]
interface
nsIQuotaUtilsService
:
nsISupports
{
unsigned
long
getPrivateIdentityId
(
in
AString
aName
)
;
}
;
