#
include
"
nsISupports
.
idl
"
interface
nsIPrincipal
;
interface
nsIQuotaRequest
;
interface
nsIQuotaCallback
;
interface
nsIQuotaUsageCallback
;
interface
nsIQuotaUsageRequest
;
[
scriptable
builtinclass
uuid
(
1b3d0a38
-
8151
-
4cf9
-
89fa
-
4f92c2ef0e7e
)
]
interface
nsIQuotaManagerService
:
nsISupports
{
[
must_use
]
nsIQuotaRequest
storageName
(
)
;
[
must_use
]
nsIQuotaRequest
storageInitialized
(
)
;
[
must_use
]
nsIQuotaRequest
temporaryStorageInitialized
(
)
;
[
must_use
]
nsIQuotaRequest
init
(
)
;
[
must_use
]
nsIQuotaRequest
initTemporaryStorage
(
)
;
[
must_use
]
nsIQuotaRequest
initializePersistentOrigin
(
in
nsIPrincipal
aPrincipal
)
;
[
must_use
]
nsIQuotaRequest
initializeTemporaryOrigin
(
in
ACString
aPersistenceType
in
nsIPrincipal
aPrincipal
)
;
[
must_use
]
nsIQuotaRequest
getFullOriginMetadata
(
in
ACString
aPersistenceType
in
nsIPrincipal
aPrincipal
)
;
[
must_use
]
nsIQuotaUsageRequest
getUsage
(
in
nsIQuotaUsageCallback
aCallback
[
optional
]
in
boolean
aGetAll
)
;
[
must_use
]
nsIQuotaUsageRequest
getUsageForPrincipal
(
in
nsIPrincipal
aPrincipal
in
nsIQuotaUsageCallback
aCallback
[
optional
]
in
boolean
aFromMemory
)
;
[
must_use
]
nsIQuotaRequest
listOrigins
(
)
;
[
must_use
]
nsIQuotaRequest
clear
(
)
;
[
must_use
]
nsIQuotaRequest
clearStoragesForPrivateBrowsing
(
)
;
[
must_use
]
nsIQuotaRequest
clearStoragesForOriginAttributesPattern
(
in
AString
aPattern
)
;
[
must_use
]
nsIQuotaRequest
clearStoragesForPrincipal
(
in
nsIPrincipal
aPrincipal
[
optional
]
in
ACString
aPersistenceType
[
optional
]
in
AString
aClientType
[
optional
]
in
boolean
aClearAll
)
;
[
must_use
]
nsIQuotaRequest
reset
(
)
;
[
must_use
]
nsIQuotaRequest
resetStoragesForPrincipal
(
in
nsIPrincipal
aPrincipal
[
optional
]
in
ACString
aPersistenceType
[
optional
]
in
AString
aClientType
)
;
[
must_use
]
nsIQuotaRequest
persisted
(
in
nsIPrincipal
aPrincipal
)
;
[
must_use
]
nsIQuotaRequest
persist
(
in
nsIPrincipal
aPrincipal
)
;
[
must_use
]
nsIQuotaRequest
estimate
(
in
nsIPrincipal
aPrincipal
)
;
}
;
