#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
9a28937E
-
997f
-
4962
-
9422
-
f8a2103214bc
)
]
interface
nsIQuotaArtificialFailure
:
nsISupports
{
cenum
Category
:
32
{
CATEGORY_NONE
=
0
}
;
}
;
