#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
8cd92fce
-
1ec3
-
470a
-
ad09
-
c0de9d98497e
)
]
interface
nsIBackgroundTasksRunner
:
nsISupports
{
void
runInDetachedProcess
(
in
ACString
aTaskName
in
Array
<
ACString
>
aCommandLine
)
;
void
removeDirectoryInDetachedProcess
(
in
ACString
aParentDirPath
in
ACString
aChildDirName
in
ACString
aSecondsToWait
in
ACString
aOtherFoldersSuffix
)
;
}
;
