#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
353dccb8
-
a863
-
49e4
-
941b
-
007382eac168
)
]
interface
nsIBackgroundTasks
:
nsISupports
{
readonly
attribute
boolean
isBackgroundTaskMode
;
AString
backgroundTaskName
(
)
;
void
overrideBackgroundTaskNameForTesting
(
in
AString
taskName
)
;
}
;
