#
include
"
nsICommandLineHandler
.
idl
"
interface
nsICommandLine
;
[
scriptable
uuid
(
4d48c536
-
e16f
-
4699
-
8f9c
-
add4f28f92f0
)
]
interface
nsIBackgroundTasksManager
:
nsICommandLineHandler
{
void
runBackgroundTaskNamed
(
in
AString
aTaskName
in
nsICommandLine
aCommandLine
)
;
}
;
