#
include
"
nsISupports
.
idl
"
interface
nsIPrincipal
;
[
scriptable
builtinclass
uuid
(
d4f534da
-
2744
-
4db3
-
8774
-
8b187c64ade9
)
]
interface
nsILocalStorageManager
:
nsISupports
{
readonly
attribute
boolean
nextGenLocalStorageEnabled
;
[
implicit_jscontext
]
Promise
preload
(
in
nsIPrincipal
aPrincipal
)
;
[
implicit_jscontext
]
Promise
isPreloaded
(
in
nsIPrincipal
aPrincipal
)
;
[
implicit_jscontext
]
Promise
getState
(
in
nsIPrincipal
aPrincipal
)
;
}
;
