#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
CA89B55B
-
6FAF
-
4051
-
9645
-
1C03EF5108F8
)
]
interface
nsIPrintProgressParams
:
nsISupports
{
attribute
AString
docTitle
;
attribute
AString
docURL
;
}
;
