#
include
"
nsIWebProgressListener
.
idl
"
interface
mozIDOMWindowProxy
;
interface
nsIObserver
;
interface
nsIPrompt
;
[
scriptable
uuid
(
05f4fb88
-
e568
-
4d35
-
b394
-
ce0aa3eea6fc
)
]
interface
nsIPrintProgress
:
nsIWebProgressListener
{
void
openProgressDialog
(
in
mozIDOMWindowProxy
parent
in
string
dialogURL
in
nsISupports
parameters
in
nsIObserver
openDialogObserver
out
boolean
notifyOnOpen
)
;
void
closeProgressDialog
(
in
boolean
forceClose
)
;
void
registerListener
(
in
nsIWebProgressListener
listener
)
;
void
unregisterListener
(
in
nsIWebProgressListener
listener
)
;
void
doneIniting
(
)
;
nsIPrompt
getPrompter
(
)
;
attribute
boolean
processCanceledByUser
;
}
;
