#
include
"
nsISupports
.
idl
"
interface
nsIArray
;
interface
nsIProfileStartup
;
[
scriptable
uuid
(
22b56ffc
-
3149
-
43c5
-
b5a9
-
b3a6b678de93
)
]
interface
nsIBrowserProfileMigrator
:
nsISupports
{
void
migrate
(
in
unsigned
short
aItems
in
nsIProfileStartup
aStartup
in
jsval
aProfile
)
;
jsval
getMigrateData
(
in
jsval
aProfile
)
;
jsval
getLastUsedDate
(
)
;
jsval
isSourceAvailable
(
)
;
jsval
getSourceProfiles
(
)
;
readonly
attribute
boolean
enabled
;
}
;
