#
include
"
nsISupports
.
idl
"
interface
nsIArray
;
interface
nsIProfileStartup
;
[
scriptable
uuid
(
22b56ffc
-
3149
-
43c5
-
b5a9
-
b3a6b678de93
)
]
interface
nsIBrowserProfileMigrator
:
nsISupports
{
const
unsigned
short
ALL
=
0x0000
;
const
unsigned
short
COOKIES
=
0x0002
;
const
unsigned
short
HISTORY
=
0x0004
;
const
unsigned
short
FORMDATA
=
0x0008
;
const
unsigned
short
PASSWORDS
=
0x0010
;
const
unsigned
short
BOOKMARKS
=
0x0020
;
const
unsigned
short
OTHERDATA
=
0x0040
;
const
unsigned
short
SESSION
=
0x0080
;
void
migrate
(
in
unsigned
short
aItems
in
nsIProfileStartup
aStartup
in
jsval
aProfile
)
;
jsval
getMigrateData
(
in
jsval
aProfile
)
;
jsval
getLastUsedDate
(
)
;
jsval
isSourceAvailable
(
)
;
jsval
getSourceProfiles
(
)
;
readonly
attribute
boolean
sourceLocked
;
readonly
attribute
boolean
enabled
;
}
;
