#
include
"
nsISupports
.
idl
"
[
scriptable
builtinclass
uuid
(
05cd38b1
-
94b3
-
4cdf
-
8371
-
3935a9611405
)
]
interface
nsIAccessibleScrollType
:
nsISupports
{
const
unsigned
long
SCROLL_TYPE_TOP_LEFT
=
0x00
;
const
unsigned
long
SCROLL_TYPE_BOTTOM_RIGHT
=
0x01
;
const
unsigned
long
SCROLL_TYPE_TOP_EDGE
=
0x02
;
const
unsigned
long
SCROLL_TYPE_BOTTOM_EDGE
=
0x03
;
const
unsigned
long
SCROLL_TYPE_LEFT_EDGE
=
0x04
;
const
unsigned
long
SCROLL_TYPE_RIGHT_EDGE
=
0x05
;
const
unsigned
long
SCROLL_TYPE_ANYWHERE
=
0x06
;
}
;
[
scriptable
builtinclass
uuid
(
c9fbdf10
-
619e
-
436f
-
bf4b
-
8566686f1577
)
]
interface
nsIAccessibleCoordinateType
:
nsISupports
{
const
unsigned
long
COORDTYPE_SCREEN_RELATIVE
=
0x00
;
const
unsigned
long
COORDTYPE_WINDOW_RELATIVE
=
0x01
;
const
unsigned
long
COORDTYPE_PARENT_RELATIVE
=
0x02
;
}
;
