#
include
"
nsISupports
.
idl
"
#
include
"
nsIArray
.
idl
"
#
include
"
nsIAccessibleText
.
idl
"
interface
nsIAccessible
;
[
scriptable
builtinclass
uuid
(
9181e777
-
8954
-
4f8f
-
8cee
-
32f9771e40d7
)
]
interface
nsIAccessibleTextLeafPoint
:
nsISupports
{
attribute
nsIAccessible
accessible
;
attribute
long
offset
;
nsIAccessibleTextLeafPoint
findBoundary
(
in
AccessibleTextBoundary
aBoundaryType
in
unsigned
long
aDirection
in
unsigned
long
aFlags
)
;
const
long
DIRECTION_NEXT
=
0x0
;
const
long
DIRECTION_PREVIOUS
=
0x1
;
const
unsigned
long
BOUNDARY_FLAG_DEFAULT
=
0x0
;
const
unsigned
long
BOUNDARY_FLAG_INCLUDE_ORIGIN
=
0x1
;
const
unsigned
long
BOUNDARY_FLAG_STOP_IN_EDITABLE
=
0x2
;
}
;
