#
include
"
nsISupports
.
idl
"
#
include
"
nsIArray
.
idl
"
interface
nsIAccessible
;
[
scriptable
builtinclass
uuid
(
55b308c4
-
2ae4
-
46bc
-
b4cd
-
4d4370e0a660
)
]
interface
nsIAccessibleRelation
:
nsISupports
{
const
unsigned
long
RELATION_LABELLED_BY
=
0x00
;
const
unsigned
long
RELATION_LABEL_FOR
=
0x01
;
const
unsigned
long
RELATION_DESCRIBED_BY
=
0x02
;
const
unsigned
long
RELATION_DESCRIPTION_FOR
=
0x3
;
const
unsigned
long
RELATION_NODE_CHILD_OF
=
0x4
;
const
unsigned
long
RELATION_NODE_PARENT_OF
=
0x5
;
const
unsigned
long
RELATION_CONTROLLED_BY
=
0x06
;
const
unsigned
long
RELATION_CONTROLLER_FOR
=
0x07
;
const
unsigned
long
RELATION_FLOWS_TO
=
0x08
;
const
unsigned
long
RELATION_FLOWS_FROM
=
0x09
;
const
unsigned
long
RELATION_MEMBER_OF
=
0x0a
;
const
unsigned
long
RELATION_SUBWINDOW_OF
=
0x0b
;
const
unsigned
long
RELATION_EMBEDS
=
0x0c
;
const
unsigned
long
RELATION_EMBEDDED_BY
=
0x0d
;
const
unsigned
long
RELATION_POPUP_FOR
=
0x0e
;
const
unsigned
long
RELATION_PARENT_WINDOW_OF
=
0x0f
;
const
unsigned
long
RELATION_DEFAULT_BUTTON
=
0x10
;
const
unsigned
long
RELATION_CONTAINING_DOCUMENT
=
0x11
;
const
unsigned
long
RELATION_CONTAINING_TAB_PANE
=
0x12
;
const
unsigned
long
RELATION_CONTAINING_WINDOW
=
0x13
;
const
unsigned
long
RELATION_CONTAINING_APPLICATION
=
0x14
;
const
unsigned
long
RELATION_DETAILS
=
0x15
;
const
unsigned
long
RELATION_DETAILS_FOR
=
0x16
;
const
unsigned
long
RELATION_ERRORMSG
=
0x17
;
const
unsigned
long
RELATION_ERRORMSG_FOR
=
0x18
;
const
unsigned
long
RELATION_LINKS_TO
=
0x19
;
const
unsigned
long
RELATION_ACTION
=
0x20
;
const
unsigned
long
RELATION_ACTION_FOR
=
0x21
;
readonly
attribute
unsigned
long
relationType
;
readonly
attribute
unsigned
long
targetsCount
;
nsIAccessible
getTarget
(
in
unsigned
long
index
)
;
nsIArray
getTargets
(
)
;
}
;
