#
include
"
nsIAccessibleEvent
.
idl
"
[
scriptable
builtinclass
uuid
(
58b74954
-
1835
-
46ed
-
9ccd
-
c906490106f6
)
]
interface
nsIAccessibleStateChangeEvent
:
nsIAccessibleEvent
{
readonly
attribute
unsigned
long
state
;
readonly
attribute
boolean
isExtraState
;
readonly
attribute
boolean
isEnabled
;
}
;
