#
include
"
nsIAccessibleEvent
.
idl
"
[
scriptable
builtinclass
uuid
(
8818e49c
-
1286
-
4fe6
-
ae82
-
4d1b795ec88d
)
]
interface
nsIAccessibleAnnouncementEvent
:
nsIAccessibleEvent
{
const
unsigned
short
POLITE
=
0
;
const
unsigned
short
ASSERTIVE
=
1
;
readonly
attribute
AString
announcement
;
readonly
attribute
unsigned
short
priority
;
}
;
