#
include
"
nsISupports
.
idl
"
interface
nsIAccessible
;
interface
nsIArray
;
[
scriptable
builtinclass
uuid
(
cb0bf7b9
-
117e
-
40e2
-
9e46
-
189c3d43ce4a
)
]
interface
nsIAccessibleTable
:
nsISupports
{
readonly
attribute
nsIAccessible
caption
;
readonly
attribute
AString
summary
;
readonly
attribute
long
columnCount
;
readonly
attribute
long
rowCount
;
nsIAccessible
getCellAt
(
in
long
rowIndex
in
long
columnIndex
)
;
long
getCellIndexAt
(
in
long
rowIndex
in
long
columnIndex
)
;
long
getColumnIndexAt
(
in
long
cellIndex
)
;
long
getRowIndexAt
(
in
long
cellIndex
)
;
void
getRowAndColumnIndicesAt
(
in
long
cellIndex
out
long
rowIndex
out
long
columnIndex
)
;
long
getColumnExtentAt
(
in
long
row
in
long
column
)
;
long
getRowExtentAt
(
in
long
row
in
long
column
)
;
AString
getColumnDescription
(
in
long
columnIndex
)
;
AString
getRowDescription
(
in
long
rowIndex
)
;
boolean
isColumnSelected
(
in
long
columnIndex
)
;
boolean
isRowSelected
(
in
long
rowIndex
)
;
boolean
isCellSelected
(
in
long
rowIndex
in
long
columnIndex
)
;
readonly
attribute
unsigned
long
selectedCellCount
;
readonly
attribute
unsigned
long
selectedColumnCount
;
readonly
attribute
unsigned
long
selectedRowCount
;
readonly
attribute
nsIArray
selectedCells
;
Array
<
uint32_t
>
getSelectedCellIndices
(
)
;
Array
<
uint32_t
>
getSelectedColumnIndices
(
)
;
Array
<
uint32_t
>
getSelectedRowIndices
(
)
;
boolean
isProbablyForLayout
(
)
;
}
;
[
scriptable
builtinclass
uuid
(
654e296d
-
fae6
-
452b
-
987d
-
746b20b9514b
)
]
interface
nsIAccessibleTableCell
:
nsISupports
{
readonly
attribute
nsIAccessibleTable
table
;
readonly
attribute
long
columnIndex
;
readonly
attribute
long
rowIndex
;
readonly
attribute
long
columnExtent
;
readonly
attribute
long
rowExtent
;
readonly
attribute
nsIArray
columnHeaderCells
;
readonly
attribute
nsIArray
rowHeaderCells
;
boolean
isSelected
(
)
;
}
;
