#
include
"
nsIAccessibleEvent
.
idl
"
[
scriptable
builtinclass
uuid
(
9fb3a8a4
-
d254
-
43d3
-
80a5
-
20e171d52b21
)
]
interface
nsIAccessibleTableChangeEvent
:
nsIAccessibleEvent
{
readonly
attribute
long
rowOrColIndex
;
readonly
attribute
long
RowsOrColsCount
;
}
;
