#
include
"
nsIAccessibleEvent
.
idl
"
[
scriptable
builtinclass
uuid
(
ed1982e4
-
57d7
-
41a8
-
8cd8
-
9023f809383e
)
]
interface
nsIAccessibleCaretMoveEvent
:
nsIAccessibleEvent
{
readonly
attribute
long
caretOffset
;
readonly
attribute
bool
isSelectionCollapsed
;
readonly
attribute
bool
isAtEndOfLine
;
readonly
attribute
long
granularity
;
}
;
