#
include
"
nsISupports
.
idl
"
interface
nsIAccessible
;
interface
nsIWeakReference
;
interface
nsIAccessiblePivot
;
interface
nsIAccessibleTextLeafPoint
;
webidl
Node
;
[
scriptable
builtinclass
uuid
(
2188e3a0
-
c88e
-
11e7
-
8f1a
-
0800200c9a66
)
]
interface
nsIAccessibilityService
:
nsISupports
{
nsIAccessible
getApplicationAccessible
(
)
;
nsIAccessible
getAccessibleFor
(
in
Node
aNode
)
;
nsIAccessible
getAccessibleDescendantFor
(
in
Node
aNode
)
;
AString
getStringRole
(
in
unsigned
long
aRole
)
;
nsISupports
getStringStates
(
in
unsigned
long
aStates
in
unsigned
long
aExtraStates
)
;
AString
getStringEventType
(
in
unsigned
long
aEventType
)
;
AString
getStringRelationType
(
in
unsigned
long
aRelationType
)
;
nsIAccessible
getAccessibleFromCache
(
in
Node
aNode
)
;
void
setCacheDomains
(
in
unsigned
long
long
aCacheDomains
)
;
nsIAccessiblePivot
createAccessiblePivot
(
in
nsIAccessible
aRoot
)
;
nsIAccessibleTextLeafPoint
createTextLeafPoint
(
in
nsIAccessible
aAccessible
in
long
aOffset
)
;
void
setLogging
(
in
ACString
aModules
)
;
boolean
isLogged
(
in
AString
aModule
)
;
AString
getConsumers
(
)
;
}
;
