#
include
"
nsISupports
.
idl
"
#
include
"
nsIAccessibleHyperLink
.
idl
"
[
scriptable
builtinclass
uuid
(
b33684e2
-
090c
-
4e1d
-
a3d9
-
f4b46f4237b9
)
]
interface
nsIAccessibleHyperText
:
nsISupports
{
readonly
attribute
long
linkCount
;
nsIAccessibleHyperLink
getLinkAt
(
in
long
index
)
;
long
getLinkIndex
(
in
nsIAccessibleHyperLink
link
)
;
long
getLinkIndexAtOffset
(
in
long
offset
)
;
}
;
