#
include
"
nsISupports
.
idl
"
[
scriptable
builtinclass
uuid
(
79251626
-
387c
-
4531
-
89f3
-
680d31d6cf05
)
]
interface
nsIAccessibleApplication
:
nsISupports
{
readonly
attribute
AString
appName
;
readonly
attribute
AString
appVersion
;
readonly
attribute
AString
platformName
;
readonly
attribute
AString
platformVersion
;
}
;
