#
include
"
nsIAccessibleEvent
.
idl
"
[
scriptable
builtinclass
uuid
(
f75f0b32
-
5342
-
4d60
-
b1a5
-
b7bd6888eef5
)
]
interface
nsIAccessibleScrollingEvent
:
nsIAccessibleEvent
{
readonly
attribute
unsigned
long
scrollX
;
readonly
attribute
unsigned
long
scrollY
;
readonly
attribute
unsigned
long
maxScrollX
;
readonly
attribute
unsigned
long
maxScrollY
;
}
;
