#
include
"
nsIAccessibleEvent
.
idl
"
[
scriptable
builtinclass
uuid
(
a58693b1
-
009e
-
4cc9
-
ae93
-
9c7d8f85cfdf
)
]
interface
nsIAccessibleVirtualCursorChangeEvent
:
nsIAccessibleEvent
{
readonly
attribute
nsIAccessible
oldAccessible
;
readonly
attribute
nsIAccessible
newAccessible
;
readonly
attribute
short
reason
;
}
;
