#
include
"
nsIAccessibleEvent
.
idl
"
[
scriptable
builtinclass
uuid
(
2051709a
-
4e0d
-
4be5
-
873d
-
b49d1dee35fa
)
]
interface
nsIAccessibleHideEvent
:
nsIAccessibleEvent
{
readonly
attribute
nsIAccessible
targetParent
;
readonly
attribute
nsIAccessible
targetNextSibling
;
readonly
attribute
nsIAccessible
targetPrevSibling
;
}
;
