#
include
"
nsISupports
.
idl
"
interface
nsIAccessiblePivot
;
interface
mozIDOMWindowProxy
;
webidl
BrowsingContext
;
webidl
Document
;
[
scriptable
builtinclass
uuid
(
5cad5f91
-
fcce
-
40e7
-
913e
-
4671701d19b4
)
]
interface
nsIAccessibleDocument
:
nsISupports
{
readonly
attribute
AString
URL
;
readonly
attribute
AString
title
;
readonly
attribute
AString
mimeType
;
readonly
attribute
AString
docType
;
readonly
attribute
Document
DOMDocument
;
readonly
attribute
mozIDOMWindowProxy
window
;
readonly
attribute
nsIAccessibleDocument
parentDocument
;
readonly
attribute
unsigned
long
childDocumentCount
;
nsIAccessibleDocument
getChildDocumentAt
(
in
unsigned
long
index
)
;
readonly
attribute
BrowsingContext
browsingContext
;
}
;
