#
include
"
nsIAccessibleEvent
.
idl
"
[
scriptable
builtinclass
uuid
(
1fcc0dfa
-
93e6
-
48f4
-
bbd4
-
f80eb1d9f2e6
)
]
interface
nsIAccessibleTextChangeEvent
:
nsIAccessibleEvent
{
readonly
attribute
long
start
;
readonly
attribute
unsigned
long
length
;
readonly
attribute
boolean
isInserted
;
readonly
attribute
AString
modifiedText
;
}
;
