#
include
"
nsISupports
.
idl
"
[
scriptable
builtinclass
uuid
(
42a1e1dc
-
58cf
-
419d
-
bff0
-
ed3314c70016
)
]
interface
nsIAccessibleValue
:
nsISupports
{
readonly
attribute
double
maximumValue
;
readonly
attribute
double
minimumValue
;
attribute
double
currentValue
;
readonly
attribute
double
minimumIncrement
;
}
;
