#
include
"
nsISupports
.
idl
"
interface
nsIURI
;
interface
nsIAccessible
;
[
scriptable
builtinclass
uuid
(
883643d4
-
93a5
-
4f32
-
922c
-
6f06e01363c1
)
]
interface
nsIAccessibleHyperLink
:
nsISupports
{
readonly
attribute
long
startIndex
;
readonly
attribute
long
endIndex
;
readonly
attribute
boolean
valid
;
readonly
attribute
long
anchorCount
;
nsIURI
getURI
(
in
long
index
)
;
nsIAccessible
getAnchor
(
in
long
index
)
;
}
;
