#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
f1e0fbb7
-
fde4
-
4519
-
9383
-
2bcbee428513
)
]
interface
nsIAccessibleStates
:
nsISupports
{
const
unsigned
long
STATE_UNAVAILABLE
=
0x00000001
;
const
unsigned
long
STATE_SELECTED
=
0x00000002
;
const
unsigned
long
STATE_FOCUSED
=
0x00000004
;
const
unsigned
long
STATE_PRESSED
=
0x00000008
;
const
unsigned
long
STATE_CHECKED
=
0x00000010
;
const
unsigned
long
STATE_MIXED
=
0x00000020
;
const
unsigned
long
STATE_READONLY
=
0x00000040
;
const
unsigned
long
STATE_HOTTRACKED
=
0x00000080
;
const
unsigned
long
STATE_DEFAULT
=
0x00000100
;
const
unsigned
long
STATE_EXPANDED
=
0x00000200
;
const
unsigned
long
STATE_COLLAPSED
=
0x00000400
;
const
unsigned
long
STATE_BUSY
=
0x00000800
;
const
unsigned
long
STATE_FLOATING
=
0x00001000
;
const
unsigned
long
STATE_MARQUEED
=
0x00002000
;
const
unsigned
long
STATE_ANIMATED
=
0x00004000
;
const
unsigned
long
STATE_INVISIBLE
=
0x00008000
;
const
unsigned
long
STATE_OFFSCREEN
=
0x00010000
;
const
unsigned
long
STATE_SIZEABLE
=
0x00020000
;
const
unsigned
long
STATE_MOVEABLE
=
0x00040000
;
const
unsigned
long
STATE_SELFVOICING
=
0x00080000
;
const
unsigned
long
STATE_FOCUSABLE
=
0x00100000
;
const
unsigned
long
STATE_SELECTABLE
=
0x00200000
;
const
unsigned
long
STATE_LINKED
=
0x00400000
;
const
unsigned
long
STATE_TRAVERSED
=
0x00800000
;
const
unsigned
long
STATE_MULTISELECTABLE
=
0x01000000
;
const
unsigned
long
STATE_EXTSELECTABLE
=
0x02000000
;
const
unsigned
long
STATE_ALERT_LOW
=
0x04000000
;
const
unsigned
long
STATE_ALERT_MEDIUM
=
0x08000000
;
const
unsigned
long
STATE_ALERT_HIGH
=
0x10000000
;
const
unsigned
long
STATE_PROTECTED
=
0x20000000
;
const
unsigned
long
STATE_HASPOPUP
=
0x40000000
;
const
unsigned
long
STATE_REQUIRED
=
STATE_ALERT_LOW
;
const
unsigned
long
STATE_IMPORTANT
=
STATE_ALERT_MEDIUM
;
const
unsigned
long
STATE_INVALID
=
STATE_ALERT_HIGH
;
const
unsigned
long
STATE_CHECKABLE
=
STATE_MARQUEED
;
const
unsigned
long
EXT_STATE_SUPPORTS_AUTOCOMPLETION
=
0x00000001
;
const
unsigned
long
EXT_STATE_DEFUNCT
=
0x00000002
;
const
unsigned
long
EXT_STATE_SELECTABLE_TEXT
=
0x00000004
;
const
unsigned
long
EXT_STATE_EDITABLE
=
0x00000008
;
const
unsigned
long
EXT_STATE_ACTIVE
=
0x00000010
;
const
unsigned
long
EXT_STATE_MODAL
=
0x00000020
;
const
unsigned
long
EXT_STATE_MULTI_LINE
=
0x00000040
;
const
unsigned
long
EXT_STATE_HORIZONTAL
=
0x00000080
;
const
unsigned
long
EXT_STATE_OPAQUE
=
0x00000100
;
const
unsigned
long
EXT_STATE_SINGLE_LINE
=
0x00000200
;
const
unsigned
long
EXT_STATE_TRANSIENT
=
0x00000400
;
const
unsigned
long
EXT_STATE_VERTICAL
=
0x00000800
;
const
unsigned
long
EXT_STATE_STALE
=
0x00001000
;
const
unsigned
long
EXT_STATE_ENABLED
=
0x00002000
;
const
unsigned
long
EXT_STATE_SENSITIVE
=
0x00004000
;
const
unsigned
long
EXT_STATE_EXPANDABLE
=
0x00008000
;
const
unsigned
long
EXT_STATE_PINNED
=
0x00010000
;
const
unsigned
long
EXT_STATE_CURRENT
=
0x00020000
;
}
;
