#
include
"
nsIAccessibleEvent
.
idl
"
[
scriptable
builtinclass
uuid
(
ce41add2
-
096e
-
4606
-
b1ca
-
7408c6d5b4c3
)
]
interface
nsIAccessibleObjectAttributeChangedEvent
:
nsIAccessibleEvent
{
readonly
attribute
AString
changedAttribute
;
}
;
