#
include
"
nsISupports
.
idl
"
interface
nsIAccessible
;
interface
nsIAccessibleDocument
;
webidl
Node
;
%
{
C
+
+
#
define
NS_ACCESSIBLE_EVENT_TOPIC
"
accessible
-
event
"
%
}
[
scriptable
builtinclass
uuid
(
20c69a40
-
6c2c
-
42a3
-
a578
-
6f4473aab9dd
)
]
interface
nsIAccessibleEvent
:
nsISupports
{
const
unsigned
long
EVENT_SHOW
=
0x0001
;
const
unsigned
long
EVENT_HIDE
=
0x0002
;
const
unsigned
long
EVENT_REORDER
=
0x0003
;
const
unsigned
long
EVENT_FOCUS
=
0x0004
;
const
unsigned
long
EVENT_STATE_CHANGE
=
0x0005
;
const
unsigned
long
EVENT_NAME_CHANGE
=
0x0006
;
const
unsigned
long
EVENT_DESCRIPTION_CHANGE
=
0x0007
;
const
unsigned
long
EVENT_VALUE_CHANGE
=
0x0008
;
const
unsigned
long
EVENT_SELECTION
=
0x0009
;
const
unsigned
long
EVENT_SELECTION_ADD
=
0x000A
;
const
unsigned
long
EVENT_SELECTION_REMOVE
=
0x000B
;
const
unsigned
long
EVENT_SELECTION_WITHIN
=
0x000C
;
const
unsigned
long
EVENT_ALERT
=
0x000D
;
const
unsigned
long
EVENT_MENU_START
=
0x000E
;
const
unsigned
long
EVENT_MENU_END
=
0x000F
;
const
unsigned
long
EVENT_MENUPOPUP_START
=
0x0010
;
const
unsigned
long
EVENT_MENUPOPUP_END
=
0x0011
;
const
unsigned
long
EVENT_DRAGDROP_START
=
0x0012
;
const
unsigned
long
EVENT_SCROLLING_START
=
0x0013
;
const
unsigned
long
EVENT_SCROLLING_END
=
0x0014
;
const
unsigned
long
EVENT_DOCUMENT_LOAD_COMPLETE
=
0x0015
;
const
unsigned
long
EVENT_DOCUMENT_RELOAD
=
0x0016
;
const
unsigned
long
EVENT_DOCUMENT_LOAD_STOPPED
=
0x0017
;
const
unsigned
long
EVENT_TEXT_ATTRIBUTE_CHANGED
=
0x0018
;
const
unsigned
long
EVENT_TEXT_CARET_MOVED
=
0x0019
;
const
unsigned
long
EVENT_TEXT_INSERTED
=
0x001A
;
const
unsigned
long
EVENT_TEXT_REMOVED
=
0x001B
;
const
unsigned
long
EVENT_TEXT_SELECTION_CHANGED
=
0x001C
;
const
unsigned
long
EVENT_WINDOW_ACTIVATE
=
0x001D
;
const
unsigned
long
EVENT_WINDOW_DEACTIVATE
=
0x001E
;
const
unsigned
long
EVENT_WINDOW_MAXIMIZE
=
0x001F
;
const
unsigned
long
EVENT_WINDOW_MINIMIZE
=
0x0020
;
const
unsigned
long
EVENT_WINDOW_RESTORE
=
0x0021
;
const
unsigned
long
EVENT_OBJECT_ATTRIBUTE_CHANGED
=
0x0022
;
const
unsigned
long
EVENT_VIRTUALCURSOR_CHANGED
=
0x0023
;
const
unsigned
long
EVENT_TEXT_VALUE_CHANGE
=
0x0024
;
const
unsigned
long
EVENT_SCROLLING
=
0x0025
;
const
unsigned
long
EVENT_ANNOUNCEMENT
=
0x0026
;
const
unsigned
long
EVENT_LIVE_REGION_ADDED
=
0x0027
;
const
unsigned
long
EVENT_LIVE_REGION_REMOVED
=
0x0028
;
const
unsigned
long
EVENT_INNER_REORDER
=
0x0029
;
const
unsigned
long
EVENT_LAST_ENTRY
=
0x002A
;
readonly
attribute
unsigned
long
eventType
;
readonly
attribute
nsIAccessible
accessible
;
readonly
attribute
nsIAccessibleDocument
accessibleDocument
;
readonly
attribute
Node
DOMNode
;
readonly
attribute
boolean
isFromUserInput
;
}
;
