#
include
"
nsISupports
.
idl
"
interface
nsIAccessible
;
interface
nsIArray
;
[
scriptable
builtinclass
uuid
(
8efb03d4
-
1354
-
4875
-
94cf
-
261336057626
)
]
interface
nsIAccessibleSelectable
:
nsISupports
{
readonly
attribute
nsIArray
selectedItems
;
readonly
attribute
unsigned
long
selectedItemCount
;
nsIAccessible
getSelectedItemAt
(
in
unsigned
long
index
)
;
boolean
isItemSelected
(
in
unsigned
long
index
)
;
void
addItemToSelection
(
in
unsigned
long
index
)
;
void
removeItemFromSelection
(
in
unsigned
long
index
)
;
boolean
selectAll
(
)
;
void
unselectAll
(
)
;
}
;
