#
include
"
nsISupports
.
idl
"
interface
nsIAccessible
;
interface
nsIAccessibleDocument
;
webidl
Node
;
%
{
C
+
+
#
define
NS_ACCESSIBLE_EVENT_TOPIC
"
accessible
-
event
"
%
}
[
scriptable
builtinclass
uuid
(
20c69a40
-
6c2c
-
42a3
-
a578
-
6f4473aab9dd
)
]
interface
nsIAccessibleEvent
:
nsISupports
{
const
unsigned
long
EVENT_SHOW
=
0x0001
;
const
unsigned
long
EVENT_HIDE
=
0x0002
;
const
unsigned
long
EVENT_REORDER
=
0x0003
;
const
unsigned
long
EVENT_ACTIVE_DECENDENT_CHANGED
=
0x0004
;
const
unsigned
long
EVENT_FOCUS
=
0x0005
;
const
unsigned
long
EVENT_STATE_CHANGE
=
0x0006
;
const
unsigned
long
EVENT_LOCATION_CHANGE
=
0x0007
;
const
unsigned
long
EVENT_NAME_CHANGE
=
0x0008
;
const
unsigned
long
EVENT_DESCRIPTION_CHANGE
=
0x0009
;
const
unsigned
long
EVENT_VALUE_CHANGE
=
0x000A
;
const
unsigned
long
EVENT_HELP_CHANGE
=
0x000B
;
const
unsigned
long
EVENT_DEFACTION_CHANGE
=
0x000C
;
const
unsigned
long
EVENT_ACTION_CHANGE
=
0x000D
;
const
unsigned
long
EVENT_ACCELERATOR_CHANGE
=
0x000E
;
const
unsigned
long
EVENT_SELECTION
=
0x000F
;
const
unsigned
long
EVENT_SELECTION_ADD
=
0x0010
;
const
unsigned
long
EVENT_SELECTION_REMOVE
=
0x0011
;
const
unsigned
long
EVENT_SELECTION_WITHIN
=
0x0012
;
const
unsigned
long
EVENT_ALERT
=
0x0013
;
const
unsigned
long
EVENT_FOREGROUND
=
0x0014
;
const
unsigned
long
EVENT_MENU_START
=
0x0015
;
const
unsigned
long
EVENT_MENU_END
=
0x0016
;
const
unsigned
long
EVENT_MENUPOPUP_START
=
0x0017
;
const
unsigned
long
EVENT_MENUPOPUP_END
=
0x0018
;
const
unsigned
long
EVENT_CAPTURE_START
=
0x0019
;
const
unsigned
long
EVENT_CAPTURE_END
=
0x001A
;
const
unsigned
long
EVENT_MOVESIZE_START
=
0x001B
;
const
unsigned
long
EVENT_MOVESIZE_END
=
0x001C
;
const
unsigned
long
EVENT_CONTEXTHELP_START
=
0x001D
;
const
unsigned
long
EVENT_CONTEXTHELP_END
=
0x001E
;
const
unsigned
long
EVENT_DRAGDROP_START
=
0x001F
;
const
unsigned
long
EVENT_DRAGDROP_END
=
0x0020
;
const
unsigned
long
EVENT_DIALOG_START
=
0x0021
;
const
unsigned
long
EVENT_DIALOG_END
=
0x0022
;
const
unsigned
long
EVENT_SCROLLING_START
=
0x0023
;
const
unsigned
long
EVENT_SCROLLING_END
=
0x0024
;
const
unsigned
long
EVENT_MINIMIZE_START
=
0x0025
;
const
unsigned
long
EVENT_MINIMIZE_END
=
0x0026
;
const
unsigned
long
EVENT_DOCUMENT_LOAD_COMPLETE
=
0x0027
;
const
unsigned
long
EVENT_DOCUMENT_RELOAD
=
0x0028
;
const
unsigned
long
EVENT_DOCUMENT_LOAD_STOPPED
=
0x0029
;
const
unsigned
long
EVENT_DOCUMENT_ATTRIBUTES_CHANGED
=
0x002A
;
const
unsigned
long
EVENT_DOCUMENT_CONTENT_CHANGED
=
0x002B
;
const
unsigned
long
EVENT_PROPERTY_CHANGED
=
0x002C
;
const
unsigned
long
EVENT_PAGE_CHANGED
=
0x002D
;
const
unsigned
long
EVENT_TEXT_ATTRIBUTE_CHANGED
=
0x002E
;
const
unsigned
long
EVENT_TEXT_CARET_MOVED
=
0x002F
;
const
unsigned
long
EVENT_TEXT_CHANGED
=
0x0030
;
const
unsigned
long
EVENT_TEXT_INSERTED
=
0x0031
;
const
unsigned
long
EVENT_TEXT_REMOVED
=
0x0032
;
const
unsigned
long
EVENT_TEXT_UPDATED
=
0x0033
;
const
unsigned
long
EVENT_TEXT_SELECTION_CHANGED
=
0x0034
;
const
unsigned
long
EVENT_VISIBLE_DATA_CHANGED
=
0x0035
;
const
unsigned
long
EVENT_TEXT_COLUMN_CHANGED
=
0x0036
;
const
unsigned
long
EVENT_SECTION_CHANGED
=
0x0037
;
const
unsigned
long
EVENT_TABLE_CAPTION_CHANGED
=
0x0038
;
const
unsigned
long
EVENT_TABLE_MODEL_CHANGED
=
0x0039
;
const
unsigned
long
EVENT_TABLE_SUMMARY_CHANGED
=
0x003A
;
const
unsigned
long
EVENT_TABLE_ROW_DESCRIPTION_CHANGED
=
0x003B
;
const
unsigned
long
EVENT_TABLE_ROW_HEADER_CHANGED
=
0x003C
;
const
unsigned
long
EVENT_TABLE_ROW_INSERT
=
0x003D
;
const
unsigned
long
EVENT_TABLE_ROW_DELETE
=
0x003E
;
const
unsigned
long
EVENT_TABLE_ROW_REORDER
=
0x003F
;
const
unsigned
long
EVENT_TABLE_COLUMN_DESCRIPTION_CHANGED
=
0x0040
;
const
unsigned
long
EVENT_TABLE_COLUMN_HEADER_CHANGED
=
0x0041
;
const
unsigned
long
EVENT_TABLE_COLUMN_INSERT
=
0x0042
;
const
unsigned
long
EVENT_TABLE_COLUMN_DELETE
=
0x0043
;
const
unsigned
long
EVENT_TABLE_COLUMN_REORDER
=
0x0044
;
const
unsigned
long
EVENT_WINDOW_ACTIVATE
=
0x0045
;
const
unsigned
long
EVENT_WINDOW_CREATE
=
0x0046
;
const
unsigned
long
EVENT_WINDOW_DEACTIVATE
=
0x0047
;
const
unsigned
long
EVENT_WINDOW_DESTROY
=
0x0048
;
const
unsigned
long
EVENT_WINDOW_MAXIMIZE
=
0x0049
;
const
unsigned
long
EVENT_WINDOW_MINIMIZE
=
0x004A
;
const
unsigned
long
EVENT_WINDOW_RESIZE
=
0x004B
;
const
unsigned
long
EVENT_WINDOW_RESTORE
=
0x004C
;
const
unsigned
long
EVENT_HYPERLINK_END_INDEX_CHANGED
=
0x004D
;
const
unsigned
long
EVENT_HYPERLINK_NUMBER_OF_ANCHORS_CHANGED
=
0x004E
;
const
unsigned
long
EVENT_HYPERLINK_SELECTED_LINK_CHANGED
=
0x004F
;
const
unsigned
long
EVENT_HYPERTEXT_LINK_ACTIVATED
=
0x0050
;
const
unsigned
long
EVENT_HYPERTEXT_LINK_SELECTED
=
0x0051
;
const
unsigned
long
EVENT_HYPERLINK_START_INDEX_CHANGED
=
0x0052
;
const
unsigned
long
EVENT_HYPERTEXT_CHANGED
=
0x0053
;
const
unsigned
long
EVENT_HYPERTEXT_NLINKS_CHANGED
=
0x0054
;
const
unsigned
long
EVENT_OBJECT_ATTRIBUTE_CHANGED
=
0x0055
;
const
unsigned
long
EVENT_VIRTUALCURSOR_CHANGED
=
0x0056
;
const
unsigned
long
EVENT_TEXT_VALUE_CHANGE
=
0x0057
;
const
unsigned
long
EVENT_SCROLLING
=
0x0058
;
const
unsigned
long
EVENT_ANNOUNCEMENT
=
0x0059
;
const
unsigned
long
EVENT_LIVE_REGION_ADDED
=
0x005A
;
const
unsigned
long
EVENT_LIVE_REGION_REMOVED
=
0x005B
;
const
unsigned
long
EVENT_INNER_REORDER
=
0x005C
;
const
unsigned
long
EVENT_LAST_ENTRY
=
0x005D
;
readonly
attribute
unsigned
long
eventType
;
readonly
attribute
nsIAccessible
accessible
;
readonly
attribute
nsIAccessibleDocument
accessibleDocument
;
readonly
attribute
Node
DOMNode
;
readonly
attribute
boolean
isFromUserInput
;
}
;
