#
include
"
nsISupports
.
idl
"
[
scriptable
builtinclass
uuid
(
ad7f32a5
-
6d5f
-
4154
-
a5b8
-
0fa7aed48936
)
]
interface
nsIAccessibleRole
:
nsISupports
{
const
unsigned
long
ROLE_NOTHING
=
0
;
const
unsigned
long
ROLE_TITLEBAR
=
1
;
const
unsigned
long
ROLE_MENUBAR
=
2
;
const
unsigned
long
ROLE_SCROLLBAR
=
3
;
const
unsigned
long
ROLE_GRIP
=
4
;
const
unsigned
long
ROLE_SOUND
=
5
;
const
unsigned
long
ROLE_CURSOR
=
6
;
const
unsigned
long
ROLE_CARET
=
7
;
const
unsigned
long
ROLE_ALERT
=
8
;
const
unsigned
long
ROLE_WINDOW
=
9
;
const
unsigned
long
ROLE_INTERNAL_FRAME
=
10
;
const
unsigned
long
ROLE_MENUPOPUP
=
11
;
const
unsigned
long
ROLE_MENUITEM
=
12
;
const
unsigned
long
ROLE_TOOLTIP
=
13
;
const
unsigned
long
ROLE_APPLICATION
=
14
;
const
unsigned
long
ROLE_DOCUMENT
=
15
;
const
unsigned
long
ROLE_PANE
=
16
;
const
unsigned
long
ROLE_CHART
=
17
;
const
unsigned
long
ROLE_DIALOG
=
18
;
const
unsigned
long
ROLE_BORDER
=
19
;
const
unsigned
long
ROLE_GROUPING
=
20
;
const
unsigned
long
ROLE_SEPARATOR
=
21
;
const
unsigned
long
ROLE_TOOLBAR
=
22
;
const
unsigned
long
ROLE_STATUSBAR
=
23
;
const
unsigned
long
ROLE_TABLE
=
24
;
const
unsigned
long
ROLE_COLUMNHEADER
=
25
;
const
unsigned
long
ROLE_ROWHEADER
=
26
;
const
unsigned
long
ROLE_COLUMN
=
27
;
const
unsigned
long
ROLE_ROW
=
28
;
const
unsigned
long
ROLE_CELL
=
29
;
const
unsigned
long
ROLE_LINK
=
30
;
const
unsigned
long
ROLE_HELPBALLOON
=
31
;
const
unsigned
long
ROLE_CHARACTER
=
32
;
const
unsigned
long
ROLE_LIST
=
33
;
const
unsigned
long
ROLE_LISTITEM
=
34
;
const
unsigned
long
ROLE_OUTLINE
=
35
;
const
unsigned
long
ROLE_OUTLINEITEM
=
36
;
const
unsigned
long
ROLE_PAGETAB
=
37
;
const
unsigned
long
ROLE_PROPERTYPAGE
=
38
;
const
unsigned
long
ROLE_INDICATOR
=
39
;
const
unsigned
long
ROLE_GRAPHIC
=
40
;
const
unsigned
long
ROLE_STATICTEXT
=
41
;
const
unsigned
long
ROLE_TEXT_LEAF
=
42
;
const
unsigned
long
ROLE_PUSHBUTTON
=
43
;
const
unsigned
long
ROLE_CHECKBUTTON
=
44
;
const
unsigned
long
ROLE_RADIOBUTTON
=
45
;
const
unsigned
long
ROLE_COMBOBOX
=
46
;
const
unsigned
long
ROLE_DROPLIST
=
47
;
const
unsigned
long
ROLE_PROGRESSBAR
=
48
;
const
unsigned
long
ROLE_DIAL
=
49
;
const
unsigned
long
ROLE_HOTKEYFIELD
=
50
;
const
unsigned
long
ROLE_SLIDER
=
51
;
const
unsigned
long
ROLE_SPINBUTTON
=
52
;
const
unsigned
long
ROLE_DIAGRAM
=
53
;
const
unsigned
long
ROLE_ANIMATION
=
54
;
const
unsigned
long
ROLE_EQUATION
=
55
;
const
unsigned
long
ROLE_BUTTONDROPDOWN
=
56
;
const
unsigned
long
ROLE_BUTTONMENU
=
57
;
const
unsigned
long
ROLE_BUTTONDROPDOWNGRID
=
58
;
const
unsigned
long
ROLE_WHITESPACE
=
59
;
const
unsigned
long
ROLE_PAGETABLIST
=
60
;
const
unsigned
long
ROLE_CLOCK
=
61
;
const
unsigned
long
ROLE_SPLITBUTTON
=
62
;
const
unsigned
long
ROLE_IPADDRESS
=
63
;
const
unsigned
long
ROLE_ACCEL_LABEL
=
64
;
const
unsigned
long
ROLE_ARROW
=
65
;
const
unsigned
long
ROLE_CANVAS
=
66
;
const
unsigned
long
ROLE_CHECK_MENU_ITEM
=
67
;
const
unsigned
long
ROLE_COLOR_CHOOSER
=
68
;
const
unsigned
long
ROLE_DATE_EDITOR
=
69
;
const
unsigned
long
ROLE_DESKTOP_ICON
=
70
;
const
unsigned
long
ROLE_DESKTOP_FRAME
=
71
;
const
unsigned
long
ROLE_DIRECTORY_PANE
=
72
;
const
unsigned
long
ROLE_FILE_CHOOSER
=
73
;
const
unsigned
long
ROLE_FONT_CHOOSER
=
74
;
const
unsigned
long
ROLE_CHROME_WINDOW
=
75
;
const
unsigned
long
ROLE_GLASS_PANE
=
76
;
const
unsigned
long
ROLE_HTML_CONTAINER
=
77
;
const
unsigned
long
ROLE_ICON
=
78
;
const
unsigned
long
ROLE_LABEL
=
79
;
const
unsigned
long
ROLE_LAYERED_PANE
=
80
;
const
unsigned
long
ROLE_OPTION_PANE
=
81
;
const
unsigned
long
ROLE_PASSWORD_TEXT
=
82
;
const
unsigned
long
ROLE_POPUP_MENU
=
83
;
const
unsigned
long
ROLE_RADIO_MENU_ITEM
=
84
;
const
unsigned
long
ROLE_ROOT_PANE
=
85
;
const
unsigned
long
ROLE_SCROLL_PANE
=
86
;
const
unsigned
long
ROLE_SPLIT_PANE
=
87
;
const
unsigned
long
ROLE_TABLE_COLUMN_HEADER
=
88
;
const
unsigned
long
ROLE_TABLE_ROW_HEADER
=
89
;
const
unsigned
long
ROLE_TEAR_OFF_MENU_ITEM
=
90
;
const
unsigned
long
ROLE_TERMINAL
=
91
;
const
unsigned
long
ROLE_TEXT_CONTAINER
=
92
;
const
unsigned
long
ROLE_TOGGLE_BUTTON
=
93
;
const
unsigned
long
ROLE_TREE_TABLE
=
94
;
const
unsigned
long
ROLE_VIEWPORT
=
95
;
const
unsigned
long
ROLE_HEADER
=
96
;
const
unsigned
long
ROLE_FOOTER
=
97
;
const
unsigned
long
ROLE_PARAGRAPH
=
98
;
const
unsigned
long
ROLE_RULER
=
99
;
const
unsigned
long
ROLE_AUTOCOMPLETE
=
100
;
const
unsigned
long
ROLE_EDITBAR
=
101
;
const
unsigned
long
ROLE_ENTRY
=
102
;
const
unsigned
long
ROLE_CAPTION
=
103
;
const
unsigned
long
ROLE_NON_NATIVE_DOCUMENT
=
104
;
const
unsigned
long
ROLE_HEADING
=
105
;
const
unsigned
long
ROLE_PAGE
=
106
;
const
unsigned
long
ROLE_SECTION
=
107
;
const
unsigned
long
ROLE_REDUNDANT_OBJECT
=
108
;
const
unsigned
long
ROLE_FORM
=
109
;
const
unsigned
long
ROLE_IME
=
110
;
const
unsigned
long
ROLE_APP_ROOT
=
111
;
const
unsigned
long
ROLE_PARENT_MENUITEM
=
112
;
const
unsigned
long
ROLE_CALENDAR
=
113
;
const
unsigned
long
ROLE_COMBOBOX_LIST
=
114
;
const
unsigned
long
ROLE_COMBOBOX_OPTION
=
115
;
const
unsigned
long
ROLE_IMAGE_MAP
=
116
;
const
unsigned
long
ROLE_OPTION
=
117
;
const
unsigned
long
ROLE_RICH_OPTION
=
118
;
const
unsigned
long
ROLE_LISTBOX
=
119
;
const
unsigned
long
ROLE_FLAT_EQUATION
=
120
;
const
unsigned
long
ROLE_GRID_CELL
=
121
;
const
unsigned
long
ROLE_EMBEDDED_OBJECT
=
122
;
const
unsigned
long
ROLE_NOTE
=
123
;
const
unsigned
long
ROLE_FIGURE
=
124
;
const
unsigned
long
ROLE_CHECK_RICH_OPTION
=
125
;
const
unsigned
long
ROLE_DEFINITION_LIST
=
126
;
const
unsigned
long
ROLE_TERM
=
127
;
const
unsigned
long
ROLE_DEFINITION
=
128
;
const
unsigned
long
ROLE_KEY
=
129
;
const
unsigned
long
ROLE_SWITCH
=
130
;
const
unsigned
long
ROLE_MATHML_MATH
=
131
;
const
unsigned
long
ROLE_MATHML_IDENTIFIER
=
132
;
const
unsigned
long
ROLE_MATHML_NUMBER
=
133
;
const
unsigned
long
ROLE_MATHML_OPERATOR
=
134
;
const
unsigned
long
ROLE_MATHML_TEXT
=
135
;
const
unsigned
long
ROLE_MATHML_STRING_LITERAL
=
136
;
const
unsigned
long
ROLE_MATHML_GLYPH
=
137
;
const
unsigned
long
ROLE_MATHML_ROW
=
138
;
const
unsigned
long
ROLE_MATHML_FRACTION
=
139
;
const
unsigned
long
ROLE_MATHML_SQUARE_ROOT
=
140
;
const
unsigned
long
ROLE_MATHML_ROOT
=
141
;
const
unsigned
long
ROLE_MATHML_FENCED
=
142
;
const
unsigned
long
ROLE_MATHML_ENCLOSED
=
143
;
const
unsigned
long
ROLE_MATHML_STYLE
=
144
;
const
unsigned
long
ROLE_MATHML_SUB
=
145
;
const
unsigned
long
ROLE_MATHML_SUP
=
146
;
const
unsigned
long
ROLE_MATHML_SUB_SUP
=
147
;
const
unsigned
long
ROLE_MATHML_UNDER
=
148
;
const
unsigned
long
ROLE_MATHML_OVER
=
149
;
const
unsigned
long
ROLE_MATHML_UNDER_OVER
=
150
;
const
unsigned
long
ROLE_MATHML_MULTISCRIPTS
=
151
;
const
unsigned
long
ROLE_MATHML_TABLE
=
152
;
const
unsigned
long
ROLE_MATHML_LABELED_ROW
=
153
;
const
unsigned
long
ROLE_MATHML_TABLE_ROW
=
154
;
const
unsigned
long
ROLE_MATHML_CELL
=
155
;
const
unsigned
long
ROLE_MATHML_ACTION
=
156
;
const
unsigned
long
ROLE_MATHML_ERROR
=
157
;
const
unsigned
long
ROLE_MATHML_STACK
=
158
;
const
unsigned
long
ROLE_MATHML_LONG_DIVISION
=
159
;
const
unsigned
long
ROLE_MATHML_STACK_GROUP
=
160
;
const
unsigned
long
ROLE_MATHML_STACK_ROW
=
161
;
const
unsigned
long
ROLE_MATHML_STACK_CARRIES
=
162
;
const
unsigned
long
ROLE_MATHML_STACK_CARRY
=
163
;
const
unsigned
long
ROLE_MATHML_STACK_LINE
=
164
;
const
unsigned
long
ROLE_RADIO_GROUP
=
165
;
const
unsigned
long
ROLE_TEXT
=
166
;
const
unsigned
long
ROLE_DETAILS
=
167
;
const
unsigned
long
ROLE_SUMMARY
=
168
;
const
unsigned
long
ROLE_LANDMARK
=
169
;
const
unsigned
long
ROLE_NAVIGATION
=
170
;
const
unsigned
long
ROLE_FOOTNOTE
=
171
;
const
unsigned
long
ROLE_ARTICLE
=
172
;
const
unsigned
long
ROLE_REGION
=
173
;
const
unsigned
long
ROLE_EDITCOMBOBOX
=
174
;
const
unsigned
long
ROLE_BLOCKQUOTE
=
175
;
const
unsigned
long
ROLE_CONTENT_DELETION
=
176
;
const
unsigned
long
ROLE_CONTENT_INSERTION
=
177
;
const
unsigned
long
ROLE_FORM_LANDMARK
=
178
;
const
unsigned
long
ROLE_MARK
=
179
;
const
unsigned
long
ROLE_SUGGESTION
=
180
;
const
unsigned
long
ROLE_COMMENT
=
181
;
const
unsigned
long
ROLE_CODE
=
182
;
const
unsigned
long
ROLE_TIME_EDITOR
=
183
;
}
;
