#
include
"
nsISupports
.
idl
"
interface
nsIInputStream
;
%
{
C
+
+
#
define
NS_ISCRIPTABLEUNICODECONVERTER_CID
{
0x0A698C44
0x3BFF
0x11d4
{
0x96
0x49
0x00
0xC0
0xCA
0x13
0x5B
0x4E
}
}
#
define
NS_ISCRIPTABLEUNICODECONVERTER_CONTRACTID
"
mozilla
.
org
/
intl
/
scriptableunicodeconverter
"
%
}
[
scriptable
uuid
(
f36ee324
-
5c1c
-
437f
-
ba10
-
2b4db7a18031
)
]
interface
nsIScriptableUnicodeConverter
:
nsISupports
{
ACString
ConvertFromUnicode
(
in
AString
aSrc
)
;
ACString
Finish
(
)
;
AString
ConvertToUnicode
(
in
ACString
aSrc
)
;
attribute
ACString
charset
;
attribute
boolean
isInternal
;
}
;
