#
include
"
nsISupports
.
idl
"
interface
nsIInputStream
;
[
scriptable
uuid
(
f36ee324
-
5c1c
-
437f
-
ba10
-
2b4db7a18031
)
]
interface
nsIScriptableUnicodeConverter
:
nsISupports
{
ACString
ConvertFromUnicode
(
in
AString
aSrc
)
;
ACString
Finish
(
)
;
AString
ConvertToUnicode
(
in
ACString
aSrc
)
;
attribute
ACString
charset
;
attribute
boolean
isInternal
;
}
;
