#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
a76599ef
-
78a4
-
441f
-
b258
-
4908dedef42d
)
]
interface
nsITerminatorTest
:
nsISupports
{
[
implicit_jscontext
]
jsval
getTicksForShutdownPhases
(
)
;
}
;
