#
include
"
nsISupports
.
idl
"
#
include
"
nsIURI
.
idl
"
#
include
"
nsIPrincipal
.
idl
"
interface
WebTransportSessionEventListener
;
interface
nsIWebTransportStreamCallback
;
%
{
C
+
+
namespace
mozilla
:
:
net
{
class
Http3WebTransportSession
;
}
%
}
[
ptr
]
native
Http3WebTransportSessionPtr
(
mozilla
:
:
net
:
:
Http3WebTransportSession
)
;
[
builtinclass
scriptable
uuid
(
c20d6e77
-
8cb1
-
4838
-
a88d
-
fff826080aa3
)
]
interface
nsIWebTransport
:
nsISupports
{
void
asyncConnect
(
in
nsIURI
aURI
in
nsIPrincipal
aLoadingPrincipal
in
unsigned
long
aSecurityFlags
in
WebTransportSessionEventListener
aListener
)
;
void
getStats
(
)
;
void
closeSession
(
in
uint32_t
aErrorCode
in
ACString
aReason
)
;
void
createOutgoingBidirectionalStream
(
in
nsIWebTransportStreamCallback
aListener
)
;
void
createOutgoingUnidirectionalStream
(
in
nsIWebTransportStreamCallback
aListener
)
;
}
;
[
scriptable
uuid
(
0e3cb269
-
f318
-
43c8
-
959e
-
897f57894b71
)
]
interface
WebTransportSessionEventListener
:
nsISupports
{
void
onSessionReady
(
in
uint64_t
aSessionId
)
;
void
onSessionReadyInternal
(
in
Http3WebTransportSessionPtr
aSession
)
;
void
onSessionClosed
(
in
uint32_t
aErrorCode
in
ACString
aReason
)
;
}
;
[
scriptable
uuid
(
c6eeff1d
-
599b
-
40a8
-
9157
-
c7a40c3d51a2
)
]
interface
nsIWebTransportStreamCallback
:
nsISupports
{
void
onError
(
in
uint8_t
aError
)
;
}
;
