#
include
"
nsISupports
.
idl
"
[
builtinclass
scriptable
uuid
(
d461b235
-
6291
-
4817
-
adcc
-
a2a3b3dfc10b
)
]
interface
nsIWebTransportReceiveStream
:
nsISupports
{
void
sendStopSending
(
in
uint8_t
aError
)
;
}
;
[
builtinclass
scriptable
uuid
(
804f245c
-
52ea
-
403c
-
8a78
-
f751533bdd70
)
]
interface
nsIWebTransportSendStream
:
nsISupports
{
void
sendFin
(
)
;
void
reset
(
in
uint8_t
aErrorCode
)
;
}
;
[
builtinclass
scriptable
uuid
(
f9ecb509
-
36db
-
4689
-
97d6
-
137639a08750
)
]
interface
nsIWebTransportBidirectionalStream
:
nsISupports
{
void
sendStopSending
(
in
uint8_t
aError
)
;
void
sendFin
(
)
;
void
reset
(
in
uint8_t
aErrorCode
)
;
}
;
