#
include
"
nsISupports
.
idl
"
interface
nsIURI
;
interface
nsIPrincipal
;
interface
nsIObserver
;
[
scriptable
builtinclass
uuid
(
19533e7b
-
f321
-
4ef1
-
bc59
-
6e812dc2a733
)
]
interface
mozIJSSubScriptLoader
:
nsISupports
{
[
implicit_jscontext
]
jsval
loadSubScript
(
in
AString
url
[
optional
]
in
jsval
obj
)
;
[
implicit_jscontext
]
jsval
loadSubScriptWithOptions
(
in
AString
url
in
jsval
options
)
;
}
;
