#
include
"
nsIChannel
.
idl
"
[
uuid
(
3e9800f8
-
edb7
-
4c9a
-
9285
-
09b4f045b019
)
]
interface
nsIViewSourceChannel
:
nsIChannel
{
[
must_use
]
attribute
ACString
originalContentType
;
[
must_use
]
readonly
attribute
boolean
isSrcdocChannel
;
[
must_use
]
attribute
nsIURI
baseURI
;
attribute
boolean
replaceRequest
;
}
;
