#
include
"
nsISupports
.
idl
"
#
include
"
domstubs
.
idl
"
webidl
CharacterData
;
webidl
Node
;
webidl
Selection
;
[
scriptable
uuid
(
b22907b1
-
ee93
-
11d2
-
8d50
-
000064657374
)
]
interface
nsIEditActionListener
:
nsISupports
{
void
DidCreateNode
(
in
AString
aTag
in
Node
aNewNode
in
nsresult
aResult
)
;
void
DidInsertNode
(
in
Node
aNode
in
nsresult
aResult
)
;
void
DidDeleteNode
(
in
Node
aChild
in
nsresult
aResult
)
;
void
DidSplitNode
(
in
Node
aExistingRightNode
in
Node
aNewLeftNode
)
;
void
DidJoinNodes
(
in
Node
aLeftNode
in
Node
aRightNode
in
Node
aParent
in
nsresult
aResult
)
;
void
DidInsertText
(
in
CharacterData
aTextNode
in
long
aOffset
in
AString
aString
in
nsresult
aResult
)
;
void
WillDeleteText
(
in
CharacterData
aTextNode
in
long
aOffset
in
long
aLength
)
;
void
WillDeleteSelection
(
in
Selection
aSelection
)
;
void
DidDeleteSelection
(
in
Selection
aSelection
)
;
}
;
