#
include
"
nsISupports
.
idl
"
interface
nsIArray
;
webidl
Node
;
[
scriptable
builtinclass
uuid
(
fdf23301
-
4a94
-
11d3
-
9ce4
-
9960496c41bc
)
]
interface
nsIEditorMailSupport
:
nsISupports
{
[
can_run_script
]
Node
insertAsCitedQuotation
(
in
AString
aQuotedText
in
AString
aCitation
in
boolean
aInsertHTML
)
;
[
can_run_script
]
void
rewrap
(
in
boolean
aRespectNewlines
)
;
[
can_run_script
]
void
insertTextWithQuotations
(
in
AString
aStringToInsert
)
;
[
setter_can_run_script
]
attribute
long
wrapWidth
;
}
;
