#
include
"
nsISupports
.
idl
"
#
include
"
domstubs
.
idl
"
webidl
CharacterData
;
webidl
Node
;
webidl
Range
;
%
{
C
+
+
#
include
"
mozilla
/
EditorDOMPoint
.
h
"
class
nsINode
;
class
nsIContent
;
%
}
[
ref
]
native
EditorRawDOMPointRef
(
mozilla
:
:
EditorDOMPointBase
<
nsINode
*
nsIContent
*
>
)
;
[
scriptable
uuid
(
b22907b1
-
ee93
-
11d2
-
8d50
-
000064657374
)
]
interface
nsIEditActionListener
:
nsISupports
{
void
DidDeleteNode
(
in
Node
aChild
in
nsresult
aResult
)
;
[
noscript
]
void
DidJoinContents
(
[
const
]
in
EditorRawDOMPointRef
aJoinedPoint
[
const
]
in
Node
aRemovedNode
)
;
void
DidInsertText
(
in
CharacterData
aTextNode
in
long
aOffset
in
AString
aString
in
nsresult
aResult
)
;
void
WillDeleteText
(
in
CharacterData
aTextNode
in
long
aOffset
in
long
aLength
)
;
void
WillDeleteRanges
(
in
Array
<
Range
>
aRangesToDelete
)
;
}
;
