#
include
"
nsISupports
.
idl
"
#
include
"
domstubs
.
idl
"
[
scriptable
builtinclass
uuid
(
91375f52
-
20e6
-
4757
-
9835
-
eb04fabe5498
)
]
interface
nsIHTMLAbsPosEditor
:
nsISupports
{
[
setter_can_run_script
]
attribute
boolean
absolutePositioningEnabled
;
attribute
boolean
snapToGridEnabled
;
attribute
unsigned
long
gridSize
;
}
;
