#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
12f7d302
-
5368
-
412d
-
bdc9
-
26d151518e6c
)
]
interface
nsIRddProcessTest
:
nsISupports
{
[
implicit_jscontext
]
Promise
testTelemetryProbes
(
)
;
void
stopProcess
(
)
;
}
;
