#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
98d0e975
-
9cad
-
4ce3
-
ae2f
-
f878b8be6307
)
]
interface
nsIFOG
:
nsISupports
{
void
initializeFOG
(
)
;
void
setLogPings
(
in
boolean
aEnableLogPings
)
;
void
setTagPings
(
in
ACString
aDebugTag
)
;
void
sendPing
(
in
ACString
aPingName
)
;
}
;
