#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
98d0e975
-
9cad
-
4ce3
-
ae2f
-
f878b8be6307
)
]
interface
nsIFOG
:
nsISupports
{
void
initializeFOG
(
[
optional
]
in
AUTF8String
aDataPathOverride
[
optional
]
in
AUTF8String
aAppIdOverride
)
;
void
registerCustomPings
(
)
;
void
setLogPings
(
in
boolean
aEnableLogPings
)
;
void
setTagPings
(
in
ACString
aDebugTag
)
;
void
sendPing
(
in
ACString
aPingName
)
;
[
implicit_jscontext
]
void
setExperimentActive
(
in
ACString
aExperimentId
in
ACString
aBranch
[
optional
]
in
jsval
aExtra
)
;
void
setExperimentInactive
(
in
ACString
aExperimentId
)
;
[
implicit_jscontext
]
jsval
testGetExperimentData
(
in
ACString
aExperimentId
)
;
[
implicit_jscontext
]
Promise
testFlushAllChildren
(
)
;
void
testResetFOG
(
[
optional
]
in
AUTF8String
aDataPathOverride
[
optional
]
in
AUTF8String
aAppIdOverride
)
;
[
implicit_jscontext
]
Promise
testTriggerMetrics
(
in
unsigned
long
aProcessType
)
;
uint32_t
testRegisterRuntimeMetric
(
in
ACString
aType
in
ACString
aCategory
in
ACString
aName
in
Array
<
ACString
>
aPings
in
ACString
aLifetime
in
boolean
aDisabled
[
optional
]
in
ACString
aExtraArgs
)
;
}
;
