#
include
"
nsISupports
.
idl
"
[
scriptable
function
uuid
(
e5447f62
-
4b03
-
497c
-
81e9
-
6ab683d20380
)
]
interface
nsIGleanPingTestCallback
:
nsISupports
{
void
call
(
in
ACString
aReason
)
;
}
;
[
scriptable
uuid
(
5223a48b
-
687d
-
47ff
-
a629
-
fd4a72d1ecfa
)
]
interface
nsIGleanPing
:
nsISupports
{
void
submit
(
[
optional
]
in
ACString
aReason
)
;
void
testBeforeNextSubmit
(
in
nsIGleanPingTestCallback
aCallback
)
;
}
;
