#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
d3180fe0
-
19fa
-
11eb
-
8b6f
-
0800200c9a66
)
]
interface
nsIGleanBoolean
:
nsISupports
{
void
set
(
in
bool
value
)
;
jsval
testGetValue
(
in
AUTF8String
aStorageName
)
;
}
;
[
scriptable
uuid
(
aa15fd20
-
1e8a
-
11eb
-
9bec
-
0800200c9a66
)
]
interface
nsIGleanDatetime
:
nsISupports
{
[
optional_argc
]
void
set
(
[
optional
]
in
PRTime
aValue
)
;
[
implicit_jscontext
]
jsval
testGetValue
(
in
AUTF8String
aStorageName
)
;
}
;
[
scriptable
uuid
(
05b89d2a
-
d57c
-
11ea
-
82da
-
3f63399a6f5a
)
]
interface
nsIGleanCounter
:
nsISupports
{
void
add
(
in
uint32_t
amount
)
;
jsval
testGetValue
(
in
AUTF8String
aStorageName
)
;
}
;
[
scriptable
uuid
(
d84a3555
-
46f1
-
48c1
-
9122
-
e8e88b069d2b
)
]
interface
nsIGleanString
:
nsISupports
{
void
set
(
in
AUTF8String
value
)
;
[
implicit_jscontext
]
jsval
testGetValue
(
in
AUTF8String
aStorageName
)
;
}
;
[
scriptable
uuid
(
2586530c
-
030f
-
11eb
-
93cb
-
cbf30d25225a
)
]
interface
nsIGleanTimespan
:
nsISupports
{
void
start
(
)
;
void
stop
(
)
;
jsval
testGetValue
(
in
AUTF8String
aStorageName
)
;
}
;
[
scriptable
uuid
(
395700e7
-
06f6
-
46be
-
adcc
-
ea58977fda6d
)
]
interface
nsIGleanUuid
:
nsISupports
{
void
set
(
in
AUTF8String
aValue
)
;
void
generateAndSet
(
)
;
[
implicit_jscontext
]
jsval
testGetValue
(
in
AUTF8String
aStorageName
)
;
}
;
[
scriptable
uuid
(
1b01424a
-
1f55
-
11eb
-
92a5
-
0754f6c3f240
)
]
interface
nsIGleanEvent
:
nsISupports
{
[
implicit_jscontext
]
void
record
(
[
optional
]
in
jsval
aExtra
)
;
[
implicit_jscontext
]
jsval
testGetValue
(
in
AUTF8String
aStorageName
)
;
}
;
