#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
d3180fe0
-
19fa
-
11eb
-
8b6f
-
0800200c9a66
)
]
interface
nsIGleanBoolean
:
nsISupports
{
[
implicit_jscontext
]
void
set
(
in
bool
value
)
;
[
implicit_jscontext
]
bool
testHasValue
(
in
ACString
aStorageName
)
;
[
implicit_jscontext
]
bool
testGetValue
(
in
ACString
aStorageName
)
;
}
;
[
scriptable
uuid
(
05b89d2a
-
d57c
-
11ea
-
82da
-
3f63399a6f5a
)
]
interface
nsIGleanCounter
:
nsISupports
{
[
implicit_jscontext
]
void
add
(
in
uint32_t
amount
)
;
[
implicit_jscontext
]
bool
testHasValue
(
in
ACString
aStorageName
)
;
[
implicit_jscontext
]
long
testGetValue
(
in
ACString
aStorageName
)
;
}
;
[
scriptable
uuid
(
2586530c
-
030f
-
11eb
-
93cb
-
cbf30d25225a
)
]
interface
nsIGleanTimespan
:
nsISupports
{
[
implicit_jscontext
]
void
start
(
)
;
[
implicit_jscontext
]
void
stop
(
)
;
[
implicit_jscontext
]
bool
testHasValue
(
in
ACString
aStorageName
)
;
[
implicit_jscontext
]
long
long
testGetValue
(
in
ACString
aStorageName
)
;
}
;
