#
include
"
nsIProtocolHandler
.
idl
"
interface
nsIFile
;
interface
nsIURIMutator
;
[
scriptable
uuid
(
1fb25bd5
-
4354
-
4dcd
-
8d97
-
621b7b3ed2e4
)
]
interface
nsIFileProtocolHandler
:
nsIProtocolHandler
{
nsIURI
newFileURI
(
in
nsIFile
aFile
)
;
nsIURIMutator
newFileURIMutator
(
in
nsIFile
file
)
;
AUTF8String
getURLSpecFromFile
(
in
nsIFile
file
)
;
AUTF8String
getURLSpecFromActualFile
(
in
nsIFile
file
)
;
AUTF8String
getURLSpecFromDir
(
in
nsIFile
file
)
;
nsIFile
getFileFromURLSpec
(
in
AUTF8String
url
)
;
nsIURI
readURLFile
(
in
nsIFile
file
)
;
nsIURI
readShellLink
(
in
nsIFile
file
)
;
}
;
