#
include
"
nsISupports
.
idl
"
interface
nsIMutableArray
;
[
scriptable
uuid
(
f76c0901
-
437a
-
11d3
-
b7a0
-
e35db351b4bc
)
]
interface
nsIDialogParamBlock
:
nsISupports
{
int32_t
GetInt
(
in
int32_t
inIndex
)
;
void
SetInt
(
in
int32_t
inIndex
in
int32_t
inInt
)
;
void
SetNumberStrings
(
in
int32_t
inNumStrings
)
;
wstring
GetString
(
in
int32_t
inIndex
)
;
void
SetString
(
in
int32_t
inIndex
in
wstring
inString
)
;
attribute
nsIMutableArray
objects
;
}
;
%
{
C
+
+
#
define
NS_DIALOGPARAMBLOCK_CONTRACTID
"
mozilla
.
org
/
embedcomp
/
dialogparam
;
1
"
%
}
