#
include
"
nsISupports
.
idl
"
webidl
BrowsingContext
;
%
{
C
+
+
namespace
mozilla
{
class
OriginAttributes
;
namespace
dom
{
class
BrowserParent
;
}
}
%
}
[
ref
]
native
const_OriginAttributes
(
const
mozilla
:
:
OriginAttributes
)
;
[
ptr
]
native
BrowserParent
(
mozilla
:
:
dom
:
:
BrowserParent
)
;
[
uuid
(
0524ee06
-
7f4c
-
4cd3
-
ab80
-
084562745cad
)
]
interface
nsIBrowsingContextReadyCallback
:
nsISupports
{
void
browsingContextReady
(
in
BrowsingContext
bc
)
;
}
;
[
scriptable
builtinclass
uuid
(
30359edb
-
126c
-
4f65
-
ae80
-
07fb158697f9
)
]
interface
nsIOpenWindowInfo
:
nsISupports
{
[
infallible
]
readonly
attribute
BrowsingContext
parent
;
[
infallible
]
readonly
attribute
boolean
isRemote
;
[
infallible
]
readonly
attribute
boolean
forceNoOpener
;
[
infallible
]
readonly
attribute
boolean
isForPrinting
;
[
infallible
]
readonly
attribute
boolean
isForPrintPreview
;
[
notxpcom
nostdcall
]
BrowserParent
getNextRemoteBrowser
(
)
;
[
implicit_jscontext
binaryname
(
ScriptableOriginAttributes
)
]
readonly
attribute
jsval
originAttributes
;
[
notxpcom
nostdcall
binaryname
(
GetOriginAttributes
)
]
const_OriginAttributes
binaryGetOriginAttributes
(
)
;
[
notxpcom
nostdcall
]
nsIBrowsingContextReadyCallback
browsingContextReadyCallback
(
)
;
}
;
