#
include
"
nsISupports
.
idl
"
webidl
BrowsingContext
;
%
{
C
+
+
namespace
mozilla
{
class
OriginAttributes
;
}
%
}
[
ref
]
native
const_OriginAttributes
(
const
mozilla
:
:
OriginAttributes
)
;
[
scriptable
builtinclass
uuid
(
30359edb
-
126c
-
4f65
-
ae80
-
07fb158697f9
)
]
interface
nsIOpenWindowInfo
:
nsISupports
{
[
infallible
]
readonly
attribute
BrowsingContext
parent
;
[
infallible
]
readonly
attribute
boolean
isRemote
;
[
infallible
]
readonly
attribute
boolean
forceNoOpener
;
[
infallible
]
readonly
attribute
unsigned
long
long
nextRemoteBrowserId
;
[
implicit_jscontext
binaryname
(
ScriptableOriginAttributes
)
]
readonly
attribute
jsval
originAttributes
;
[
notxpcom
nostdcall
binaryname
(
GetOriginAttributes
)
]
const_OriginAttributes
binaryGetOriginAttributes
(
)
;
}
;
