#
include
"
nsISupports
.
idl
"
interface
mozIDOMWindowProxy
;
interface
nsIAuthPromptCallback
;
interface
nsIAuthInformation
;
interface
nsICancelable
;
interface
nsIChannel
;
webidl
BrowsingContext
;
[
scriptable
uuid
(
404ebfa2
-
d8f4
-
4c94
-
8416
-
e65a55f9df5a
)
]
interface
nsIPromptService
:
nsISupports
{
void
alert
(
in
mozIDOMWindowProxy
aParent
in
wstring
aDialogTitle
in
wstring
aText
)
;
void
alertBC
(
in
BrowsingContext
aBrowsingContext
in
unsigned
long
modalType
in
wstring
aDialogTitle
in
wstring
aText
)
;
Promise
asyncAlert
(
in
BrowsingContext
aBrowsingContext
in
unsigned
long
modalType
in
wstring
aDialogTitle
in
wstring
aText
)
;
void
alertCheck
(
in
mozIDOMWindowProxy
aParent
in
wstring
aDialogTitle
in
wstring
aText
in
wstring
aCheckMsg
inout
boolean
aCheckState
)
;
void
alertCheckBC
(
in
BrowsingContext
aBrowsingContext
in
unsigned
long
modalType
in
wstring
aDialogTitle
in
wstring
aText
in
wstring
aCheckMsg
inout
boolean
aCheckState
)
;
Promise
asyncAlertCheck
(
in
BrowsingContext
aBrowsingContext
in
unsigned
long
modalType
in
wstring
aDialogTitle
in
wstring
aText
in
wstring
aCheckMsg
in
boolean
aCheckState
)
;
boolean
confirm
(
in
mozIDOMWindowProxy
aParent
in
wstring
aDialogTitle
in
wstring
aText
)
;
boolean
confirmBC
(
in
BrowsingContext
aBrowsingContext
in
unsigned
long
modalType
in
wstring
aDialogTitle
in
wstring
aText
)
;
Promise
asyncConfirm
(
in
BrowsingContext
aBrowsingContext
in
unsigned
long
modalType
in
wstring
aDialogTitle
in
wstring
aText
)
;
boolean
confirmCheck
(
in
mozIDOMWindowProxy
aParent
in
wstring
aDialogTitle
in
wstring
aText
in
wstring
aCheckMsg
inout
boolean
aCheckState
)
;
boolean
confirmCheckBC
(
in
BrowsingContext
aBrowsingContext
in
unsigned
long
modalType
in
wstring
aDialogTitle
in
wstring
aText
in
wstring
aCheckMsg
inout
boolean
aCheckState
)
;
Promise
asyncConfirmCheck
(
in
BrowsingContext
aBrowsingContext
in
unsigned
long
modalType
in
wstring
aDialogTitle
in
wstring
aText
in
wstring
aCheckMsg
in
boolean
aCheckState
)
;
const
unsigned
long
BUTTON_POS_0
=
1
;
const
unsigned
long
BUTTON_POS_1
=
1
<
<
8
;
const
unsigned
long
BUTTON_POS_2
=
1
<
<
16
;
const
unsigned
long
BUTTON_TITLE_OK
=
1
;
const
unsigned
long
BUTTON_TITLE_CANCEL
=
2
;
const
unsigned
long
BUTTON_TITLE_YES
=
3
;
const
unsigned
long
BUTTON_TITLE_NO
=
4
;
const
unsigned
long
BUTTON_TITLE_SAVE
=
5
;
const
unsigned
long
BUTTON_TITLE_DONT_SAVE
=
6
;
const
unsigned
long
BUTTON_TITLE_REVERT
=
7
;
const
unsigned
long
BUTTON_TITLE_IS_STRING
=
127
;
const
unsigned
long
BUTTON_POS_0_DEFAULT
=
0
;
const
unsigned
long
BUTTON_POS_1_DEFAULT
=
1
<
<
24
;
const
unsigned
long
BUTTON_POS_2_DEFAULT
=
1
<
<
25
;
const
unsigned
long
BUTTON_DELAY_ENABLE
=
1
<
<
26
;
const
unsigned
long
STD_OK_CANCEL_BUTTONS
=
(
BUTTON_TITLE_OK
*
BUTTON_POS_0
)
+
(
BUTTON_TITLE_CANCEL
*
BUTTON_POS_1
)
;
const
unsigned
long
STD_YES_NO_BUTTONS
=
(
BUTTON_TITLE_YES
*
BUTTON_POS_0
)
+
(
BUTTON_TITLE_NO
*
BUTTON_POS_1
)
;
const
unsigned
long
MODAL_TYPE_CONTENT
=
1
;
const
unsigned
long
MODAL_TYPE_TAB
=
2
;
const
unsigned
long
MODAL_TYPE_WINDOW
=
3
;
int32_t
confirmEx
(
in
mozIDOMWindowProxy
aParent
in
wstring
aDialogTitle
in
wstring
aText
in
unsigned
long
aButtonFlags
in
wstring
aButton0Title
in
wstring
aButton1Title
in
wstring
aButton2Title
in
wstring
aCheckMsg
inout
boolean
aCheckState
)
;
int32_t
confirmExBC
(
in
BrowsingContext
aBrowsingContext
in
unsigned
long
modalType
in
wstring
aDialogTitle
in
wstring
aText
in
unsigned
long
aButtonFlags
in
wstring
aButton0Title
in
wstring
aButton1Title
in
wstring
aButton2Title
in
wstring
aCheckMsg
inout
boolean
aCheckState
)
;
Promise
asyncConfirmEx
(
in
BrowsingContext
aBrowsingContext
in
unsigned
long
modalType
in
wstring
aDialogTitle
in
wstring
aText
in
unsigned
long
aButtonFlags
in
wstring
aButton0Title
in
wstring
aButton1Title
in
wstring
aButton2Title
in
wstring
aCheckMsg
in
boolean
aCheckState
[
optional
]
in
jsval
aExtraArgs
)
;
boolean
prompt
(
in
mozIDOMWindowProxy
aParent
in
wstring
aDialogTitle
in
wstring
aText
inout
wstring
aValue
in
wstring
aCheckMsg
inout
boolean
aCheckState
)
;
boolean
promptBC
(
in
BrowsingContext
aBrowsingContext
in
unsigned
long
modalType
in
wstring
aDialogTitle
in
wstring
aText
inout
wstring
aValue
in
wstring
aCheckMsg
inout
boolean
aCheckState
)
;
Promise
asyncPrompt
(
in
BrowsingContext
aBrowsingContext
in
unsigned
long
modalType
in
wstring
aDialogTitle
in
wstring
aText
in
wstring
aValue
in
wstring
aCheckMsg
in
boolean
aCheckState
)
;
boolean
promptUsernameAndPassword
(
in
mozIDOMWindowProxy
aParent
in
wstring
aDialogTitle
in
wstring
aText
inout
wstring
aUsername
inout
wstring
aPassword
in
wstring
aCheckMsg
inout
boolean
aCheckState
)
;
boolean
promptUsernameAndPasswordBC
(
in
BrowsingContext
aBrowsingContext
in
unsigned
long
modalType
in
wstring
aDialogTitle
in
wstring
aText
inout
wstring
aUsername
inout
wstring
aPassword
in
wstring
aCheckMsg
inout
boolean
aCheckState
)
;
Promise
asyncPromptUsernameAndPassword
(
in
BrowsingContext
aBrowsingContext
in
unsigned
long
modalType
in
wstring
aDialogTitle
in
wstring
aText
in
wstring
aUsername
in
wstring
aPassword
in
wstring
aCheckMsg
in
boolean
aCheckState
)
;
boolean
promptPassword
(
in
mozIDOMWindowProxy
aParent
in
wstring
aDialogTitle
in
wstring
aText
inout
wstring
aPassword
in
wstring
aCheckMsg
inout
boolean
aCheckState
)
;
boolean
promptPasswordBC
(
in
BrowsingContext
aBrowsingContext
in
unsigned
long
modalType
in
wstring
aDialogTitle
in
wstring
aText
inout
wstring
aPassword
in
wstring
aCheckMsg
inout
boolean
aCheckState
)
;
Promise
asyncPromptPassword
(
in
BrowsingContext
aBrowsingContext
in
unsigned
long
modalType
in
wstring
aDialogTitle
in
wstring
aText
in
wstring
aPassword
in
wstring
aCheckMsg
in
boolean
aCheckState
)
;
boolean
select
(
in
mozIDOMWindowProxy
aParent
in
wstring
aDialogTitle
in
wstring
aText
in
Array
<
AString
>
aSelectList
out
long
aOutSelection
)
;
boolean
selectBC
(
in
BrowsingContext
aBrowsingContext
in
unsigned
long
modalType
in
wstring
aDialogTitle
in
wstring
aText
in
Array
<
AString
>
aSelectList
out
long
aOutSelection
)
;
Promise
asyncSelect
(
in
BrowsingContext
aBrowsingContext
in
unsigned
long
modalType
in
wstring
aDialogTitle
in
wstring
aText
in
Array
<
AString
>
aSelectList
)
;
boolean
promptAuth
(
in
mozIDOMWindowProxy
aParent
in
nsIChannel
aChannel
in
uint32_t
level
in
nsIAuthInformation
authInfo
in
wstring
checkboxLabel
inout
boolean
checkValue
)
;
boolean
promptAuthBC
(
in
BrowsingContext
aBrowsingContext
in
unsigned
long
modalType
in
nsIChannel
aChannel
in
uint32_t
level
in
nsIAuthInformation
authInfo
in
wstring
checkboxLabel
inout
boolean
checkValue
)
;
nsICancelable
asyncPromptAuth
(
in
mozIDOMWindowProxy
aParent
in
nsIChannel
aChannel
in
nsIAuthPromptCallback
aCallback
in
nsISupports
aContext
in
uint32_t
level
in
nsIAuthInformation
authInfo
in
wstring
checkboxLabel
inout
boolean
checkValue
)
;
nsICancelable
asyncPromptAuthBC
(
in
BrowsingContext
aBrowsingContext
in
unsigned
long
modalType
in
nsIChannel
aChannel
in
nsIAuthPromptCallback
aCallback
in
nsISupports
aContext
in
uint32_t
level
in
nsIAuthInformation
authInfo
in
wstring
checkboxLabel
inout
boolean
checkValue
)
;
}
;
