#
include
"
nsISupports
.
idl
"
%
{
C
+
+
#
include
"
mozilla
/
dom
/
UserActivation
.
h
"
class
nsDocShellLoadState
;
namespace
mozilla
:
:
dom
{
class
WindowFeatures
;
}
%
}
webidl
BrowsingContext
;
interface
mozIDOMWindowProxy
;
interface
nsISimpleEnumerator
;
interface
nsIWebBrowserChrome
;
interface
nsIDocShellTreeItem
;
interface
nsIArray
;
interface
nsIRemoteTab
;
interface
nsIOpenWindowInfo
;
native
nsDocShellLoadStatePtr
(
nsDocShellLoadState
*
)
;
[
ref
]
native
WindowFeaturesRef
(
const
mozilla
:
:
dom
:
:
WindowFeatures
)
;
[
ref
]
native
UserActivationModifiersRef
(
const
mozilla
:
:
dom
:
:
UserActivation
:
:
Modifiers
)
;
[
uuid
(
d162f9c4
-
19d5
-
4723
-
931f
-
f1e51bfa9f68
)
]
interface
nsPIWindowWatcher
:
nsISupports
{
void
addWindow
(
in
mozIDOMWindowProxy
aWindow
in
nsIWebBrowserChrome
aChrome
)
;
void
removeWindow
(
in
mozIDOMWindowProxy
aWindow
)
;
cenum
PrintKind
:
8
{
PRINT_NONE
PRINT_INTERNAL
PRINT_WINDOW_DOT_PRINT
}
;
[
noscript
]
BrowsingContext
openWindow2
(
in
mozIDOMWindowProxy
aParent
in
ACString
aUrl
in
ACString
aName
in
ACString
aFeatures
in
UserActivationModifiersRef
aModifiers
in
boolean
aCalledFromScript
in
boolean
aDialog
in
boolean
aNavigate
in
nsISupports
aArgs
in
boolean
aIsPopupSpam
in
boolean
aForceNoOpener
in
boolean
aForceNoReferrer
in
nsPIWindowWatcher_PrintKind
aPrintKind
in
nsDocShellLoadStatePtr
aLoadState
)
;
nsIRemoteTab
openWindowWithRemoteTab
(
in
nsIRemoteTab
aOpeningTab
in
WindowFeaturesRef
aFeatures
in
UserActivationModifiersRef
aModifiers
in
boolean
aCalledFromJS
in
float
aOpenerFullZoom
in
nsIOpenWindowInfo
aOpenWindowInfo
)
;
}
;
