#
include
"
nsISupports
.
idl
"
interface
nsIPrincipal
;
interface
nsIClearDataCallback
;
[
scriptable
uuid
(
6ef3ef16
-
a502
-
4576
-
9fb4
-
919f1c40bf61
)
]
interface
nsIClearDataService
:
nsISupports
{
void
deleteDataFromLocalFiles
(
in
bool
aIsUserRequest
in
uint32_t
aFlags
in
nsIClearDataCallback
aCallback
)
;
void
deleteDataFromHost
(
in
AUTF8String
aHost
in
bool
aIsUserRequest
in
uint32_t
aFlags
in
nsIClearDataCallback
aCallback
)
;
void
deleteDataFromPrincipal
(
in
nsIPrincipal
aPrincipal
in
bool
aIsUserRequest
in
uint32_t
aFlags
in
nsIClearDataCallback
aCallback
)
;
void
deleteDataInTimeRange
(
in
PRTime
aFrom
in
PRTime
aTo
in
bool
aIsUserRequest
in
uint32_t
aFlags
in
nsIClearDataCallback
aCallback
)
;
void
deleteData
(
in
uint32_t
aFlags
in
nsIClearDataCallback
aCallback
)
;
void
deleteDataFromOriginAttributesPattern
(
in
jsval
aOriginAttributesPattern
[
optional
]
in
nsIClearDataCallback
aCallback
)
;
const
uint32_t
CLEAR_COOKIES
=
1
<
<
0
;
const
uint32_t
CLEAR_NETWORK_CACHE
=
1
<
<
1
;
const
uint32_t
CLEAR_IMAGE_CACHE
=
1
<
<
2
;
const
uint32_t
CLEAR_PLUGIN_DATA
=
1
<
<
3
;
const
uint32_t
CLEAR_DOWNLOADS
=
1
<
<
4
;
const
uint32_t
CLEAR_PASSWORDS
=
1
<
<
5
;
const
uint32_t
CLEAR_MEDIA_DEVICES
=
1
<
<
6
;
const
uint32_t
CLEAR_APPCACHE
=
1
<
<
7
;
const
uint32_t
CLEAR_DOM_QUOTA
=
1
<
<
8
;
const
uint32_t
CLEAR_PREDICTOR_NETWORK_DATA
=
1
<
<
9
;
const
uint32_t
CLEAR_DOM_PUSH_NOTIFICATIONS
=
1
<
<
10
;
const
uint32_t
CLEAR_HISTORY
=
1
<
<
11
;
const
uint32_t
CLEAR_SESSION_HISTORY
=
1
<
<
12
;
const
uint32_t
CLEAR_AUTH_TOKENS
=
1
<
<
13
;
const
uint32_t
CLEAR_AUTH_CACHE
=
1
<
<
14
;
const
uint32_t
CLEAR_PERMISSIONS
=
1
<
<
15
;
const
uint32_t
CLEAR_CONTENT_PREFERENCES
=
1
<
<
16
;
const
uint32_t
CLEAR_SECURITY_SETTINGS
=
1
<
<
17
;
const
uint32_t
CLEAR_EME
=
1
<
<
18
;
const
uint32_t
CLEAR_REPORTS
=
1
<
<
19
;
const
uint32_t
CLEAR_STORAGE_ACCESS
=
1
<
<
20
;
const
uint32_t
CLEAR_CERT_EXCEPTIONS
=
1
<
<
21
;
const
uint32_t
CLEAR_CONTENT_BLOCKING_RECORDS
=
1
<
<
22
;
const
uint32_t
CLEAR_CSS_CACHE
=
1
<
<
23
;
const
uint32_t
CLEAR_ALL
=
0xFFFFFF
;
const
uint32_t
CLEAR_ALL_CACHES
=
CLEAR_NETWORK_CACHE
|
CLEAR_IMAGE_CACHE
|
CLEAR_CSS_CACHE
;
const
uint32_t
CLEAR_DOM_STORAGES
=
CLEAR_APPCACHE
|
CLEAR_DOM_QUOTA
|
CLEAR_DOM_PUSH_NOTIFICATIONS
|
CLEAR_REPORTS
;
const
uint32_t
CLEAR_FORGET_ABOUT_SITE
=
CLEAR_HISTORY
|
CLEAR_SESSION_HISTORY
|
CLEAR_ALL_CACHES
|
CLEAR_COOKIES
|
CLEAR_EME
|
CLEAR_PLUGIN_DATA
|
CLEAR_DOWNLOADS
|
CLEAR_PASSWORDS
|
CLEAR_PERMISSIONS
|
CLEAR_DOM_STORAGES
|
CLEAR_CONTENT_PREFERENCES
|
CLEAR_PREDICTOR_NETWORK_DATA
|
CLEAR_DOM_PUSH_NOTIFICATIONS
|
CLEAR_SECURITY_SETTINGS
|
CLEAR_REPORTS
|
CLEAR_CERT_EXCEPTIONS
;
}
;
[
function
scriptable
uuid
(
e225517b
-
24c5
-
498a
-
b9fb
-
9993e341a398
)
]
interface
nsIClearDataCallback
:
nsISupports
{
void
onDataDeleted
(
in
uint32_t
aFailedFlags
)
;
}
;
