#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
5bb3d56b
-
e733
-
4a2c
-
8a53
-
058123df65e2
)
]
interface
nsIBrowserController
:
nsISupports
{
void
enableDisableCommands
(
in
AString
action
in
Array
<
ACString
>
enabledCommands
in
Array
<
ACString
>
disabledCommands
)
;
}
;
