#
include
"
nsISupports
.
idl
"
interface
nsIURI
;
[
scriptable
uuid
(
68067eb5
-
ad8d
-
43cb
-
a043
-
1cc85ebe06e7
)
]
interface
nsIEffectiveTLDService
:
nsISupports
{
ACString
getPublicSuffix
(
in
nsIURI
aURI
)
;
ACString
getKnownPublicSuffix
(
in
nsIURI
aURI
)
;
ACString
getBaseDomain
(
in
nsIURI
aURI
[
optional
]
in
uint32_t
aAdditionalParts
)
;
ACString
getSchemelessSite
(
in
nsIURI
aURI
)
;
ACString
getSchemelessSiteFromHost
(
in
AUTF8String
aHost
)
;
ACString
getSite
(
in
nsIURI
aURI
)
;
ACString
getPublicSuffixFromHost
(
in
AUTF8String
aHost
)
;
ACString
getKnownPublicSuffixFromHost
(
in
AUTF8String
aHost
)
;
ACString
getBaseDomainFromHost
(
in
AUTF8String
aHost
[
optional
]
in
uint32_t
aAdditionalParts
)
;
ACString
getNextSubDomain
(
in
AUTF8String
aHost
)
;
boolean
hasRootDomain
(
in
AUTF8String
aInput
in
AUTF8String
aHost
)
;
boolean
hasKnownPublicSuffix
(
in
nsIURI
aURI
)
;
boolean
hasKnownPublicSuffixFromHost
(
in
AUTF8String
aHost
)
;
}
;
