#
include
"
nsISupports
.
idl
"
#
include
"
mozIStorageBindingParams
.
idl
"
interface
mozIStorageConnection
;
interface
mozIStorageStatementCallback
;
interface
mozIStoragePendingStatement
;
interface
mozIStorageBindingParams
;
interface
mozIStorageBindingParamsArray
;
[
scriptable
builtinclass
uuid
(
16ca67aa
-
1325
-
43e2
-
aac7
-
859afd1590b2
)
]
interface
mozIStorageBaseStatement
:
mozIStorageBindingParams
{
void
finalize
(
)
;
void
bindParameters
(
in
mozIStorageBindingParamsArray
aParameters
)
;
mozIStorageBindingParamsArray
newBindingParamsArray
(
)
;
mozIStoragePendingStatement
executeAsync
(
[
optional
]
in
mozIStorageStatementCallback
aCallback
)
;
const
long
MOZ_STORAGE_STATEMENT_INVALID
=
0
;
const
long
MOZ_STORAGE_STATEMENT_READY
=
1
;
const
long
MOZ_STORAGE_STATEMENT_EXECUTING
=
2
;
readonly
attribute
long
state
;
AString
escapeStringForLIKE
(
in
AString
aValue
in
wchar
aEscapeChar
)
;
AUTF8String
escapeUTF8StringForLIKE
(
in
AUTF8String
aValue
in
char
aEscapeChar
)
;
}
;
