#
include
"
nsISupports
.
idl
"
interface
mozIStorageConnection
;
[
scriptable
uuid
(
8f367508
-
1d9a
-
4d3f
-
be0c
-
ac11b6dd7dbf
)
]
interface
mozIStorageVacuumParticipant
:
nsISupports
{
readonly
attribute
long
expectedDatabasePageSize
;
readonly
attribute
mozIStorageConnection
databaseConnection
;
boolean
onBeginVacuum
(
)
;
void
onEndVacuum
(
in
boolean
aSucceeded
)
;
}
;
