#
include
"
nsISupports
.
idl
"
interface
nsIXPCScriptable
;
[
scriptable
uuid
(
a60569d7
-
d401
-
4677
-
ba63
-
2aa5971af25d
)
]
interface
nsIClassInfo
:
nsISupports
{
readonly
attribute
Array
<
nsIIDRef
>
interfaces
;
[
noscript
]
nsIXPCScriptable
getScriptableHelper
(
)
;
readonly
attribute
AUTF8String
contractID
;
readonly
attribute
AUTF8String
classDescription
;
readonly
attribute
nsCIDPtr
classID
;
const
uint32_t
SINGLETON
=
1
<
<
0
;
const
uint32_t
THREADSAFE
=
1
<
<
1
;
const
uint32_t
SINGLETON_CLASSINFO
=
1
<
<
5
;
const
uint32_t
RESERVED
=
1
<
<
31
;
readonly
attribute
uint32_t
flags
;
[
noscript
]
readonly
attribute
nsCID
classIDNoAlloc
;
}
;
