#
include
"
nsISupports
.
idl
"
%
{
C
+
+
namespace
mozilla
{
class
HangDetails
;
}
%
}
[
ref
]
native
HangDetailsRef
(
mozilla
:
:
HangDetails
)
;
[
scriptable
uuid
(
23d63fff
-
38d6
-
4003
-
9c57
-
2c90aca1180a
)
]
interface
nsIHangDetails
:
nsISupports
{
readonly
attribute
boolean
wasPersisted
;
readonly
attribute
double
duration
;
readonly
attribute
ACString
thread
;
readonly
attribute
ACString
runnableName
;
readonly
attribute
ACString
process
;
readonly
attribute
AUTF8String
remoteType
;
[
implicit_jscontext
]
readonly
attribute
jsval
stack
;
[
implicit_jscontext
]
readonly
attribute
jsval
modules
;
[
implicit_jscontext
]
readonly
attribute
jsval
annotations
;
}
;
