#
include
"
nsISupports
.
idl
"
interface
nsIPrincipal
;
[
scriptable
uuid
(
d60a08ee
-
5c83
-
4eb6
-
bdfb
-
79fd0716501e
)
]
interface
nsIUrlListManager
:
nsISupports
{
ACString
getGethashUrl
(
in
ACString
tableName
)
;
ACString
getUpdateUrl
(
in
ACString
tableName
)
;
boolean
registerTable
(
in
ACString
tableName
in
ACString
providerName
in
ACString
updateUrl
in
ACString
gethashUrl
)
;
void
unregisterTable
(
in
ACString
tableName
)
;
void
enableUpdate
(
in
ACString
tableName
)
;
void
disableAllUpdates
(
)
;
void
disableUpdate
(
in
ACString
tableName
)
;
void
maybeToggleUpdateChecking
(
)
;
boolean
checkForUpdates
(
in
ACString
updateUrl
)
;
boolean
forceUpdates
(
in
ACString
tableNames
)
;
uint64_t
getBackOffTime
(
in
ACString
provider
)
;
boolean
isRegistered
(
)
;
}
;
