#
include
"
nsISupports
.
idl
"
#
include
"
nsIArray
.
idl
"
[
scriptable
uuid
(
b3c27f8c
-
7db8
-
4f3f
-
97a5
-
5a94d781e565
)
]
interface
nsIUrlClassifierPositiveCacheEntry
:
nsISupports
{
readonly
attribute
ACString
fullhash
;
readonly
attribute
long
long
expiry
;
}
;
[
scriptable
uuid
(
d6297907
-
8236
-
4126
-
adaf
-
c3aa239a0d40
)
]
interface
nsIUrlClassifierCacheEntry
:
nsISupports
{
readonly
attribute
ACString
prefix
;
readonly
attribute
long
long
expiry
;
readonly
attribute
nsIArray
matches
;
}
;
[
scriptable
uuid
(
69384f24
-
d9c5
-
4462
-
b24e
-
351c69e3b46a
)
]
interface
nsIUrlClassifierCacheInfo
:
nsISupports
{
readonly
attribute
ACString
table
;
readonly
attribute
nsIArray
entries
;
}
;
[
scriptable
function
uuid
(
26e12ea4
-
14ff
-
4c77
-
858f
-
6745998b7659
)
]
interface
nsIUrlClassifierGetCacheCallback
:
nsISupports
{
void
onGetCacheComplete
(
in
nsIUrlClassifierCacheInfo
info
)
;
}
;
[
scriptable
uuid
(
411bbff4
-
1b88
-
4687
-
aa36
-
e2bbdd93f6e8
)
]
interface
nsIUrlClassifierInfo
:
nsISupports
{
void
getCacheInfo
(
in
ACString
table
in
nsIUrlClassifierGetCacheCallback
callback
)
;
}
;
