#
include
"
nsISupports
.
idl
"
#
include
"
nsIUrlClassifierDBService
.
idl
"
[
scriptable
uuid
(
e1797597
-
f4d6
-
4dd3
-
a1e1
-
745ad352cd80
)
]
interface
nsIUrlClassifierStreamUpdater
:
nsISupports
{
boolean
downloadUpdates
(
in
ACString
aRequestTables
in
ACString
aRequestPayload
in
ACString
aRequestQueryParameters
in
boolean
aIsPostRequest
in
ACString
aProvider
in
ACString
aUpdateUrl
in
nsIUrlClassifierCallback
aSuccessCallback
in
nsIUrlClassifierCallback
aUpdateErrorCallback
in
nsIUrlClassifierCallback
aDownloadErrorCallback
)
;
}
;
