#
include
"
nsISupports
.
idl
"
interface
nsIURI
;
[
scriptable
uuid
(
249fb5ad
-
ae29
-
4e2c
-
a728
-
ba5cf464d188
)
]
interface
nsIChromeRegistry
:
nsISupports
{
const
int32_t
NONE
=
0
;
const
int32_t
PARTIAL
=
1
;
const
int32_t
FULL
=
2
;
nsIURI
convertChromeURL
(
in
nsIURI
aChromeURL
)
;
void
checkForNewChrome
(
)
;
}
;
[
scriptable
uuid
(
93251ddf
-
5e85
-
4172
-
ac2a
-
31780562974f
)
]
interface
nsIXULChromeRegistry
:
nsIChromeRegistry
{
boolean
isLocaleRTL
(
in
ACString
package
)
;
boolean
allowScriptsForPackage
(
in
nsIURI
url
)
;
boolean
allowContentToAccess
(
in
nsIURI
url
)
;
boolean
canLoadURLRemotely
(
in
nsIURI
url
)
;
boolean
mustLoadURLRemotely
(
in
nsIURI
url
)
;
}
;
%
{
C
+
+
#
define
NS_CHROMEREGISTRY_CONTRACTID
\
"
mozilla
.
org
/
chrome
/
chrome
-
registry
;
1
"
#
define
NS_CHROME_FLUSH_TOPIC
\
"
chrome
-
flush
-
caches
"
%
}
