#
include
"
nsISupports
.
idl
"
interface
nsIPrincipal
;
interface
nsIAsyncInputStream
;
[
scriptable
uuid
(
650934db
-
1939
-
4424
-
be26
-
6ffb0375424d
)
]
interface
nsITrackingDBService
:
nsISupports
{
void
recordContentBlockingLog
(
in
ACString
data
)
;
Promise
saveEvents
(
in
AString
data
)
;
Promise
clearAll
(
)
;
Promise
clearSince
(
in
int64_t
since
)
;
Promise
getEventsByDateRange
(
in
int64_t
dateFrom
in
int64_t
dateTo
)
;
Promise
sumAllEvents
(
)
;
Promise
getEarliestRecordedDate
(
)
;
const
unsigned
long
OTHER_COOKIES_BLOCKED_ID
=
0
;
const
unsigned
long
TRACKERS_ID
=
1
;
const
unsigned
long
TRACKING_COOKIES_ID
=
2
;
const
unsigned
long
CRYPTOMINERS_ID
=
3
;
const
unsigned
long
FINGERPRINTERS_ID
=
4
;
const
unsigned
long
SOCIAL_ID
=
5
;
const
unsigned
long
SUSPICIOUS_FINGERPRINTERS_ID
=
6
;
const
unsigned
long
BOUNCETRACKERS_ID
=
7
;
}
;
