#
include
"
nsIOutputStream
.
idl
"
%
{
C
+
+
#
include
"
mozilla
/
Try
.
h
"
namespace
mozilla
{
template
<
class
ElementType
size_t
Extent
>
class
Span
;
}
%
}
native
Bytes
(
mozilla
:
:
Span
<
const
uint8_t
>
)
;
[
scriptable
builtinclass
uuid
(
204ee610
-
8765
-
11d3
-
90cf
-
0040056a906e
)
]
interface
nsIBinaryOutputStream
:
nsIOutputStream
{
void
setOutputStream
(
in
nsIOutputStream
aOutputStream
)
;
[
must_use
]
void
writeBoolean
(
in
boolean
aBoolean
)
;
[
must_use
]
void
write8
(
in
uint8_t
aByte
)
;
[
must_use
]
void
write16
(
in
uint16_t
a16
)
;
[
must_use
]
void
write32
(
in
uint32_t
a32
)
;
[
must_use
]
void
write64
(
in
uint64_t
a64
)
;
[
must_use
]
void
writeFloat
(
in
float
aFloat
)
;
[
must_use
]
void
writeDouble
(
in
double
aDouble
)
;
[
must_use
]
void
writeStringZ
(
in
string
aString
)
;
[
must_use
]
void
writeWStringZ
(
in
wstring
aString
)
;
[
must_use
]
void
writeUtf8Z
(
in
wstring
aString
)
;
[
binaryname
(
WriteBytesFromJS
)
must_use
]
void
writeBytes
(
[
size_is
(
aLength
)
]
in
string
aString
[
optional
]
in
uint32_t
aLength
)
;
[
noscript
nostdcall
binaryname
(
WriteBytes
)
must_use
]
void
writeBytesNative
(
in
Bytes
aBytes
)
;
[
must_use
]
void
writeByteArray
(
in
Array
<
uint8_t
>
aBytes
)
;
%
{
C
+
+
[
[
nodiscard
]
]
nsresult
WriteCString
(
const
nsACString
&
aString
)
{
MOZ_TRY
(
Write32
(
aString
.
Length
(
)
)
)
;
return
WriteBytes
(
aString
)
;
}
%
}
}
;
%
{
C
+
+
[
[
nodiscard
]
]
inline
nsresult
NS_WriteOptionalStringZ
(
nsIBinaryOutputStream
*
aStream
const
char
*
aString
)
{
bool
nonnull
=
(
aString
!
=
nullptr
)
;
MOZ_TRY
(
aStream
-
>
WriteBoolean
(
nonnull
)
)
;
if
(
nonnull
)
{
MOZ_TRY
(
aStream
-
>
WriteStringZ
(
aString
)
)
;
}
return
NS_OK
;
}
[
[
nodiscard
]
]
inline
nsresult
NS_WriteOptionalWStringZ
(
nsIBinaryOutputStream
*
aStream
const
char16_t
*
aString
)
{
bool
nonnull
=
(
aString
!
=
nullptr
)
;
MOZ_TRY
(
aStream
-
>
WriteBoolean
(
nonnull
)
)
;
if
(
nonnull
)
{
MOZ_TRY
(
aStream
-
>
WriteWStringZ
(
aString
)
)
;
}
return
NS_OK
;
}
%
}
