#
include
"
nsIUnicharInputStream
.
idl
"
interface
nsIInputStream
;
[
scriptable
builtinclass
uuid
(
FC66FFB6
-
5404
-
4908
-
A4A3
-
27F92FA0579D
)
]
interface
nsIConverterInputStream
:
nsIUnicharInputStream
{
const
char16_t
DEFAULT_REPLACEMENT_CHARACTER
=
0xFFFD
;
const
char16_t
ERRORS_ARE_FATAL
=
0
;
void
init
(
in
nsIInputStream
aStream
in
string
aCharset
in
long
aBufferSize
in
char16_t
aReplacementChar
)
;
}
;
