#
include
"
nsISupports
.
idl
"
#
include
"
nsISimpleEnumerator
.
idl
"
interface
nsIFile
;
[
scriptable
uuid
(
31f7f4ae
-
6916
-
4f2d
-
a81e
-
926a4e3022ee
)
]
interface
nsIDirectoryEnumerator
:
nsISimpleEnumerator
{
readonly
attribute
nsIFile
nextFile
;
void
close
(
)
;
}
;
