#
include
"
nsISupports
.
idl
"
interface
nsIFile
;
interface
nsISimpleEnumerator
;
[
scriptable
uuid
(
bbf8cab0
-
d43a
-
11d3
-
8cc2
-
00609792278c
)
]
interface
nsIDirectoryServiceProvider
:
nsISupports
{
nsIFile
getFile
(
in
string
prop
out
boolean
persistent
)
;
}
;
[
scriptable
uuid
(
2f977d4b
-
5485
-
11d4
-
87e2
-
0010a4e75ef2
)
]
interface
nsIDirectoryServiceProvider2
:
nsIDirectoryServiceProvider
{
nsISimpleEnumerator
getFiles
(
in
string
prop
)
;
}
;
[
scriptable
uuid
(
57a66a60
-
d43a
-
11d3
-
8cc2
-
00609792278c
)
]
interface
nsIDirectoryService
:
nsISupports
{
void
init
(
)
;
void
registerProvider
(
in
nsIDirectoryServiceProvider
prov
)
;
void
unregisterProvider
(
in
nsIDirectoryServiceProvider
prov
)
;
}
;
