#
include
"
nsISupports
.
idl
"
interface
nsIInputStream
;
interface
nsIOutputStream
;
[
scriptable
uuid
(
e8152f7f
-
4209
-
4c63
-
ad23
-
c3d2aa0c5a49
)
]
interface
nsIIOUtil
:
nsISupports
{
boolean
inputStreamIsBuffered
(
in
nsIInputStream
aStream
)
;
boolean
outputStreamIsBuffered
(
in
nsIOutputStream
aStream
)
;
}
;
