#
include
"
nsIInputStream
.
idl
"
interface
nsIOutputStream
;
interface
nsIEventTarget
;
[
scriptable
builtinclass
uuid
(
90a9d790
-
3bca
-
421e
-
a73b
-
98f68e13c917
)
]
interface
nsIInputStreamTee
:
nsIInputStream
{
attribute
nsIInputStream
source
;
attribute
nsIOutputStream
sink
;
attribute
nsIEventTarget
eventTarget
;
}
;
%
{
C
+
+
extern
nsresult
NS_NewInputStreamTee
(
nsIInputStream
*
*
tee
nsIInputStream
*
source
nsIOutputStream
*
sink
)
;
extern
nsresult
NS_NewInputStreamTeeAsync
(
nsIInputStream
*
*
tee
nsIInputStream
*
source
nsIOutputStream
*
sink
nsIEventTarget
*
eventTarget
)
;
%
}
