#
include
"
nsISupports
.
idl
"
interface
nsIInputStream
;
%
{
C
+
+
typedef
nsresult
(
*
nsWriteSegmentFun
)
(
nsIInputStream
*
aInStream
void
*
aClosure
const
char
*
aFromSegment
uint32_t
aToOffset
uint32_t
aCount
uint32_t
*
aWriteCount
)
;
%
}
native
nsWriteSegmentFun
(
nsWriteSegmentFun
)
;
[
scriptable
uuid
(
53cdbc97
-
c2d7
-
4e30
-
b2c3
-
45b2ee79db18
)
]
interface
nsIInputStream
:
nsISupports
{
void
close
(
)
;
unsigned
long
long
available
(
)
;
[
noscript
]
unsigned
long
read
(
in
charPtr
aBuf
in
unsigned
long
aCount
)
;
[
noscript
]
unsigned
long
readSegments
(
in
nsWriteSegmentFun
aWriter
in
voidPtr
aClosure
in
unsigned
long
aCount
)
;
boolean
isNonBlocking
(
)
;
}
;
