#
include
"
nsIFile
.
idl
"
%
{
C
+
+
struct
PRFileDesc
;
%
}
[
ptr
]
native
PRFileDescStar
(
PRFileDesc
)
;
[
scriptable
builtinclass
uuid
(
e7a3a954
-
384b
-
4aeb
-
a5f7
-
55626b0de9be
)
]
interface
nsILocalFileWin
:
nsIFile
{
void
initWithCommandLine
(
in
AString
aCommandLine
)
;
AString
getVersionInfoField
(
in
string
aField
)
;
[
noscript
]
readonly
attribute
AString
canonicalPath
;
attribute
bool
readOnly
;
attribute
boolean
useDOSDevicePathSyntax
;
[
noscript
]
PRFileDescStar
openNSPRFileDescShareDelete
(
in
long
flags
in
long
mode
)
;
[
noscript
]
unsigned
long
getWindowsFileAttributes
(
)
;
[
noscript
]
void
setWindowsFileAttributes
(
in
unsigned
long
aSetAttrs
in
unsigned
long
aClearAttrs
)
;
}
;
