#
include
"
nsIInputStream
.
idl
"
[
scriptable
builtinclass
uuid
(
a076fd12
-
1dd1
-
11b2
-
b19a
-
d53b5dffaade
)
]
interface
nsIMultiplexInputStream
:
nsISupports
{
[
infallible
]
readonly
attribute
unsigned
long
count
;
void
appendStream
(
in
nsIInputStream
stream
)
;
nsIInputStream
getStream
(
in
unsigned
long
index
)
;
}
;
