#
include
"
nsISupports
.
idl
"
interface
nsIOutputStream
;
interface
nsIInputStream
;
%
{
C
+
+
typedef
nsresult
(
*
nsReadSegmentFun
)
(
nsIOutputStream
*
aOutStream
void
*
aClosure
char
*
aToSegment
uint32_t
aFromOffset
uint32_t
aCount
uint32_t
*
aReadCount
)
;
%
}
native
nsReadSegmentFun
(
nsReadSegmentFun
)
;
[
scriptable
builtinclass
uuid
(
0d0acd2a
-
61b4
-
11d4
-
9877
-
00c04fa0cf4a
)
]
interface
nsIOutputStream
:
nsISupports
{
void
close
(
)
;
void
flush
(
)
;
unsigned
long
write
(
in
string
aBuf
in
unsigned
long
aCount
)
;
unsigned
long
writeFrom
(
in
nsIInputStream
aFromStream
in
unsigned
long
aCount
)
;
[
noscript
]
unsigned
long
writeSegments
(
in
nsReadSegmentFun
aReader
in
voidPtr
aClosure
in
unsigned
long
aCount
)
;
boolean
isNonBlocking
(
)
;
}
;
