#
include
"
nsIBinaryOutputStream
.
idl
"
[
scriptable
builtinclass
uuid
(
92c898ac
-
5fde
-
4b99
-
87b3
-
5d486422094b
)
]
interface
nsIObjectOutputStream
:
nsIBinaryOutputStream
{
[
must_use
]
void
writeObject
(
in
nsISupports
aObject
in
boolean
aIsStrongRef
)
;
[
must_use
]
void
writeSingleRefObject
(
in
nsISupports
aObject
)
;
[
must_use
]
void
writeCompoundObject
(
in
nsISupports
aObject
in
nsIIDRef
aIID
in
boolean
aIsStrongRef
)
;
[
must_use
]
void
writeID
(
in
nsIDRef
aID
)
;
[
notxpcom
must_use
]
charPtr
getBuffer
(
in
uint32_t
aLength
in
uint32_t
aAlignMask
)
;
[
notxpcom
]
void
putBuffer
(
in
charPtr
aBuffer
in
uint32_t
aLength
)
;
}
;
%
{
C
+
+
already_AddRefed
<
nsIObjectOutputStream
>
NS_NewObjectOutputStream
(
nsIOutputStream
*
aOutputStream
)
;
[
[
nodiscard
]
]
inline
nsresult
NS_WriteOptionalObject
(
nsIObjectOutputStream
*
aStream
nsISupports
*
aObject
bool
aIsStrongRef
)
{
bool
nonnull
=
(
aObject
!
=
nullptr
)
;
MOZ_TRY
(
aStream
-
>
WriteBoolean
(
nonnull
)
)
;
if
(
nonnull
)
{
MOZ_TRY
(
aStream
-
>
WriteObject
(
aObject
aIsStrongRef
)
)
;
}
return
NS_OK
;
}
[
[
nodiscard
]
]
inline
nsresult
NS_WriteOptionalSingleRefObject
(
nsIObjectOutputStream
*
aStream
nsISupports
*
aObject
)
{
bool
nonnull
=
(
aObject
!
=
nullptr
)
;
MOZ_TRY
(
aStream
-
>
WriteBoolean
(
nonnull
)
)
;
if
(
nonnull
)
{
MOZ_TRY
(
aStream
-
>
WriteSingleRefObject
(
aObject
)
)
;
}
return
NS_OK
;
}
[
[
nodiscard
]
]
inline
nsresult
NS_WriteOptionalCompoundObject
(
nsIObjectOutputStream
*
aStream
nsISupports
*
aObject
const
nsIID
&
aIID
bool
aIsStrongRef
)
{
bool
nonnull
=
(
aObject
!
=
nullptr
)
;
MOZ_TRY
(
aStream
-
>
WriteBoolean
(
nonnull
)
)
;
if
(
nonnull
)
{
MOZ_TRY
(
aStream
-
>
WriteCompoundObject
(
aObject
aIID
aIsStrongRef
)
)
;
}
return
NS_OK
;
}
%
}
