#
include
"
nsISupports
.
idl
"
#
include
"
nsISeekableStream
.
idl
"
interface
nsIInputStream
;
interface
nsIInterfaceRequestor
;
interface
nsIOutputStream
;
%
{
C
+
+
namespace
mozilla
:
:
ipc
{
class
RandomAccessStreamParams
;
}
%
}
native
RandomAccessStreamParams
(
mozilla
:
:
ipc
:
:
RandomAccessStreamParams
)
;
[
ref
]
native
RandomAccessStreamParamsRef
(
mozilla
:
:
ipc
:
:
RandomAccessStreamParams
)
;
[
scriptable
builtinclass
uuid
(
9b5904a8
-
886a
-
420f
-
a1d8
-
847de8ffc133
)
]
interface
nsIRandomAccessStream
:
nsISeekableStream
{
nsIInputStream
getInputStream
(
)
;
nsIOutputStream
getOutputStream
(
)
;
[
notxpcom
nostdcall
]
nsIInputStream
inputStream
(
)
;
[
notxpcom
nostdcall
]
nsIOutputStream
outputStream
(
)
;
[
notxpcom
nostdcall
]
RandomAccessStreamParams
serialize
(
in
nsIInterfaceRequestor
aCallbacks
)
;
[
notxpcom
nostdcall
]
boolean
deserialize
(
inout
RandomAccessStreamParamsRef
params
)
;
}
;
