#
include
"
nsIInputStream
.
idl
"
%
{
C
+
+
#
include
"
mozilla
/
MemoryReporting
.
h
"
namespace
mozilla
{
class
StreamBufferSource
;
}
%
}
native
MallocSizeOf
(
mozilla
:
:
MallocSizeOf
)
;
[
ptr
]
native
StreamBufferSource
(
mozilla
:
:
StreamBufferSource
)
;
[
scriptable
builtinclass
uuid
(
450cd2d4
-
f0fd
-
424d
-
b365
-
b1251f80fd53
)
]
interface
nsIStringInputStream
:
nsIInputStream
{
void
setData
(
in
string
data
in
long
dataLen
)
;
void
setUTF8Data
(
in
AUTF8String
data
)
;
[
noscript
]
void
adoptData
(
in
charPtr
data
in
long
dataLen
)
;
[
noscript
]
void
shareData
(
in
string
data
in
long
dataLen
)
;
[
noscript
]
void
setDataSource
(
in
StreamBufferSource
source
)
;
[
noscript
notxpcom
]
size_t
SizeOfIncludingThisIfUnshared
(
in
MallocSizeOf
aMallocSizeOf
)
;
[
noscript
notxpcom
]
size_t
SizeOfIncludingThisEvenIfShared
(
in
MallocSizeOf
aMallocSizeOf
)
;
}
;
