#
include
"
nsISupports
.
idl
"
interface
nsIUnicharInputStream
;
interface
nsIInputStream
;
%
{
C
+
+
typedef
nsresult
(
*
nsWriteUnicharSegmentFun
)
(
nsIUnicharInputStream
*
aInStream
void
*
aClosure
const
char16_t
*
aFromSegment
uint32_t
aToOffset
uint32_t
aCount
uint32_t
*
aWriteCount
)
;
%
}
native
nsWriteUnicharSegmentFun
(
nsWriteUnicharSegmentFun
)
;
[
scriptable
uuid
(
d5e3bd80
-
6723
-
4b92
-
b0c9
-
22f6162fd94f
)
]
interface
nsIUnicharInputStream
:
nsISupports
{
[
noscript
]
unsigned
long
read
(
[
array
size_is
(
aCount
)
]
in
char16_t
aBuf
in
unsigned
long
aCount
)
;
[
noscript
]
unsigned
long
readSegments
(
in
nsWriteUnicharSegmentFun
aWriter
in
voidPtr
aClosure
in
unsigned
long
aCount
)
;
unsigned
long
readString
(
in
unsigned
long
aCount
out
AString
aString
)
;
void
close
(
)
;
}
;
