#
include
"
nsISupports
.
idl
"
interface
nsIOpenWindowInfo
;
interface
nsIURI
;
[
scriptable
uuid
(
e778cce6
-
a231
-
42f0
-
86e4
-
574600524393
)
]
interface
nsIGeckoViewServiceWorker
:
nsISupports
{
Promise
openWindow
(
in
nsIURI
uri
in
nsIOpenWindowInfo
aOpenWindowInfo
)
;
}
;
