#
include
"
nsISupports
.
idl
"
interface
nsIPrincipal
;
[
scriptable
builtinclass
uuid
(
07611dc6
-
bf4d
-
4d8a
-
a64b
-
f3a5904dddc7
)
]
interface
nsIPermissionDelegateHandler
:
nsISupports
{
boolean
maybeUnsafePermissionDelegate
(
in
Array
<
ACString
>
aTypes
)
;
}
;
