#
include
"
nsISupports
.
idl
"
interface
nsIVariant
;
%
{
C
+
+
#
include
"
js
/
TypeDecls
.
h
"
%
}
[
scriptable
uuid
(
c664aae7
-
0d67
-
4155
-
a2dd
-
a3861778626f
)
]
interface
nsIStructuredCloneContainer
:
nsISupports
{
[
noscript
implicit_jscontext
]
void
initFromJSVal
(
in
jsval
aData
)
;
void
initFromBase64
(
in
AString
aData
in
unsigned
long
aFormatVersion
)
;
[
implicit_jscontext
]
jsval
deserializeToJsval
(
)
;
AString
getDataAsBase64
(
)
;
readonly
attribute
unsigned
long
long
serializedNBytes
;
readonly
attribute
unsigned
long
formatVersion
;
}
;
