#
include
"
nsIStreamConverter
.
idl
"
%
{
C
+
+
#
define
MOZ_TXTTOHTMLCONV_CONTRACTID
\
"
mozilla
.
org
/
txttohtmlconv
;
1
"
%
}
[
scriptable
uuid
(
77c0e42a
-
1dd2
-
11b2
-
8ebf
-
edc6606f2f4b
)
]
interface
mozITXTToHTMLConv
:
nsIStreamConverter
{
const
unsigned
long
kEntities
=
0
;
const
unsigned
long
kURLs
=
1
<
<
1
;
const
unsigned
long
kGlyphSubstitution
=
1
<
<
2
;
const
unsigned
long
kStructPhrase
=
1
<
<
3
;
AString
scanTXT
(
in
AString
text
in
unsigned
long
whattodo
)
;
AString
scanHTML
(
in
AString
text
in
unsigned
long
whattodo
)
;
unsigned
long
citeLevelTXT
(
in
wstring
line
out
unsigned
long
logLineStart
)
;
void
findURLInPlaintext
(
in
wstring
text
in
long
aLength
in
long
aPos
out
long
aStartPos
out
long
aEndPos
)
;
}
;
