#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
23bbabd0
-
1dd2
-
11b2
-
86b7
-
aad68ae7d7e0
)
]
interface
nsIDirIndex
:
nsISupports
{
const
unsigned
long
TYPE_UNKNOWN
=
0
;
const
unsigned
long
TYPE_DIRECTORY
=
1
;
const
unsigned
long
TYPE_FILE
=
2
;
const
unsigned
long
TYPE_SYMLINK
=
3
;
attribute
unsigned
long
type
;
attribute
ACString
location
;
attribute
long
long
size
;
attribute
PRTime
lastModified
;
}
;
