#
include
"
nsIStreamListener
.
idl
"
interface
nsIDirIndex
;
[
scriptable
uuid
(
fae4e9a8
-
1dd1
-
11b2
-
b53c
-
8f3aa1bbf8f5
)
]
interface
nsIDirIndexListener
:
nsISupports
{
void
onIndexAvailable
(
in
nsIRequest
aRequest
in
nsIDirIndex
aIndex
)
;
}
;
[
scriptable
uuid
(
38e3066c
-
1dd2
-
11b2
-
9b59
-
8be515c1ee3f
)
]
interface
nsIDirIndexParser
:
nsIStreamListener
{
attribute
nsIDirIndexListener
listener
;
}
;
