#
include
"
nsISupports
.
idl
"
[
scriptable
main_process_scriptable_only
uuid
(
a8d36901
-
0b6a
-
46c3
-
a214
-
a9e1d5d6047a
)
]
interface
nsIWinTaskSchedulerService
:
nsISupports
{
void
registerTask
(
in
wstring
aFolderName
in
wstring
aTaskName
in
wstring
aDefinitionXML
[
optional
]
in
boolean
aUpdateExisting
)
;
long
validateTaskDefinition
(
in
wstring
aDefinitionXML
)
;
AString
getTaskXML
(
in
wstring
aFolderName
in
wstring
aTaskName
)
;
void
deleteTask
(
in
wstring
aFolderName
in
wstring
aTaskName
)
;
Array
<
AString
>
getFolderTasks
(
in
wstring
aFolderName
)
;
void
createFolder
(
in
wstring
aParentFolderName
in
wstring
aSubFolderName
)
;
void
deleteFolder
(
in
wstring
aParentFolderName
in
wstring
aSubFolderName
)
;
}
;
