#
include
"
nsISupports
.
idl
"
interface
nsITransaction
;
interface
nsITransactionManager
;
[
scriptable
uuid
(
58e330c4
-
7b48
-
11d2
-
98b9
-
00805f297d89
)
]
interface
nsITransactionListener
:
nsISupports
{
void
didDo
(
in
nsITransactionManager
aManager
in
nsITransaction
aTransaction
in
nsresult
aDoResult
)
;
void
didUndo
(
in
nsITransactionManager
aManager
in
nsITransaction
aTransaction
in
nsresult
aUndoResult
)
;
void
didRedo
(
in
nsITransactionManager
aManager
in
nsITransaction
aTransaction
in
nsresult
aRedoResult
)
;
}
;
