#
include
"
nsISupports
.
idl
"
#
include
"
nsITransaction
.
idl
"
#
include
"
nsITransactionListener
.
idl
"
%
{
C
+
+
namespace
mozilla
{
class
TransactionManager
;
}
%
}
[
scriptable
builtinclass
uuid
(
c77763df
-
0fb9
-
41a8
-
8074
-
8e882f605755
)
]
interface
nsITransactionManager
:
nsISupports
{
void
doTransaction
(
in
nsITransaction
aTransaction
)
;
void
undoTransaction
(
)
;
void
redoTransaction
(
)
;
void
clear
(
)
;
void
clearUndoStack
(
)
;
void
clearRedoStack
(
)
;
void
beginBatch
(
in
nsISupports
aData
)
;
void
endBatch
(
in
boolean
aAllowEmpty
)
;
readonly
attribute
long
numberOfUndoItems
;
readonly
attribute
long
numberOfRedoItems
;
attribute
long
maxTransactionCount
;
void
batchTopUndo
(
)
;
void
removeTopUndo
(
)
;
nsITransaction
peekUndoStack
(
)
;
nsITransaction
peekRedoStack
(
)
;
void
AddListener
(
in
nsITransactionListener
aListener
)
;
void
RemoveListener
(
in
nsITransactionListener
aListener
)
;
%
{
C
+
+
inline
mozilla
:
:
TransactionManager
*
AsTransactionManager
(
)
;
%
}
}
;
