#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
58e330c1
-
7b48
-
11d2
-
98b9
-
00805f297d89
)
]
interface
nsITransaction
:
nsISupports
{
[
can_run_script
]
void
doTransaction
(
)
;
[
can_run_script
]
void
undoTransaction
(
)
;
[
can_run_script
]
void
redoTransaction
(
)
;
readonly
attribute
boolean
isTransient
;
boolean
merge
(
in
nsITransaction
aTransaction
)
;
}
;
