#
include
"
nsISupports
.
idl
"
interface
nsIURI
;
interface
nsIChannel
;
interface
nsILoadInfo
;
[
scriptable
uuid
(
c0c19db9
-
1b5a
-
4ac5
-
b656
-
ed6f8149fa48
)
]
interface
nsIAboutModule
:
nsISupports
{
nsIChannel
newChannel
(
in
nsIURI
aURI
in
nsILoadInfo
aLoadInfo
)
;
const
unsigned
long
URI_SAFE_FOR_UNTRUSTED_CONTENT
=
(
1
<
<
0
)
;
const
unsigned
long
ALLOW_SCRIPT
=
(
1
<
<
1
)
;
const
unsigned
long
HIDE_FROM_ABOUTABOUT
=
(
1
<
<
2
)
;
const
unsigned
long
ENABLE_INDEXED_DB
=
(
1
<
<
3
)
;
const
unsigned
long
URI_CAN_LOAD_IN_CHILD
=
(
1
<
<
4
)
;
const
unsigned
long
URI_MUST_LOAD_IN_CHILD
=
(
1
<
<
5
)
;
const
unsigned
long
MAKE_UNLINKABLE
=
(
1
<
<
6
)
;
const
unsigned
long
MAKE_LINKABLE
=
(
1
<
<
7
)
;
const
unsigned
long
URI_CAN_LOAD_IN_PRIVILEGEDABOUT_PROCESS
=
(
1
<
<
8
)
;
const
unsigned
long
URI_MUST_LOAD_IN_EXTENSION_PROCESS
=
(
1
<
<
9
)
;
const
unsigned
long
IS_SECURE_CHROME_UI
=
(
1
<
<
10
)
;
unsigned
long
getURIFlags
(
in
nsIURI
aURI
)
;
nsIURI
getChromeURI
(
in
nsIURI
aURI
)
;
}
;
%
{
C
+
+
#
define
NS_ABOUT_MODULE_CONTRACTID
"
mozilla
.
org
/
network
/
protocol
/
about
;
1
"
#
define
NS_ABOUT_MODULE_CONTRACTID_PREFIX
NS_ABOUT_MODULE_CONTRACTID
"
?
what
=
"
#
define
NS_ABOUT_MODULE_CONTRACTID_LENGTH
49
/
/
strlen
(
NS_ABOUT_MODULE_CONTRACTID_PREFIX
)
%
}
