#
include
"
nsISupports
.
idl
"
%
{
C
+
+
namespace
mozilla
{
namespace
net
{
class
HttpBackgroundChannelParent
;
class
HttpChannelParent
;
}
}
%
}
[
ptr
]
native
HttpChannelParent
(
mozilla
:
:
net
:
:
HttpChannelParent
)
;
[
ptr
]
native
HttpBackgroundChannelParent
(
mozilla
:
:
net
:
:
HttpBackgroundChannelParent
)
;
[
uuid
(
8acaa9b1
-
f0c4
-
4ade
-
baeb
-
39b0d4b96e5b
)
]
interface
nsIBackgroundChannelRegistrar
:
nsISupports
{
[
noscript
notxpcom
nostdcall
]
void
linkHttpChannel
(
in
uint64_t
aKey
in
HttpChannelParent
aChannel
)
;
[
noscript
notxpcom
nostdcall
]
void
linkBackgroundChannel
(
in
uint64_t
aKey
in
HttpBackgroundChannelParent
aBgChannel
)
;
[
noscript
notxpcom
nostdcall
]
void
deleteChannel
(
in
uint64_t
aKey
)
;
}
;
