#
include
"
nsISupports
.
idl
"
interface
nsIURI
;
interface
nsIPrincipal
;
[
ref
]
native
const_OriginAttributes
(
const
mozilla
:
:
OriginAttributes
)
;
[
builtinclass
scriptable
uuid
(
f43f2098
-
53dc
-
4554
-
b706
-
040b4ce1e587
)
]
interface
nsICORSPreflightCacheEntry
:
nsISupports
{
readonly
attribute
ACString
key
;
readonly
attribute
nsIURI
URI
;
[
implicit_jscontext
]
readonly
attribute
jsval
originAttributes
;
[
noscript
notxpcom
nostdcall
binaryname
(
OriginAttributesRef
)
]
const_OriginAttributes
OriginAttributesRef
(
)
;
readonly
attribute
nsIPrincipal
principal
;
readonly
attribute
boolean
privateBrowsing
;
readonly
attribute
boolean
withCredentials
;
}
;
