#
include
"
nsISupports
.
idl
"
#
include
"
nsIURI
.
idl
"
#
include
"
nsIPrincipal
.
idl
"
#
include
"
nsICORSPreflightCacheEntry
.
idl
"
[
builtinclass
scriptable
uuid
(
89781b3e
-
5cd5
-
4b63
-
a549
-
8d9ec3013505
)
]
interface
nsICORSPreflightCache
:
nsISupports
{
Array
<
nsICORSPreflightCacheEntry
>
getEntries
(
in
nsIPrincipal
principal
)
;
void
clearEntry
(
in
nsICORSPreflightCacheEntry
entry
)
;
}
;
