#
include
"
nsISupports
.
idl
"
native
ReferrerPolicy
(
mozilla
:
:
dom
:
:
ReferrerPolicy
)
;
[
scriptable
uuid
(
97b6be6f
-
283c
-
45dd
-
81a7
-
4bb2d87d42f8
)
]
interface
nsIEarlyHintObserver
:
nsISupports
{
void
earlyHint
(
in
ACString
linkHeader
in
ACString
referrerPolicy
)
;
}
;
