#
include
"
nsIProxiedChannel
.
idl
"
#
include
"
nsIRequest
.
idl
"
interface
nsILoadGroup
;
interface
nsIURI
;
interface
nsIInterfaceRequestor
;
[
uuid
(
701093ac
-
5c7f
-
429c
-
99e3
-
423b041fccb4
)
]
interface
nsIHttpAuthenticableChannel
:
nsIProxiedChannel
{
[
must_use
]
readonly
attribute
boolean
isSSL
;
[
must_use
]
readonly
attribute
boolean
proxyMethodIsConnect
;
[
must_use
]
void
cancel
(
in
nsresult
aStatus
)
;
[
must_use
]
readonly
attribute
nsLoadFlags
loadFlags
;
[
must_use
]
readonly
attribute
nsIURI
URI
;
[
must_use
]
readonly
attribute
nsILoadGroup
loadGroup
;
[
must_use
]
readonly
attribute
nsIInterfaceRequestor
notificationCallbacks
;
[
must_use
]
readonly
attribute
ACString
requestMethod
;
[
must_use
]
readonly
attribute
ACString
serverResponseHeader
;
[
must_use
]
readonly
attribute
ACString
proxyChallenges
;
[
must_use
]
readonly
attribute
ACString
WWWChallenges
;
[
must_use
]
void
setProxyCredentials
(
in
ACString
credentials
)
;
[
must_use
]
void
setWWWCredentials
(
in
ACString
credentials
)
;
[
must_use
]
void
onAuthAvailable
(
)
;
[
must_use
]
void
onAuthCancelled
(
in
boolean
userCancel
)
;
[
must_use
]
void
closeStickyConnection
(
)
;
void
connectionRestartable
(
in
boolean
restartable
)
;
}
;
