#
include
"
nsICancelable
.
idl
"
interface
nsIHttpChannel
;
interface
nsIHttpAuthenticableChannel
;
[
uuid
(
788f331b
-
2e1f
-
436c
-
b405
-
4f88a31a105b
)
]
interface
nsIHttpChannelAuthProvider
:
nsICancelable
{
[
must_use
]
void
init
(
in
nsIHttpAuthenticableChannel
channel
)
;
[
must_use
]
void
processAuthentication
(
in
unsigned
long
httpStatus
in
boolean
sslConnectFailed
)
;
[
must_use
]
void
addAuthorizationHeaders
(
in
boolean
dontUseCachedWWWCreds
)
;
[
must_use
]
void
disconnect
(
in
nsresult
status
)
;
void
clearProxyIdent
(
)
;
}
;
