#
include
"
nsISupports
.
idl
"
#
include
"
nsIHttpAuthEntry
.
idl
"
[
builtinclass
scriptable
uuid
(
6ef2115c
-
7c67
-
41de
-
8de3
-
f7d412660a03
)
]
interface
nsIHttpAuthCache
:
nsISupports
{
Array
<
nsIHttpAuthEntry
>
getEntries
(
)
;
void
clearEntry
(
in
nsIHttpAuthEntry
entry
)
;
}
;
