#
include
"
nsISupports
.
idl
"
interface
nsIPrincipal
;
[
scriptable
builtinclass
uuid
(
54f90444
-
c52b
-
4d2d
-
8916
-
c59a2bb25938
)
]
interface
nsIHttpAuthManager
:
nsISupports
{
[
must_use
]
void
getAuthIdentity
(
in
ACString
aScheme
in
ACString
aHost
in
int32_t
aPort
in
ACString
aAuthType
in
ACString
aRealm
in
ACString
aPath
out
AString
aUserDomain
out
AString
aUserName
out
AString
aUserPassword
[
optional
]
in
boolean
aIsPrivate
[
optional
]
in
nsIPrincipal
aPrincipal
)
;
[
must_use
]
void
setAuthIdentity
(
in
ACString
aScheme
in
ACString
aHost
in
int32_t
aPort
in
ACString
aAuthType
in
ACString
aRealm
in
ACString
aPath
in
AString
aUserDomain
in
AString
aUserName
in
AString
aUserPassword
[
optional
]
in
boolean
aIsPrivate
[
optional
]
in
nsIPrincipal
aPrincipal
)
;
[
must_use
]
void
clearAll
(
)
;
}
;
