#
include
"
nsISupports
.
idl
"
[
scriptable
function
uuid
(
35412859
-
b9d9
-
423c
-
8866
-
2d4559fdd2be
)
]
interface
nsIHttpHeaderVisitor
:
nsISupports
{
[
must_use
]
void
visitHeader
(
in
ACString
aHeader
in
ACString
aValue
)
;
}
;
