#
include
"
nsIProxiedProtocolHandler
.
idl
"
%
{
C
+
+
namespace
mozilla
{
namespace
net
{
class
HSTSDataCallbackWrapper
;
}
}
%
}
native
HSTSDataCallbackWrapperAlreadyAddRefed
(
RefPtr
<
mozilla
:
:
net
:
:
HSTSDataCallbackWrapper
>
)
;
[
scriptable
builtinclass
uuid
(
c48126d9
-
2ddd
-
485b
-
a51a
-
378e917e75f8
)
]
interface
nsIHttpProtocolHandler
:
nsIProxiedProtocolHandler
{
[
must_use
]
readonly
attribute
ACString
userAgent
;
[
must_use
]
readonly
attribute
ACString
rfpUserAgent
;
[
must_use
]
readonly
attribute
ACString
appName
;
[
must_use
]
readonly
attribute
ACString
appVersion
;
[
must_use
]
readonly
attribute
ACString
platform
;
[
must_use
]
readonly
attribute
ACString
oscpu
;
[
must_use
]
readonly
attribute
ACString
misc
;
[
must_use
]
readonly
attribute
Array
<
ACString
>
altSvcCacheKeys
;
[
must_use
]
readonly
attribute
Array
<
ACString
>
authCacheKeys
;
[
implicit_jscontext
]
Promise
EnsureHSTSDataReady
(
)
;
[
noscript
]
void
EnsureHSTSDataReadyNative
(
in
HSTSDataCallbackWrapperAlreadyAddRefed
aCallback
)
;
void
clearCORSPreflightCache
(
)
;
}
;
%
{
C
+
+
#
define
NS_HTTP_STARTUP_CATEGORY
"
http
-
startup
-
category
"
#
define
NS_HTTP_STARTUP_TOPIC
"
http
-
startup
"
#
define
NS_HTTP_ON_FAILED_OPENING_REQUEST_TOPIC
"
http
-
on
-
failed
-
opening
-
request
"
#
define
NS_HTTP_ON_OPENING_REQUEST_TOPIC
"
http
-
on
-
opening
-
request
"
#
define
NS_DOCUMENT_ON_OPENING_REQUEST_TOPIC
"
document
-
on
-
opening
-
request
"
#
define
NS_HTTP_ON_MODIFY_REQUEST_TOPIC
"
http
-
on
-
modify
-
request
"
#
define
NS_HTTP_ON_MODIFY_REQUEST_BEFORE_COOKIES_TOPIC
"
http
-
on
-
modify
-
request
-
before
-
cookies
"
#
define
NS_DOCUMENT_ON_MODIFY_REQUEST_TOPIC
"
document
-
on
-
modify
-
request
"
#
define
NS_HTTP_ON_BEFORE_CONNECT_TOPIC
"
http
-
on
-
before
-
connect
"
#
define
NS_HTTP_ON_EXAMINE_RESPONSE_TOPIC
"
http
-
on
-
examine
-
response
"
#
define
NS_HTTP_ON_EXAMINE_MERGED_RESPONSE_TOPIC
"
http
-
on
-
examine
-
merged
-
response
"
#
define
NS_HTTP_ON_BACKGROUND_REVALIDATION
"
http
-
on
-
background
-
revalidation
"
#
define
NS_HTTP_ON_EXAMINE_CACHED_RESPONSE_TOPIC
"
http
-
on
-
examine
-
cached
-
response
"
#
define
NS_HTTP_ON_STOP_REQUEST_TOPIC
"
http
-
on
-
stop
-
request
"
%
}
