#
include
"
nsISupports
.
idl
"
#
include
"
nsILoadInfo
.
idl
"
#
include
"
nsIReplacedHttpResponse
.
idl
"
#
include
"
nsIRequest
.
idl
"
#
include
"
nsITRRSkipReason
.
idl
"
%
{
C
+
+
#
include
"
nsStringFwd
.
h
"
#
include
"
nsTArrayForwardDeclare
.
h
"
template
<
class
T
>
class
nsCOMArray
;
namespace
mozilla
{
class
TimeStamp
;
namespace
net
{
class
nsHttpConnectionInfo
;
class
WebSocketConnectionBase
;
class
EarlyHintConnectArgs
;
}
namespace
dom
{
enum
class
RequestMode
:
uint8_t
;
}
}
%
}
[
ptr
]
native
nsHttpConnectionInfo
(
mozilla
:
:
net
:
:
nsHttpConnectionInfo
)
;
[
ptr
]
native
StringArray
(
nsTArray
<
nsCString
>
)
;
[
ref
]
native
CStringArrayRef
(
const
nsTArray
<
nsCString
>
)
;
[
ref
]
native
securityMessagesArray
(
nsCOMArray
<
nsISecurityConsoleMessage
>
)
;
[
ptr
]
native
WebSocketConnectionBase
(
mozilla
:
:
net
:
:
WebSocketConnectionBase
)
;
native
TimeStamp
(
mozilla
:
:
TimeStamp
)
;
native
RequestMode
(
mozilla
:
:
dom
:
:
RequestMode
)
;
interface
nsIAsyncInputStream
;
interface
nsIAsyncOutputStream
;
interface
nsIEarlyHintObserver
;
interface
nsIPrincipal
;
interface
nsIProxyInfo
;
interface
nsISecurityConsoleMessage
;
interface
nsISocketTransport
;
interface
nsIURI
;
interface
WebTransportSessionEventListener
;
[
scriptable
uuid
(
5b515449
-
ab64
-
4dba
-
b3cd
-
da8fc2f83064
)
]
interface
nsIHttpUpgradeListener
:
nsISupports
{
[
must_use
]
void
onTransportAvailable
(
in
nsISocketTransport
aTransport
in
nsIAsyncInputStream
aSocketIn
in
nsIAsyncOutputStream
aSocketOut
)
;
[
must_use
]
void
onUpgradeFailed
(
in
nsresult
aErrorCode
)
;
[
noscript
]
void
onWebSocketConnectionAvailable
(
in
WebSocketConnectionBase
aConnection
)
;
}
;
[
builtinclass
scriptable
uuid
(
4e28263d
-
1e03
-
46f4
-
aa5c
-
9512f91957f9
)
]
interface
nsIHttpChannelInternal
:
nsISupports
{
[
must_use
]
attribute
nsIURI
documentURI
;
[
must_use
]
void
getRequestVersion
(
out
unsigned
long
major
out
unsigned
long
minor
)
;
[
must_use
]
void
getResponseVersion
(
out
unsigned
long
major
out
unsigned
long
minor
)
;
[
noscript
must_use
]
void
takeAllSecurityMessages
(
in
securityMessagesArray
aMessages
)
;
[
must_use
]
void
setCookie
(
in
ACString
aCookieHeader
)
;
[
noscript
must_use
]
readonly
attribute
boolean
isAuthChannel
;
const
unsigned
long
THIRD_PARTY_FORCE_ALLOW
=
1
<
<
0
;
[
must_use
]
attribute
unsigned
long
thirdPartyFlags
;
[
must_use
]
attribute
boolean
forceAllowThirdPartyCookie
;
[
must_use
]
attribute
boolean
channelIsForDownload
;
[
must_use
]
readonly
attribute
AUTF8String
localAddress
;
[
must_use
]
readonly
attribute
int32_t
localPort
;
[
must_use
]
readonly
attribute
AUTF8String
remoteAddress
;
[
must_use
]
readonly
attribute
int32_t
remotePort
;
[
noscript
must_use
]
void
setCacheKeysRedirectChain
(
in
StringArray
cacheKeys
)
;
[
must_use
]
void
HTTPUpgrade
(
in
ACString
aProtocolName
in
nsIHttpUpgradeListener
aListener
)
;
[
must_use
]
void
setConnectOnly
(
in
boolean
tlsTunnel
)
;
[
must_use
]
readonly
attribute
boolean
onlyConnect
;
[
must_use
]
attribute
boolean
allowSpdy
;
[
must_use
]
attribute
boolean
allowHttp3
;
[
must_use
]
attribute
boolean
responseTimeoutEnabled
;
[
must_use
]
attribute
unsigned
long
initialRwin
;
[
must_use
]
readonly
attribute
nsIURI
apiRedirectToURI
;
[
must_use
]
attribute
boolean
allowAltSvc
;
[
must_use
]
attribute
boolean
beConservative
;
[
must_use
]
attribute
boolean
bypassProxy
;
[
noscript
must_use
]
attribute
boolean
isTRRServiceChannel
;
[
must_use
]
readonly
attribute
boolean
isResolvedByTRR
;
[
must_use
]
readonly
attribute
nsIRequest_TRRMode
effectiveTRRMode
;
[
must_use
]
readonly
attribute
nsITRRSkipReason_value
trrSkipReason
;
[
must_use
]
readonly
attribute
boolean
isLoadedBySocketProcess
;
[
must_use
]
attribute
boolean
isOCSP
;
const
unsigned
long
TLS_FLAG_CONFIGURE_AS_RETRY
=
(
1
<
<
16
)
;
[
must_use
]
attribute
unsigned
long
tlsFlags
;
[
must_use
]
readonly
attribute
PRTime
lastModifiedTime
;
[
must_use
]
attribute
boolean
corsIncludeCredentials
;
[
must_use
noscript
]
attribute
RequestMode
requestMode
;
const
unsigned
long
REDIRECT_MODE_FOLLOW
=
0
;
const
unsigned
long
REDIRECT_MODE_ERROR
=
1
;
const
unsigned
long
REDIRECT_MODE_MANUAL
=
2
;
[
must_use
]
attribute
unsigned
long
redirectMode
;
const
unsigned
long
FETCH_CACHE_MODE_DEFAULT
=
0
;
const
unsigned
long
FETCH_CACHE_MODE_NO_STORE
=
1
;
const
unsigned
long
FETCH_CACHE_MODE_RELOAD
=
2
;
const
unsigned
long
FETCH_CACHE_MODE_NO_CACHE
=
3
;
const
unsigned
long
FETCH_CACHE_MODE_FORCE_CACHE
=
4
;
const
unsigned
long
FETCH_CACHE_MODE_ONLY_IF_CACHED
=
5
;
[
must_use
]
attribute
unsigned
long
fetchCacheMode
;
[
must_use
]
readonly
attribute
nsIURI
topWindowURI
;
[
must_use
]
void
setTopWindowURIIfUnknown
(
in
nsIURI
topWindowURI
)
;
[
must_use
]
readonly
attribute
nsIURI
proxyURI
;
[
noscript
notxpcom
nostdcall
]
void
setCorsPreflightParameters
(
in
CStringArrayRef
unsafeHeaders
in
boolean
shouldStripRequestBodyHeader
in
boolean
shouldStripAuthHeader
)
;
[
noscript
notxpcom
nostdcall
]
void
setAltDataForChild
(
in
boolean
aIsForChild
)
;
[
noscript
notxpcom
nostdcall
]
void
disableAltDataCache
(
)
;
[
infallible
]
attribute
boolean
blockAuthPrompt
;
[
must_use
]
attribute
AString
integrityMetadata
;
[
must_use
]
readonly
attribute
ACString
connectionInfoHashKey
;
[
noscript
infallible
]
attribute
unsigned
long
lastRedirectFlags
;
[
noscript
]
attribute
TimeStamp
navigationStartTimeStamp
;
[
noscript
]
void
cancelByURLClassifier
(
in
nsresult
aErrorCode
)
;
void
setIPv4Disabled
(
)
;
void
setIPv6Disabled
(
)
;
readonly
attribute
nsILoadInfo_CrossOriginOpenerPolicy
crossOriginOpenerPolicy
;
[
noscript
]
nsILoadInfo_CrossOriginOpenerPolicy
computeCrossOriginOpenerPolicy
(
in
nsILoadInfo_CrossOriginOpenerPolicy
aInitiatorPolicy
)
;
[
noscript
]
boolean
hasCrossOriginOpenerPolicyMismatch
(
)
;
[
noscript
]
nsILoadInfo_CrossOriginEmbedderPolicy
getResponseEmbedderPolicy
(
in
boolean
aIsOriginTrialCoepCredentiallessEnabled
)
;
[
noscript
notxpcom
nostdcall
]
void
DoDiagnosticAssertWhenOnStopNotCalledOnDestroy
(
)
;
[
must_use
]
readonly
attribute
boolean
supportsHTTP3
;
[
must_use
]
readonly
attribute
boolean
hasHTTPSRR
;
[
must_use
]
void
setEarlyHintObserver
(
in
nsIEarlyHintObserver
aObserver
)
;
[
must_use
]
attribute
unsigned
long
long
earlyHintPreloaderId
;
[
notxpcom
nostdcall
]
void
setConnectionInfo
(
in
nsHttpConnectionInfo
aInfo
)
;
[
must_use
]
readonly
attribute
boolean
isProxyUsed
;
[
must_use
]
void
setWebTransportSessionEventListener
(
in
WebTransportSessionEventListener
aListener
)
;
[
must_use
]
attribute
unsigned
long
earlyHintLinkType
;
[
must_use
]
attribute
boolean
isUserAgentHeaderModified
;
[
must_use
]
void
setResponseOverride
(
in
nsIReplacedHttpResponse
aReplacedHttpResponse
)
;
readonly
attribute
nsresult
lastTransportStatus
;
}
;
