#
include
"
nsISupports
.
idl
"
interface
nsIHttpChannel
;
[
scriptable
uuid
(
391ba410
-
0a68
-
42f7
-
b3e4
-
3ec26db645c0
)
]
interface
nsINetworkErrorLogging
:
nsISupports
{
void
registerPolicy
(
in
nsIHttpChannel
aChannel
)
;
void
generateNELReport
(
in
nsIHttpChannel
aChannel
)
;
}
;
