#
include
"
nsIHttpChannel
.
idl
"
[
builtinclass
scriptable
uuid
(
f829f761
-
0744
-
4d1c
-
9c2d
-
8931c22ae8d5
)
]
interface
nsIObliviousHttpChannel
:
nsIHttpChannel
{
readonly
attribute
nsIHttpChannel
relayChannel
;
}
;
