#
include
"
nsISupports
.
idl
"
%
{
C
+
+
#
define
NS_WELLKNOWNOPPORTUNISTICUTILS_CONTRACTID
"
mozilla
.
org
/
network
/
well
-
known
-
opportunistic
-
utils
;
1
"
%
}
[
scriptable
uuid
(
b4f96c89
-
5238
-
450c
-
8bda
-
e12c26f1d150
)
]
interface
nsIWellKnownOpportunisticUtils
:
nsISupports
{
[
must_use
]
void
verify
(
in
ACString
aJSON
in
ACString
aOrigin
)
;
[
must_use
]
readonly
attribute
boolean
valid
;
}
;
