#
include
"
nsIRunnable
.
idl
"
%
{
C
+
+
#
include
"
mozilla
/
AlreadyAddRefed
.
h
"
%
}
native
alreadyAddRefed_nsIRunnable
(
already_AddRefed
<
nsIRunnable
>
)
;
[
uuid
(
e05bf0fe
-
94b7
-
4e28
-
8462
-
a8368da9c136
)
]
interface
nsIDirectTaskDispatcher
:
nsISupports
{
[
noscript
]
void
dispatchDirectTask
(
in
alreadyAddRefed_nsIRunnable
event
)
;
[
noscript
]
void
drainDirectTasks
(
)
;
[
noscript
]
boolean
haveDirectTasks
(
)
;
%
{
C
+
+
bool
HaveDirectTasks
(
)
{
bool
value
=
false
;
MOZ_ALWAYS_SUCCEEDS
(
HaveDirectTasks
(
&
value
)
)
;
return
value
;
}
%
}
}
;
