#
include
"
nsISupports
.
idl
"
#
include
"
nsIRunnable
.
idl
"
%
{
C
+
+
#
include
"
nsCOMPtr
.
h
"
#
include
"
mozilla
/
AlreadyAddRefed
.
h
"
#
include
"
mozilla
/
Atomics
.
h
"
class
nsITargetShutdownTask
;
%
}
native
alreadyAddRefed_nsIRunnable
(
already_AddRefed
<
nsIRunnable
>
)
;
[
ptr
]
native
nsITargetShutdownTask
(
nsITargetShutdownTask
)
;
[
builtinclass
scriptable
uuid
(
a03b8b63
-
af8b
-
4164
-
b0e5
-
c41e8b2b7cfa
)
]
interface
nsIEventTarget
:
nsISupports
{
%
{
C
+
+
nsresult
Dispatch
(
nsIRunnable
*
aEvent
uint32_t
aFlags
)
{
return
Dispatch
(
nsCOMPtr
<
nsIRunnable
>
(
aEvent
)
.
forget
(
)
aFlags
)
;
}
%
}
const
unsigned
long
DISPATCH_NORMAL
=
0
;
const
unsigned
long
DISPATCH_SYNC
=
1
;
const
unsigned
long
DISPATCH_AT_END
=
2
;
const
unsigned
long
DISPATCH_EVENT_MAY_BLOCK
=
4
;
%
{
C
+
+
public
:
bool
IsOnCurrentThread
(
)
;
protected
:
mozilla
:
:
Atomic
<
PRThread
*
>
mThread
;
nsIEventTarget
(
)
:
mThread
(
nullptr
)
{
}
%
}
[
noscript
notxpcom
]
boolean
isOnCurrentThreadInfallible
(
)
;
%
{
C
+
+
public
:
%
}
boolean
isOnCurrentThread
(
)
;
[
noscript
binaryname
(
Dispatch
)
]
void
dispatchFromC
(
in
alreadyAddRefed_nsIRunnable
event
[
default
(
DISPATCH_NORMAL
)
]
in
unsigned
long
flags
)
;
[
binaryname
(
DispatchFromScript
)
]
void
dispatch
(
in
nsIRunnable
event
in
unsigned
long
flags
)
;
[
noscript
]
void
delayedDispatch
(
in
alreadyAddRefed_nsIRunnable
event
in
unsigned
long
delay
)
;
[
noscript
]
void
registerShutdownTask
(
in
nsITargetShutdownTask
task
)
;
[
noscript
]
void
unregisterShutdownTask
(
in
nsITargetShutdownTask
task
)
;
}
;
%
{
C
+
+
#
define
NS_DISPATCH_NORMAL
nsIEventTarget
:
:
DISPATCH_NORMAL
#
define
NS_DISPATCH_SYNC
nsIEventTarget
:
:
DISPATCH_SYNC
#
define
NS_DISPATCH_AT_END
nsIEventTarget
:
:
DISPATCH_AT_END
#
define
NS_DISPATCH_EVENT_MAY_BLOCK
nsIEventTarget
:
:
DISPATCH_EVENT_MAY_BLOCK
#
define
NS_DECL_NSIEVENTTARGET_FULL
\
NS_DECL_NSIEVENTTARGET
\
/
*
Avoid
hiding
these
methods
*
/
\
using
nsIEventTarget
:
:
Dispatch
;
\
using
nsIEventTarget
:
:
IsOnCurrentThread
;
%
}
