#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
101d5941
-
d820
-
4e85
-
a266
-
9a3469940807
)
]
interface
nsIEnvironment
:
nsISupports
{
void
set
(
in
AString
aName
in
AString
aValue
)
;
AString
get
(
in
AString
aName
)
;
boolean
exists
(
in
AString
aName
)
;
}
;
