#
include
"
nsISupports
.
idl
"
%
{
C
+
+
namespace
mozilla
{
class
TimeStamp
;
}
%
}
native
TimeStamp
(
mozilla
:
:
TimeStamp
)
;
[
uuid
(
21dd35a2
-
eae9
-
4bd8
-
b470
-
0dfa35a0e3b9
)
]
interface
nsIIdlePeriod
:
nsISupports
{
TimeStamp
getIdlePeriodHint
(
)
;
}
;
