#
include
"
nsISupports
.
idl
"
interface
nsIRunnable
;
[
scriptable
builtinclass
uuid
(
70a43748
-
6130
-
4ea6
-
a440
-
7c74e1b7dd7c
)
]
interface
nsIThreadShutdown
:
nsISupports
{
void
onCompletion
(
in
nsIRunnable
aEvent
)
;
[
infallible
]
readonly
attribute
boolean
completed
;
void
stopWaitingAndLeakThread
(
)
;
}
;
