#
include
"
nsIEventTarget
.
idl
"
#
include
"
nsIThread
.
idl
"
[
uuid
(
ef194cab
-
3f86
-
4b61
-
b132
-
e5e96a79e5d1
)
]
interface
nsIThreadPoolListener
:
nsISupports
{
void
onThreadCreated
(
)
;
void
onThreadShuttingDown
(
)
;
}
;
[
rust_sync
uuid
(
76ce99c9
-
8e43
-
489a
-
9789
-
f27cc4424965
)
]
interface
nsIThreadPool
:
nsIEventTarget
{
[
noscript
]
void
setQoSForThreads
(
in
nsIThread_QoSPriority
aPriority
)
;
void
shutdown
(
)
;
[
noscript
]
void
shutdownWithTimeout
(
in
long
aTimeoutMs
)
;
attribute
unsigned
long
threadLimit
;
attribute
unsigned
long
idleThreadLimit
;
attribute
unsigned
long
idleThreadGraceTimeout
;
attribute
unsigned
long
idleThreadMaximumTimeout
;
attribute
unsigned
long
threadStackSize
;
attribute
nsIThreadPoolListener
listener
;
void
setName
(
in
ACString
aName
)
;
}
;
