#
include
"
nsIThread
.
idl
"
interface
nsIRunnable
;
interface
nsIThreadObserver
;
[
builtinclass
scriptable
rust_sync
uuid
(
a3a72e5f
-
71d9
-
4add
-
8f30
-
59a78fb6d5eb
)
]
interface
nsIThreadInternal
:
nsIThread
{
attribute
nsIThreadObserver
observer
;
void
addObserver
(
in
nsIThreadObserver
observer
)
;
void
removeObserver
(
in
nsIThreadObserver
observer
)
;
}
;
[
uuid
(
cc8da053
-
1776
-
44c2
-
9199
-
b5a629d0a19d
)
]
interface
nsIThreadObserver
:
nsISupports
{
void
onDispatchedEvent
(
)
;
void
onProcessNextEvent
(
in
nsIThreadInternal
thread
in
boolean
mayWait
)
;
void
afterProcessNextEvent
(
in
nsIThreadInternal
thread
in
boolean
eventWasProcessed
)
;
}
;
