#
include
"
nsIInputStream
.
idl
"
[
scriptable
uuid
(
3014dde6
-
aa1c
-
41db
-
87d0
-
48764a3710f6
)
]
interface
nsIArrayBufferInputStream
:
nsIInputStream
{
void
setData
(
in
jsval
buffer
in
uint64_t
byteOffset
in
uint64_t
byteLen
)
;
}
;
