#
include
"
nsISupports
.
idl
"
interface
nsIPrompt
;
[
scriptable
uuid
(
358089f9
-
ee4b
-
4711
-
82fd
-
bcd07fc62061
)
]
interface
nsIAuthPrompt
:
nsISupports
{
const
uint32_t
SAVE_PASSWORD_NEVER
=
0
;
const
uint32_t
SAVE_PASSWORD_FOR_SESSION
=
1
;
const
uint32_t
SAVE_PASSWORD_PERMANENTLY
=
2
;
boolean
prompt
(
in
wstring
dialogTitle
in
wstring
text
in
wstring
passwordRealm
in
uint32_t
savePassword
in
wstring
defaultText
out
wstring
result
)
;
boolean
promptUsernameAndPassword
(
in
wstring
dialogTitle
in
wstring
text
in
wstring
passwordRealm
in
uint32_t
savePassword
inout
wstring
user
inout
wstring
pwd
)
;
Promise
asyncPromptUsernameAndPassword
(
in
wstring
dialogTitle
in
wstring
text
in
wstring
passwordRealm
in
uint32_t
savePassword
inout
wstring
user
inout
wstring
pwd
)
;
boolean
promptPassword
(
in
wstring
dialogTitle
in
wstring
text
in
wstring
passwordRealm
in
uint32_t
savePassword
inout
wstring
pwd
)
;
Promise
asyncPromptPassword
(
in
wstring
dialogTitle
in
wstring
text
in
wstring
passwordRealm
in
uint32_t
savePassword
inout
wstring
pwd
)
;
}
;
