#
include
"
nsIInputStream
.
idl
"
interface
nsIURI
;
[
scriptable
builtinclass
uuid
(
6187e14f
-
a137
-
486c
-
9c31
-
8eefe645f26b
)
]
interface
nsIAndroidContentInputStream
:
nsIInputStream
{
void
init
(
in
nsIURI
uri
)
;
}
;
