#
include
"
nsISupports
.
idl
"
interface
nsIArray
;
interface
nsIBackgroundFileSaverObserver
;
interface
nsIFile
;
[
scriptable
uuid
(
c43544a4
-
682c
-
4262
-
b407
-
2453d26e660d
)
]
interface
nsIBackgroundFileSaver
:
nsISupports
{
attribute
nsIBackgroundFileSaverObserver
observer
;
readonly
attribute
Array
<
Array
<
Array
<
uint8_t
>
>
>
signatureInfo
;
readonly
attribute
ACString
sha256Hash
;
void
enableSignatureInfo
(
)
;
void
enableSha256
(
)
;
void
enableAppend
(
)
;
void
setTarget
(
in
nsIFile
aTarget
in
boolean
aKeepPartial
)
;
void
finish
(
in
nsresult
aStatus
)
;
}
;
[
scriptable
uuid
(
ee7058c3
-
6e54
-
4411
-
b76b
-
3ce87b76fcb6
)
]
interface
nsIBackgroundFileSaverObserver
:
nsISupports
{
void
onTargetChange
(
in
nsIBackgroundFileSaver
aSaver
in
nsIFile
aTarget
)
;
void
onSaveComplete
(
in
nsIBackgroundFileSaver
aSaver
in
nsresult
aStatus
)
;
}
;
