#
include
"
nsISupports
.
idl
"
%
{
C
+
+
namespace
mozilla
{
namespace
net
{
class
ADivertableParentChannel
;
}
}
%
}
[
ptr
]
native
ADivertableParentChannelPtr
(
mozilla
:
:
net
:
:
ADivertableParentChannel
)
;
[
uuid
(
c073d79f
-
2503
-
4dff
-
ba87
-
d3071f8b433b
)
]
interface
nsIChannelWithDivertableParentListener
:
nsISupports
{
void
MessageDiversionStarted
(
in
ADivertableParentChannelPtr
aParentChannel
)
;
void
MessageDiversionStop
(
)
;
void
SuspendInternal
(
)
;
void
ResumeInternal
(
)
;
}
;
