#
include
"
nsICacheInfoChannel
.
idl
"
interface
nsIFile
;
[
scriptable
builtinclass
uuid
(
dd1d6122
-
5ecf
-
4fe4
-
8f0f
-
995e7ab3121a
)
]
interface
nsICachingChannel
:
nsICacheInfoChannel
{
attribute
nsISupports
cacheToken
;
attribute
boolean
cacheOnlyMetadata
;
attribute
boolean
pin
;
void
forceCacheEntryValidFor
(
in
unsigned
long
aSecondsToTheFuture
)
;
const
unsigned
long
LOAD_NO_NETWORK_IO
=
1
<
<
26
;
const
unsigned
long
LOAD_CHECK_OFFLINE_CACHE
=
1
<
<
27
;
const
unsigned
long
LOAD_BYPASS_LOCAL_CACHE
=
1
<
<
28
;
const
unsigned
long
LOAD_BYPASS_LOCAL_CACHE_IF_BUSY
=
1
<
<
29
;
const
unsigned
long
LOAD_ONLY_FROM_CACHE
=
1
<
<
30
;
const
unsigned
long
LOAD_ONLY_IF_MODIFIED
=
1
<
<
31
;
}
;
