#
include
"
nsISupports
.
idl
"
interface
nsIUTF8StringEnumerator
;
interface
nsIStreamListener
;
interface
nsISupports
;
[
scriptable
uuid
(
29c29ce6
-
8ce4
-
45e6
-
8d60
-
36c8fa3e255b
)
]
interface
nsIEncodedChannel
:
nsISupports
{
readonly
attribute
nsIUTF8StringEnumerator
contentEncodings
;
attribute
boolean
applyConversion
;
attribute
boolean
hasContentDecompressed
;
void
doApplyContentConversions
(
in
nsIStreamListener
aNextListener
out
nsIStreamListener
aNewNextListener
in
nsISupports
aCtxt
)
;
}
;
