#
include
"
nsIRequest
.
idl
"
interface
nsIURI
;
interface
nsIFile
;
interface
nsIRequestObserver
;
[
scriptable
uuid
(
6687823f
-
56c4
-
461d
-
93a1
-
7f6cb7dfbfba
)
]
interface
nsIIncrementalDownload
:
nsIRequest
{
void
init
(
in
nsIURI
uri
in
nsIFile
destination
in
long
chunkSize
in
long
intervalInSeconds
in
ACString
extraHeaders
)
;
readonly
attribute
nsIURI
URI
;
readonly
attribute
nsIURI
finalURI
;
readonly
attribute
nsIFile
destination
;
readonly
attribute
long
long
totalSize
;
readonly
attribute
long
long
currentSize
;
void
start
(
in
nsIRequestObserver
observer
in
nsISupports
ctxt
)
;
}
;
