#
include
"
nsIStreamListener
.
idl
"
interface
nsIRequest
;
interface
nsIIncrementalStreamLoader
;
[
scriptable
uuid
(
07c3d2cc
-
5454
-
4618
-
9f4f
-
cd93de9504a4
)
]
interface
nsIIncrementalStreamLoaderObserver
:
nsISupports
{
void
onIncrementalData
(
in
nsIIncrementalStreamLoader
loader
in
nsISupports
ctxt
in
unsigned
long
dataLength
[
const
array
size_is
(
dataLength
)
]
in
octet
data
inout
unsigned
long
consumedLength
)
;
void
onStreamComplete
(
in
nsIIncrementalStreamLoader
loader
in
nsISupports
ctxt
in
nsresult
status
in
unsigned
long
resultLength
[
const
array
size_is
(
resultLength
)
]
in
octet
result
)
;
}
;
[
scriptable
uuid
(
a023b060
-
ba23
-
431a
-
b449
-
2dd63e220554
)
]
interface
nsIIncrementalStreamLoader
:
nsIStreamListener
{
void
init
(
in
nsIIncrementalStreamLoaderObserver
aObserver
)
;
readonly
attribute
unsigned
long
numBytesRead
;
readonly
attribute
nsIRequest
request
;
}
;
