#
include
"
nsIRequest
.
idl
"
interface
nsISimpleEnumerator
;
interface
nsIRequestObserver
;
interface
nsIInterfaceRequestor
;
interface
nsIRequestContext
;
[
builtinclass
scriptable
uuid
(
f0c87725
-
7a35
-
463c
-
9ceb
-
2c07f23406cc
)
]
interface
nsILoadGroup
:
nsIRequest
{
attribute
nsIRequestObserver
groupObserver
;
attribute
nsIRequest
defaultLoadRequest
;
void
addRequest
(
in
nsIRequest
aRequest
in
nsISupports
aContext
)
;
void
removeRequest
(
in
nsIRequest
aRequest
in
nsISupports
aContext
in
nsresult
aStatus
)
;
readonly
attribute
nsISimpleEnumerator
requests
;
attribute
unsigned
long
long
totalKeepAliveBytes
;
readonly
attribute
unsigned
long
activeCount
;
attribute
nsIInterfaceRequestor
notificationCallbacks
;
readonly
attribute
unsigned
long
long
requestContextID
;
attribute
nsLoadFlags
defaultLoadFlags
;
[
infallible
]
readonly
attribute
boolean
isBrowsingContextDiscarded
;
}
;
