#
include
"
nsISupports
.
idl
"
interface
nsILoadGroup
;
[
builtinclass
scriptable
uuid
(
02efe8e2
-
fbbc
-
4718
-
a299
-
b8a09c60bf6b
)
]
interface
nsILoadGroupChild
:
nsISupports
{
attribute
nsILoadGroup
parentLoadGroup
;
readonly
attribute
nsILoadGroup
childLoadGroup
;
readonly
attribute
nsILoadGroup
rootLoadGroup
;
}
;
