#
include
"
nsISupports
.
idl
"
interface
nsIChannel
;
[
scriptable
builtinclass
uuid
(
4fefb490
-
5567
-
11e5
-
a837
-
0800200c9a66
)
]
interface
nsIMultiPartChannel
:
nsISupports
{
readonly
attribute
nsIChannel
baseChannel
;
readonly
attribute
uint32_t
partID
;
[
noscript
]
readonly
attribute
boolean
isFirstPart
;
readonly
attribute
boolean
isLastPart
;
}
;
[
scriptable
uuid
(
b084959a
-
4fb9
-
41a5
-
88a0
-
d0f045ce75cf
)
]
interface
nsIMultiPartChannelListener
:
nsISupports
{
void
onAfterLastPart
(
in
nsresult
status
)
;
}
;
