#
include
"
nsIHttpHeaderVisitor
.
idl
"
#
include
"
nsIInputStream
.
idl
"
[
scriptable
builtinclass
uuid
(
dcbce63c
-
1dd1
-
11b2
-
b94d
-
91f6d49a3161
)
]
interface
nsIMIMEInputStream
:
nsIInputStream
{
void
addHeader
(
in
string
name
in
string
value
)
;
void
visitHeaders
(
in
nsIHttpHeaderVisitor
visitor
)
;
void
setData
(
in
nsIInputStream
stream
)
;
readonly
attribute
nsIInputStream
data
;
}
;
