#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
63fff172
-
2564
-
4138
-
96c6
-
3ae7d245fbed
)
]
interface
nsIProxyInfo
:
nsISupports
{
readonly
attribute
AUTF8String
host
;
readonly
attribute
long
port
;
readonly
attribute
ACString
type
;
readonly
attribute
unsigned
long
flags
;
readonly
attribute
unsigned
long
resolveFlags
;
readonly
attribute
ACString
username
;
readonly
attribute
ACString
password
;
readonly
attribute
unsigned
long
failoverTimeout
;
attribute
nsIProxyInfo
failoverProxy
;
attribute
ACString
sourceId
;
readonly
attribute
ACString
proxyAuthorizationHeader
;
readonly
attribute
ACString
connectionIsolationKey
;
attribute
AUTF8String
masqueTemplate
;
const
unsigned
short
SOCKS_V4
=
4
;
const
unsigned
short
SOCKS_V5
=
5
;
const
unsigned
short
TRANSPARENT_PROXY_RESOLVES_HOST
=
1
<
<
0
;
}
;
