#
include
"
nsISupports
.
idl
"
interface
nsIPrincipal
;
interface
nsIPermission
;
[
scriptable
builtinclass
uuid
(
4dcb3851
-
eba2
-
4e42
-
b236
-
82d2596fca22
)
]
interface
nsIPermissionManager
:
nsISupports
{
const
uint32_t
UNKNOWN_ACTION
=
0
;
const
uint32_t
ALLOW_ACTION
=
1
;
const
uint32_t
DENY_ACTION
=
2
;
const
uint32_t
PROMPT_ACTION
=
3
;
const
uint32_t
EXPIRE_NEVER
=
0
;
const
uint32_t
EXPIRE_SESSION
=
1
;
const
uint32_t
EXPIRE_TIME
=
2
;
const
uint32_t
EXPIRE_POLICY
=
3
;
Array
<
nsIPermission
>
getAllForPrincipal
(
in
nsIPrincipal
principal
)
;
Array
<
nsIPermission
>
getAllWithTypePrefix
(
in
ACString
prefix
)
;
Array
<
nsIPermission
>
getAllByTypeSince
(
in
ACString
type
in
int64_t
since
)
;
void
addFromPrincipal
(
in
nsIPrincipal
principal
in
ACString
type
in
uint32_t
permission
[
optional
]
in
uint32_t
expireType
[
optional
]
in
int64_t
expireTime
)
;
void
addFromPrincipalAndPersistInPrivateBrowsing
(
in
nsIPrincipal
principal
in
ACString
type
in
uint32_t
permission
)
;
void
removeFromPrincipal
(
in
nsIPrincipal
principal
in
ACString
type
)
;
void
removePermission
(
in
nsIPermission
perm
)
;
void
removeAll
(
)
;
void
removeAllSince
(
in
int64_t
since
)
;
void
removeByType
(
in
ACString
type
)
;
void
removeByTypeSince
(
in
ACString
type
in
int64_t
since
)
;
uint32_t
testPermissionFromPrincipal
(
in
nsIPrincipal
principal
in
ACString
type
)
;
uint32_t
testExactPermissionFromPrincipal
(
in
nsIPrincipal
principal
in
ACString
type
)
;
uint32_t
testExactPermanentPermission
(
in
nsIPrincipal
principal
in
ACString
type
)
;
nsIPermission
getPermissionObject
(
in
nsIPrincipal
principal
in
ACString
type
in
boolean
exactHost
)
;
readonly
attribute
Array
<
nsIPermission
>
all
;
void
removePermissionsWithAttributes
(
in
AString
patternAsJSON
)
;
}
;
%
{
C
+
+
#
define
NS_PERMISSIONMANAGER_CONTRACTID
"
mozilla
.
org
/
permissionmanager
;
1
"
#
define
PERM_CHANGE_NOTIFICATION
"
perm
-
changed
"
%
}
