#
include
"
nsISupports
.
idl
"
interface
nsIURI
;
interface
nsIRequest
;
[
scriptable
uuid
(
87d55fba
-
cb7e
-
4f38
-
84c1
-
5c6c2b2a55e9
)
]
interface
nsIProgressEventSink
:
nsISupports
{
void
onProgress
(
in
nsIRequest
aRequest
in
nsISupports
aContext
in
long
long
aProgress
in
long
long
aProgressMax
)
;
void
onStatus
(
in
nsIRequest
aRequest
in
nsISupports
aContext
in
nsresult
aStatus
in
wstring
aStatusArg
)
;
}
;
