#
include
"
nsIProtocolProxyService
.
idl
"
[
scriptable
builtinclass
uuid
(
b2e5b2c0
-
e21e
-
4845
-
b336
-
be6d60a38951
)
]
interface
nsIProtocolProxyService2
:
nsIProtocolProxyService
{
void
reloadPAC
(
)
;
nsICancelable
asyncResolve2
(
in
nsIChannel
aChannel
in
unsigned
long
aFlags
in
nsIProtocolProxyCallback
aCallback
[
optional
]
in
nsISerialEventTarget
aMainThreadTarget
)
;
}
;
