#
include
"
nsISupports
.
idl
"
interface
nsIPrincipal
;
interface
nsIURI
;
[
scriptable
uuid
(
bb409a51
-
2371
-
4fea
-
9dc9
-
b7286a458b8c
)
]
interface
nsIPermission
:
nsISupports
{
readonly
attribute
nsIPrincipal
principal
;
readonly
attribute
ACString
type
;
readonly
attribute
uint32_t
capability
;
readonly
attribute
uint32_t
expireType
;
readonly
attribute
int64_t
expireTime
;
readonly
attribute
int64_t
modificationTime
;
boolean
matches
(
in
nsIPrincipal
principal
in
boolean
exactHost
)
;
boolean
matchesURI
(
in
nsIURI
uri
in
boolean
exactHost
)
;
}
;
