#
include
"
nsISupports
.
idl
"
interface
nsIChannel
;
interface
nsIProtocolProxyService
;
interface
nsIProxyInfo
;
interface
nsIURI
;
[
scriptable
uuid
(
009E6C3F
-
FB64
-
40C5
-
8093
-
F1495C64773E
)
]
interface
nsIProxyProtocolFilterResult
:
nsISupports
{
void
onProxyFilterResult
(
in
nsIProxyInfo
aProxy
)
;
}
;
[
scriptable
uuid
(
f424abd3
-
32b4
-
456c
-
9f45
-
b7e3376cb0d1
)
]
interface
nsIProtocolProxyFilter
:
nsISupports
{
void
applyFilter
(
in
nsIURI
aURI
in
nsIProxyInfo
aProxy
in
nsIProxyProtocolFilterResult
aCallback
)
;
}
;
[
scriptable
uuid
(
245b0880
-
82c5
-
4e6e
-
be6d
-
bc586aa55a90
)
]
interface
nsIProtocolProxyChannelFilter
:
nsISupports
{
void
applyFilter
(
in
nsIChannel
aChannel
in
nsIProxyInfo
aProxy
in
nsIProxyProtocolFilterResult
aCallback
)
;
}
;
