#
include
"
nsISupports
.
idl
"
%
{
C
+
+
#
include
"
nsCOMPtr
.
h
"
#
define
NS_NETWORK_PROTOCOL_CONTRACTID_PREFIX
"
mozilla
.
org
/
network
/
protocol
;
1
?
name
=
"
#
if
defined
(
MOZ_THUNDERBIRD
)
|
|
defined
(
MOZ_SUITE
)
#
define
IS_ORIGIN_IS_FULL_SPEC_DEFINED
1
#
endif
%
}
interface
nsIURI
;
interface
nsIChannel
;
interface
nsILoadInfo
;
[
scriptable
builtinclass
uuid
(
65a8e823
-
0591
-
4fc0
-
a56a
-
03265e0a4ce8
)
]
interface
nsIProtocolHandlerWithDynamicFlags
:
nsISupports
{
unsigned
long
getFlagsForURI
(
in
nsIURI
aURI
)
;
}
;
[
scriptable
uuid
(
a87210e6
-
7c8c
-
41f7
-
864d
-
df809015193e
)
]
interface
nsIProtocolHandler
:
nsISupports
{
readonly
attribute
ACString
scheme
;
nsIChannel
newChannel
(
in
nsIURI
aURI
in
nsILoadInfo
aLoadinfo
)
;
boolean
allowPort
(
in
long
port
in
string
scheme
)
;
const
unsigned
long
URI_STD
=
0
;
const
unsigned
long
URI_NORELATIVE
=
(
1
<
<
0
)
;
const
unsigned
long
URI_NOAUTH
=
(
1
<
<
1
)
;
const
unsigned
long
ALLOWS_PROXY
=
(
1
<
<
2
)
;
const
unsigned
long
ALLOWS_PROXY_HTTP
=
(
1
<
<
3
)
;
const
unsigned
long
URI_INHERITS_SECURITY_CONTEXT
=
(
1
<
<
4
)
;
const
unsigned
long
URI_FORBIDS_AUTOMATIC_DOCUMENT_REPLACEMENT
=
(
1
<
<
5
)
;
const
unsigned
long
URI_LOADABLE_BY_ANYONE
=
(
1
<
<
6
)
;
const
unsigned
long
URI_DANGEROUS_TO_LOAD
=
(
1
<
<
7
)
;
const
unsigned
long
URI_IS_UI_RESOURCE
=
(
1
<
<
8
)
;
const
unsigned
long
URI_IS_LOCAL_FILE
=
(
1
<
<
9
)
;
const
unsigned
long
URI_LOADABLE_BY_SUBSUMERS
=
(
1
<
<
10
)
;
const
unsigned
long
URI_DOES_NOT_RETURN_DATA
=
(
1
<
<
11
)
;
const
unsigned
long
URI_IS_LOCAL_RESOURCE
=
(
1
<
<
12
)
;
const
unsigned
long
URI_OPENING_EXECUTES_SCRIPT
=
(
1
<
<
13
)
;
const
unsigned
long
URI_NON_PERSISTABLE
=
(
1
<
<
14
)
;
const
unsigned
long
URI_CROSS_ORIGIN_NEEDS_WEBAPPS_PERM
=
(
1
<
<
15
)
;
const
unsigned
long
URI_SYNC_LOAD_IS_OK
=
(
1
<
<
16
)
;
const
unsigned
long
URI_IS_POTENTIALLY_TRUSTWORTHY
=
(
1
<
<
17
)
;
const
unsigned
long
ORIGIN_IS_FULL_SPEC
=
(
1
<
<
19
)
;
const
unsigned
long
URI_SCHEME_NOT_SELF_LINKABLE
=
(
1
<
<
20
)
;
const
unsigned
long
URI_LOADABLE_BY_EXTENSIONS
=
(
1
<
<
21
)
;
const
unsigned
long
URI_DISALLOW_IN_PRIVATE_CONTEXT
=
(
1
<
<
22
)
;
const
unsigned
long
URI_FORBIDS_COOKIE_ACCESS
=
(
1
<
<
23
)
;
const
unsigned
long
WEBEXT_URI_WEB_ACCESSIBLE
=
(
1
<
<
24
)
;
const
unsigned
long
URI_HAS_WEB_EXPOSED_ORIGIN
=
(
1
<
<
25
)
;
const
unsigned
long
DYNAMIC_URI_FLAGS
=
URI_LOADABLE_BY_ANYONE
|
URI_DANGEROUS_TO_LOAD
|
URI_IS_POTENTIALLY_TRUSTWORTHY
|
URI_LOADABLE_BY_EXTENSIONS
|
URI_DISALLOW_IN_PRIVATE_CONTEXT
|
WEBEXT_URI_WEB_ACCESSIBLE
|
URI_HAS_WEB_EXPOSED_ORIGIN
;
}
;
