#
include
"
nsISupports
.
idl
"
interface
nsIRequest
;
[
scriptable
uuid
(
fd91e2e0
-
1481
-
11d3
-
9333
-
00104ba0fd40
)
]
interface
nsIRequestObserver
:
nsISupports
{
void
onStartRequest
(
in
nsIRequest
aRequest
)
;
void
onStopRequest
(
in
nsIRequest
aRequest
in
nsresult
aStatusCode
)
;
}
;
