#
include
"
nsISupports
.
idl
"
interface
nsIFile
;
interface
nsISocketTransport
;
interface
nsIProxyInfo
;
interface
nsIRunnable
;
%
{
C
+
+
class
nsASocketHandler
;
struct
PRFileDesc
;
%
}
[
ptr
]
native
PRFileDescPtr
(
PRFileDesc
)
;
[
ptr
]
native
nsASocketHandlerPtr
(
nsASocketHandler
)
;
[
scriptable
function
uuid
(
338947df
-
2f3b
-
4d24
-
9ce4
-
ecf161c1b7df
)
]
interface
nsISTSShutdownObserver
:
nsISupports
{
void
observe
(
)
;
}
;
[
builtinclass
scriptable
uuid
(
ad56b25f
-
e6bb
-
4db3
-
9f7b
-
5b7db33fd2b1
)
]
interface
nsISocketTransportService
:
nsISupports
{
nsISocketTransport
createTransport
(
in
Array
<
ACString
>
aSocketTypes
in
AUTF8String
aHost
in
long
aPort
in
nsIProxyInfo
aProxyInfo
)
;
nsISocketTransport
createUnixDomainTransport
(
in
nsIFile
aPath
)
;
nsISocketTransport
createUnixDomainAbstractAddressTransport
(
in
ACString
aName
)
;
[
noscript
]
void
attachSocket
(
in
PRFileDescPtr
aFd
in
nsASocketHandlerPtr
aHandler
)
;
[
noscript
]
void
notifyWhenCanAttachSocket
(
in
nsIRunnable
aEvent
)
;
[
noscript
]
void
addShutdownObserver
(
in
nsISTSShutdownObserver
aObserver
)
;
[
noscript
]
void
removeShutdownObserver
(
in
nsISTSShutdownObserver
aObserver
)
;
}
;
[
builtinclass
scriptable
uuid
(
c5204623
-
5b58
-
4a16
-
8b2e
-
67c34dd02e3f
)
]
interface
nsIRoutedSocketTransportService
:
nsISocketTransportService
{
nsISocketTransport
createRoutedTransport
(
in
Array
<
ACString
>
aSocketTypes
in
AUTF8String
aHost
in
long
aPort
in
AUTF8String
aHostRoute
in
long
aPortRoute
in
nsIProxyInfo
aProxyInfo
)
;
}
;
