#
include
"
nsIRequestObserver
.
idl
"
interface
nsIInputStream
;
[
scriptable
uuid
(
3b4c8a77
-
76ba
-
4610
-
b316
-
678c73a3b88c
)
]
interface
nsIStreamListener
:
nsIRequestObserver
{
void
onDataAvailable
(
in
nsIRequest
aRequest
in
nsIInputStream
aInputStream
in
unsigned
long
long
aOffset
in
unsigned
long
aCount
)
;
}
;
