#
include
"
nsISupports
.
idl
"
interface
nsISerialEventTarget
;
[
uuid
(
27b84c48
-
5a73
-
4ba4
-
a8a4
-
8b5e649a145e
)
]
interface
nsIThreadRetargetableRequest
:
nsISupports
{
[
must_use
]
void
retargetDeliveryTo
(
in
nsISerialEventTarget
aNewTarget
)
;
readonly
attribute
nsISerialEventTarget
deliveryTarget
;
}
;
