#
include
"
nsISupports
.
idl
"
#
include
"
nsIStreamListener
.
idl
"
[
uuid
(
fb2304b8
-
f82f
-
4433
-
af68
-
d874a2ebbdc1
)
]
interface
nsIThreadRetargetableStreamListener
:
nsIStreamListener
{
void
checkListenerChain
(
)
;
void
onDataFinished
(
in
nsresult
aStatusCode
)
;
}
;
