#
include
"
nsISupports
.
idl
"
interface
nsIStreamListener
;
[
scriptable
uuid
(
68167b0b
-
ef34
-
4d79
-
a09a
-
8045f7c5140e
)
]
interface
nsITraceableChannel
:
nsISupports
{
nsIStreamListener
setNewListener
(
in
nsIStreamListener
aListener
[
optional
]
in
boolean
aMustApplyContentConversion
)
;
}
;
