#
include
"
nsISupports
.
idl
"
interface
nsIInputStream
;
interface
nsIRunnable
;
[
scriptable
uuid
(
2f712b52
-
19c5
-
4e0c
-
9e8f
-
b5c7c3b67049
)
]
interface
nsIUploadChannel2
:
nsISupports
{
void
explicitSetUploadStream
(
in
nsIInputStream
aStream
in
ACString
aContentType
in
long
long
aContentLength
in
ACString
aMethod
in
boolean
aStreamHasHeaders
)
;
readonly
attribute
boolean
uploadStreamHasHeaders
;
[
noscript
]
void
ensureUploadStreamIsCloneable
(
in
nsIRunnable
aCallback
)
;
[
noscript
]
nsIInputStream
cloneUploadStream
(
out
long
long
aContentLength
)
;
}
;
