#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
c5765549
-
7cf1
-
4b3d
-
9baa
-
5e74282be542
)
]
interface
nsIPermissionMonitor
:
nsISupports
{
void
startMonitoring
(
in
AString
aCapabilityName
)
;
}
;
