#
include
"
nsISupports
.
idl
"
#
include
"
nsIFile
.
idl
"
[
scriptable
function
uuid
(
3d3b9075
-
5549
-
4244
-
9c08
-
b64fefa1dd60
)
]
interface
nsIFetchTelemetryDataCallback
:
nsISupports
{
void
complete
(
)
;
}
;
[
scriptable
uuid
(
273d2dd0
-
6c63
-
475a
-
b864
-
cb65160a1909
)
]
interface
nsITelemetry
:
nsISupports
{
const
unsigned
long
HISTOGRAM_EXPONENTIAL
=
0
;
const
unsigned
long
HISTOGRAM_LINEAR
=
1
;
const
unsigned
long
HISTOGRAM_BOOLEAN
=
2
;
const
unsigned
long
HISTOGRAM_FLAG
=
3
;
const
unsigned
long
HISTOGRAM_COUNT
=
4
;
const
unsigned
long
HISTOGRAM_CATEGORICAL
=
5
;
const
unsigned
long
SCALAR_TYPE_COUNT
=
0
;
const
unsigned
long
SCALAR_TYPE_STRING
=
1
;
const
unsigned
long
SCALAR_TYPE_BOOLEAN
=
2
;
const
unsigned
long
DATASET_ALL_CHANNELS
=
0
;
const
unsigned
long
DATASET_PRERELEASE_CHANNELS
=
1
;
[
implicit_jscontext
]
jsval
getCategoricalLabels
(
)
;
[
implicit_jscontext
]
jsval
getSnapshotForHistograms
(
[
optional
]
in
ACString
aStoreName
[
optional
]
in
boolean
aClearStore
[
optional
]
in
boolean
aFilterTest
)
;
[
implicit_jscontext
]
jsval
getSnapshotForKeyedHistograms
(
[
optional
]
in
ACString
aStoreName
[
optional
]
in
boolean
aClearStore
[
optional
]
in
boolean
aFilterTest
)
;
[
implicit_jscontext
]
jsval
getSnapshotForScalars
(
[
optional
]
in
ACString
aStoreName
[
optional
]
in
boolean
aClearStore
[
optional
]
in
boolean
aFilterTest
)
;
[
implicit_jscontext
]
jsval
getSnapshotForKeyedScalars
(
[
optional
]
in
ACString
aStoreName
[
optional
]
in
boolean
aClearStore
[
optional
]
in
boolean
aFilterTest
)
;
readonly
attribute
uint32_t
lastShutdownDuration
;
readonly
attribute
uint32_t
failedProfileLockCount
;
[
implicit_jscontext
]
readonly
attribute
jsval
slowSQL
;
[
implicit_jscontext
]
readonly
attribute
jsval
debugSlowSQL
;
const
unsigned
long
INCLUDE_OLD_LOADEVENTS
=
1
<
<
0
;
const
unsigned
long
KEEP_LOADEVENTS_NEW
=
1
<
<
1
;
const
unsigned
long
INCLUDE_PRIVATE_FIELDS_IN_LOADEVENTS
=
1
<
<
2
;
const
unsigned
long
EXCLUDE_STACKINFO_FROM_LOADEVENTS
=
1
<
<
3
;
[
implicit_jscontext
]
Promise
submitAndGetUntrustedModulePayload
(
)
;
[
implicit_jscontext
]
Promise
getUntrustedModuleLoadEvents
(
[
optional
]
in
unsigned
long
aFlags
)
;
readonly
attribute
boolean
areUntrustedModuleLoadEventsReady
;
[
implicit_jscontext
]
jsval
getHistogramById
(
in
ACString
id
)
;
[
implicit_jscontext
]
jsval
getKeyedHistogramById
(
in
ACString
id
)
;
attribute
boolean
canRecordBase
;
attribute
boolean
canRecordExtended
;
readonly
attribute
boolean
canRecordReleaseData
;
readonly
attribute
boolean
canRecordPrereleaseData
;
readonly
attribute
boolean
isOfficialTelemetry
;
void
asyncFetchTelemetryData
(
in
nsIFetchTelemetryDataCallback
aCallback
)
;
[
implicit_jscontext
]
readonly
attribute
jsval
fileIOReports
;
double
msSinceProcessStart
(
)
;
double
msSinceProcessStartIncludingSuspend
(
)
;
double
msSinceProcessStartExcludingSuspend
(
)
;
double
msSystemNow
(
)
;
void
clearScalars
(
)
;
void
flushBatchedChildTelemetry
(
)
;
[
implicit_jscontext
optional_argc
]
jsval
snapshotEvents
(
in
uint32_t
aDataset
[
optional
]
in
boolean
aClear
[
optional
]
in
uint32_t
aEventLimit
)
;
[
implicit_jscontext
]
void
registerBuiltinEvents
(
in
ACString
aCategory
in
jsval
aEventData
)
;
[
implicit_jscontext
]
void
registerBuiltinScalars
(
in
ACString
aCategoryName
in
jsval
aScalarData
)
;
void
clearEvents
(
)
;
[
implicit_jscontext
]
jsval
getAllStores
(
)
;
void
earlyInit
(
)
;
void
delayedInit
(
)
;
void
shutdown
(
)
;
[
implicit_jscontext
]
Promise
gatherMemory
(
)
;
}
;
