#
include
"
nsISupports
.
idl
"
%
{
C
+
+
class
nsDocShellLoadState
;
%
}
webidl
BrowsingContext
;
interface
mozIDOMWindowProxy
;
interface
nsIURI
;
interface
nsIOpenWindowInfo
;
native
nsDocShellLoadStatePtr
(
nsDocShellLoadState
*
)
;
[
scriptable
uuid
(
e97a3830
-
15ef
-
499b
-
8372
-
c22d128091c1
)
]
interface
nsIWindowProvider
:
nsISupports
{
[
noscript
]
BrowsingContext
provideWindow
(
in
nsIOpenWindowInfo
aOpenWindowInfo
in
unsigned
long
aChromeFlags
in
boolean
aCalledFromJS
in
boolean
aWidthSpecified
in
nsIURI
aURI
in
AString
aName
in
AUTF8String
aFeatures
in
boolean
aForceNoOpener
in
boolean
aForceNoReferrer
in
nsDocShellLoadStatePtr
aLoadState
out
boolean
aWindowIsNew
)
;
}
;
