#
include
"
nsISupports
.
idl
"
interface
nsIOpenWindowInfo
;
interface
nsIRemoteTab
;
interface
nsIURI
;
interface
nsIWebBrowserChrome
;
interface
mozIDOMWindowProxy
;
[
scriptable
uuid
(
30465632
-
A777
-
44cc
-
90F9
-
8145475EF999
)
]
interface
nsIWindowCreator
:
nsISupports
{
nsIWebBrowserChrome
createChromeWindow
(
in
nsIWebBrowserChrome
parent
in
uint32_t
chromeFlags
in
nsIOpenWindowInfo
aOpenWindowInfo
out
boolean
cancel
)
;
}
;
%
{
C
+
+
#
define
NS_WINDOWCREATOR_IID
\
{
0x30465632
0xa777
0x44cc
{
0x90
0xf9
0x81
0x45
0x47
0x5e
0xf9
0x99
}
}
%
}
