#
include
"
nsISupports
.
idl
"
interface
nsIFile
;
interface
nsIURI
;
interface
mozIPersonalDictionary
;
[
scriptable
uuid
(
8ba643a4
-
7ddc
-
4662
-
b976
-
7ec123843f10
)
]
interface
mozISpellCheckingEngine
:
nsISupports
{
attribute
Array
<
ACString
>
dictionaries
;
attribute
mozIPersonalDictionary
personalDictionary
;
Array
<
ACString
>
getDictionaryList
(
)
;
boolean
check
(
in
AString
word
)
;
Array
<
AString
>
suggest
(
in
AString
word
)
;
void
loadDictionariesFromDir
(
in
nsIFile
dir
)
;
void
addDirectory
(
in
nsIFile
dir
)
;
void
removeDirectory
(
in
nsIFile
dir
)
;
void
addDictionary
(
in
AString
lang
in
nsIURI
file
)
;
bool
removeDictionary
(
in
AString
lang
in
nsIURI
file
)
;
}
;
%
{
C
+
+
#
define
SPELLCHECK_DICTIONARY_REMOVE_NOTIFICATION
\
"
spellcheck
-
dictionary
-
remove
"
%
}
