#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
0a4478f4
-
c5ae
-
4fb1
-
8686
-
d5b09fb99afb
)
]
interface
nsIUtilityProcessTest
:
nsISupports
{
[
implicit_jscontext
]
Promise
startProcess
(
[
optional
]
in
int32_t
unknownActors
)
;
void
stopProcess
(
)
;
void
testTelemetryProbes
(
)
;
}
;
