#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
0a4478f4
-
c5ae
-
4fb1
-
8686
-
d5b09fb99afb
)
]
interface
nsIUtilityProcessTest
:
nsISupports
{
[
implicit_jscontext
]
Promise
startProcess
(
[
optional
]
in
Array
<
ACString
>
actorsToAdd
)
;
[
implicit_jscontext
]
Promise
untilChildProcessDead
(
in
uint32_t
pid
)
;
void
noteIntentionalCrash
(
in
unsigned
long
pid
)
;
void
stopProcess
(
[
optional
]
in
string
utilityActorName
)
;
void
testTelemetryProbes
(
)
;
}
;
