#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
494f9336
-
ad06
-
46ad
-
bbb4
-
b0010e27e12d
)
]
interface
nsIXPCTestESMReturnCodeParent
:
nsISupports
{
nsresult
callChild
(
in
long
childBehavior
)
;
}
;
[
scriptable
uuid
(
dee07408
-
75d8
-
4968
-
a37c
-
fe0d48ccd1ac
)
]
interface
nsIXPCTestESMReturnCodeChild
:
nsISupports
{
void
doIt
(
in
long
behavior
)
;
const
long
CHILD_SHOULD_THROW
=
0
;
const
long
CHILD_SHOULD_RETURN_SUCCESS
=
1
;
const
long
CHILD_SHOULD_RETURN_RESULTCODE
=
2
;
const
long
CHILD_SHOULD_NEST_RESULTCODES
=
3
;
}
;
