#
include
"
nsISupports
.
idl
"
interface
nsIAppWindow
;
[
scriptable
uuid
(
2F276982
-
0D60
-
4377
-
A595
-
D350BA516395
)
]
interface
nsIWindowMediatorListener
:
nsISupports
{
void
onOpenWindow
(
in
nsIAppWindow
window
)
;
void
onCloseWindow
(
in
nsIAppWindow
window
)
;
}
;
