#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
0b976267
-
4aaa
-
4f36
-
a2d4
-
27b5ca8d73bb
)
]
interface
nsIEmbeddingSiteWindow
:
nsISupports
{
const
unsigned
long
DIM_FLAGS_POSITION
=
1
;
const
unsigned
long
DIM_FLAGS_SIZE_INNER
=
2
;
const
unsigned
long
DIM_FLAGS_SIZE_OUTER
=
4
;
const
unsigned
long
DIM_FLAGS_IGNORE_X
=
8
;
const
unsigned
long
DIM_FLAGS_IGNORE_Y
=
16
;
const
unsigned
long
DIM_FLAGS_IGNORE_CX
=
32
;
const
unsigned
long
DIM_FLAGS_IGNORE_CY
=
64
;
void
setDimensions
(
in
unsigned
long
flags
in
long
x
in
long
y
in
long
cx
in
long
cy
)
;
void
getDimensions
(
in
unsigned
long
flags
out
long
x
out
long
y
out
long
cx
out
long
cy
)
;
attribute
boolean
visibility
;
attribute
AString
title
;
[
noscript
]
readonly
attribute
voidPtr
siteWindow
;
void
blur
(
)
;
}
;
