#
include
"
nsISupports
.
idl
"
#
include
"
nsIWebBrowserPrint
.
idl
"
#
include
"
nsIWebProgressListener
.
idl
"
#
include
"
nsIPrintProgressParams
.
idl
"
#
include
"
nsIPrintSettings
.
idl
"
#
include
"
nsIObserver
.
idl
"
[
scriptable
uuid
(
72006d06
-
a2a5
-
4250
-
ae92
-
04b2f0e2ab8d
)
]
interface
nsIPrintingPromptService
:
nsISupports
{
void
showPrintDialog
(
in
mozIDOMWindowProxy
parent
in
nsIPrintSettings
printSettings
)
;
void
showPrintProgressDialog
(
in
mozIDOMWindowProxy
parent
in
nsIPrintSettings
printSettings
in
nsIObserver
openDialogObserver
in
boolean
isForPrinting
out
nsIWebProgressListener
webProgressListener
out
nsIPrintProgressParams
printProgressParams
out
boolean
notifyOnOpen
)
;
void
showPageSetupDialog
(
in
mozIDOMWindowProxy
parent
in
nsIPrintSettings
printSettings
)
;
}
;
%
{
C
+
+
#
define
NS_PRINTINGPROMPTSERVICE_IID
\
{
0x260fedc5
0x524d
0x4aa6
{
0x9a
0x41
0xe8
0x29
0xf4
0xc7
0x8b
0x92
}
}
%
}
