#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
947B2EE6
-
51ED
-
4C2B
-
9F45
-
426C27CA84C6
)
]
interface
nsIWebBrowserChromeFocus
:
nsISupports
{
void
focusNextElement
(
in
boolean
aForDocumentNavigation
)
;
void
focusPrevElement
(
in
boolean
aForDocumentNavigation
)
;
}
;
