#
include
"
nsISupports
.
idl
"
interface
nsIDataStorage
;
interface
nsIDataStorageItem
;
[
scriptable
uuid
(
71b49926
-
fd4e
-
43e2
-
ab8d
-
d9b049413c0b
)
]
interface
nsIDataStorageManager
:
nsISupports
{
cenum
DataStorage
:
8
{
AlternateServices
ClientAuthRememberList
SiteSecurityServiceState
}
;
nsIDataStorage
get
(
in
nsIDataStorageManager_DataStorage
dataStorage
)
;
}
;
[
scriptable
uuid
(
fcbb5ec4
-
7134
-
4069
-
91c6
-
9378eff51e03
)
]
interface
nsIDataStorage
:
nsISupports
{
cenum
DataType
:
8
{
Persistent
Private
}
;
ACString
get
(
in
ACString
key
in
nsIDataStorage_DataType
type
)
;
void
put
(
in
ACString
key
in
ACString
value
in
nsIDataStorage_DataType
type
)
;
void
remove
(
in
ACString
key
in
nsIDataStorage_DataType
type
)
;
void
clear
(
)
;
boolean
isReady
(
)
;
Array
<
nsIDataStorageItem
>
getAll
(
)
;
}
;
[
scriptable
uuid
(
4501f984
-
0e3a
-
4199
-
a67e
-
7753649e93f1
)
]
interface
nsIDataStorageItem
:
nsISupports
{
readonly
attribute
ACString
key
;
readonly
attribute
ACString
value
;
readonly
attribute
nsIDataStorage_DataType
type
;
}
;
