#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
3201b705
-
0907
-
4f7c
-
aa9b
-
78bfeae52ed6
)
]
interface
nsIFIPSUtils
:
nsISupports
{
[
must_use
]
readonly
attribute
boolean
canToggleFIPS
;
[
must_use
]
void
toggleFIPSMode
(
)
;
[
must_use
]
readonly
attribute
boolean
isFIPSEnabled
;
}
;
