#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
12f60021
-
e14b
-
4020
-
99d1
-
ed2c795be66a
)
]
interface
nsINSSErrorsService
:
nsISupports
{
[
must_use
]
boolean
isNSSErrorCode
(
in
int32_t
aNSPRCode
)
;
[
must_use
]
nsresult
getXPCOMFromNSSError
(
in
int32_t
aNSPRCode
)
;
AString
getErrorMessage
(
in
nsresult
aXPCOMErrorCode
)
;
AString
getErrorName
(
in
nsresult
aXPCOMErrorCode
)
;
[
must_use
]
uint32_t
getErrorClass
(
in
nsresult
aXPCOMErrorCode
)
;
[
must_use
]
boolean
isErrorOverridable
(
in
nsresult
aXPCOMErrorCode
)
;
const
unsigned
long
ERROR_CLASS_SSL_PROTOCOL
=
1
;
const
unsigned
long
ERROR_CLASS_BAD_CERT
=
2
;
const
long
NSS_SEC_ERROR_BASE
=
-
(
0x2000
)
;
const
long
NSS_SEC_ERROR_LIMIT
=
(
NSS_SEC_ERROR_BASE
+
1000
)
;
const
long
NSS_SSL_ERROR_BASE
=
-
(
0x3000
)
;
const
long
NSS_SSL_ERROR_LIMIT
=
(
NSS_SSL_ERROR_BASE
+
1000
)
;
const
long
MOZILLA_PKIX_ERROR_BASE
=
-
(
0x4000
)
;
const
long
MOZILLA_PKIX_ERROR_LIMIT
=
(
MOZILLA_PKIX_ERROR_BASE
+
1000
)
;
}
;
