#
include
"
nsISupports
.
idl
"
%
{
C
+
+
#
include
"
cert
.
h
"
#
include
"
SharedCertVerifier
.
h
"
#
define
PSM_COMPONENT_CONTRACTID
"
mozilla
.
org
/
psm
;
1
"
%
}
[
ptr
]
native
CERTCertificatePtr
(
CERTCertificate
)
;
[
ptr
]
native
SharedCertVerifierPtr
(
mozilla
:
:
psm
:
:
SharedCertVerifier
)
;
[
scriptable
uuid
(
a0a8f52b
-
ea18
-
4abc
-
a3ca
-
eccf704ffe63
)
]
interface
nsINSSComponent
:
nsISupports
{
[
noscript
]
void
logoutAuthenticatedPK11
(
)
;
[
noscript
]
bool
isCertTestBuiltInRoot
(
in
Array
<
octet
>
cert
)
;
Array
<
Array
<
octet
>
>
getEnterpriseRoots
(
)
;
Array
<
Array
<
octet
>
>
getEnterpriseIntermediates
(
)
;
void
addEnterpriseIntermediate
(
in
Array
<
octet
>
intermediateBytes
)
;
[
noscript
]
void
blockUntilLoadableCertsLoaded
(
)
;
[
noscript
]
void
checkForSmartCardChanges
(
)
;
[
noscript
]
void
issuerMatchesMitmCanary
(
in
string
certIssuer
)
;
[
noscript
]
SharedCertVerifierPtr
getDefaultCertVerifier
(
)
;
void
clearSSLExternalAndInternalSessionCache
(
)
;
[
implicit_jscontext
]
Promise
asyncClearSSLExternalAndInternalSessionCache
(
)
;
}
;
