#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
57972956
-
5718
-
42d2
-
8070
-
b3fc72212eaf
)
]
interface
nsIOSKeyStore
:
nsISupports
{
[
implicit_jscontext
must_use
]
Promise
asyncGenerateSecret
(
in
ACString
label
)
;
[
implicit_jscontext
must_use
]
Promise
asyncSecretAvailable
(
in
ACString
label
)
;
[
implicit_jscontext
must_use
]
Promise
asyncRecoverSecret
(
in
ACString
label
in
ACString
recoveryPhrase
)
;
[
implicit_jscontext
must_use
]
Promise
asyncDeleteSecret
(
in
ACString
label
)
;
[
implicit_jscontext
must_use
]
Promise
asyncEncryptBytes
(
in
ACString
label
in
Array
<
uint8_t
>
inBytes
)
;
[
implicit_jscontext
must_use
]
Promise
asyncDecryptBytes
(
in
ACString
label
in
ACString
encryptedBase64Text
)
;
[
implicit_jscontext
must_use
]
Promise
asyncGetRecoveryPhrase
(
in
ACString
aLabel
)
;
}
;
