#
include
"
nsISupports
.
idl
"
interface
mozIDOMWindow
;
[
scriptable
uuid
(
4fe082ae
-
6ff0
-
4b41
-
b24f
-
eaa664f6e46a
)
]
interface
nsIOSReauthenticator
:
nsISupports
{
[
implicit_jscontext
must_use
]
Promise
asyncReauthenticateUser
(
in
AString
prompt
in
AString
caption
in
mozIDOMWindow
parentWindow
)
;
}
;
