#
include
"
nsISerialEventTarget
.
idl
"
#
include
"
nsISupports
.
idl
"
%
{
C
+
+
#
define
NS_PKCS11MODULEDB_CONTRACTID
"
mozilla
.
org
/
security
/
pkcs11moduledb
;
1
"
%
}
[
scriptable
uuid
(
ff9fbcd7
-
9517
-
4334
-
b97a
-
ceed78909974
)
]
interface
nsIPKCS11ModuleDB
:
nsISupports
{
[
implicit_jscontext
must_use
]
Promise
deleteModule
(
in
AString
moduleName
)
;
[
implicit_jscontext
must_use
]
Promise
addModule
(
in
AString
moduleName
in
AString
libraryPath
in
unsigned
long
mechanismFlags
in
unsigned
long
cipherFlags
)
;
[
implicit_jscontext
must_use
]
Promise
listModules
(
)
;
}
;
