#
include
"
nsISupports
.
idl
"
interface
nsIPK11Token
;
[
scriptable
uuid
(
4ee28c82
-
1dd2
-
11b2
-
aabf
-
bb4017abe395
)
]
interface
nsIPK11TokenDB
:
nsISupports
{
nsIPK11Token
getInternalKeyToken
(
)
;
}
;
