#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
5d1acf82
-
223a
-
46fb
-
a8f3
-
a1b16e2ceb04
)
]
interface
nsISecurityUITelemetry
:
nsISupports
{
const
uint32_t
WARNING_ADDON_ASKING_PREVENTED
=
1
;
const
uint32_t
WARNING_ADDON_ASKING_PREVENTED_CLICK_THROUGH
=
2
;
const
uint32_t
WARNING_CONFIRM_ADDON_INSTALL
=
3
;
const
uint32_t
WARNING_CONFIRM_ADDON_INSTALL_CLICK_THROUGH
=
4
;
const
uint32_t
WARNING_CONFIRM_POST_TO_INSECURE_FROM_SECURE
=
9
;
const
uint32_t
WARNING_CONFIRM_POST_TO_INSECURE_FROM_SECURE_CLICK_THROUGH
=
10
;
}
;
