#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
5d1acf82
-
223a
-
46fb
-
a8f3
-
a1b16e2ceb04
)
]
interface
nsISecurityUITelemetry
:
nsISupports
{
const
uint32_t
WARNING_ADDON_ASKING_PREVENTED
=
1
;
const
uint32_t
WARNING_ADDON_ASKING_PREVENTED_CLICK_THROUGH
=
2
;
const
uint32_t
WARNING_CONFIRM_ADDON_INSTALL
=
3
;
const
uint32_t
WARNING_CONFIRM_ADDON_INSTALL_CLICK_THROUGH
=
4
;
const
uint32_t
WARNING_CONFIRM_POST_TO_INSECURE_FROM_SECURE
=
9
;
const
uint32_t
WARNING_CONFIRM_POST_TO_INSECURE_FROM_SECURE_CLICK_THROUGH
=
10
;
const
uint32_t
WARNING_BAD_CERT_ADD_EXCEPTION_BASE
=
30
;
const
uint32_t
WARNING_BAD_CERT_ADD_EXCEPTION_FLAG_UNTRUSTED
=
1
;
const
uint32_t
WARNING_BAD_CERT_ADD_EXCEPTION_FLAG_DOMAIN
=
2
;
const
uint32_t
WARNING_BAD_CERT_ADD_EXCEPTION_FLAG_TIME
=
4
;
const
uint32_t
WARNING_BAD_CERT_CONFIRM_ADD_EXCEPTION_BASE
=
38
;
const
uint32_t
WARNING_BAD_CERT_CONFIRM_ADD_EXCEPTION_FLAG_UNTRUSTED
=
1
;
const
uint32_t
WARNING_BAD_CERT_CONFIRM_ADD_EXCEPTION_FLAG_DOMAIN
=
2
;
const
uint32_t
WARNING_BAD_CERT_CONFIRM_ADD_EXCEPTION_FLAG_TIME
=
4
;
const
uint32_t
WARNING_BAD_CERT_TOP_CLICK_VIEW_CERT
=
71
;
const
uint32_t
WARNING_BAD_CERT_TOP_DONT_REMEMBER_EXCEPTION
=
72
;
const
uint32_t
WARNING_BAD_CERT_TOP_ADD_EXCEPTION_BASE
=
76
;
const
uint32_t
WARNING_BAD_CERT_TOP_ADD_EXCEPTION_FLAG_UNTRUSTED
=
1
;
const
uint32_t
WARNING_BAD_CERT_TOP_ADD_EXCEPTION_FLAG_DOMAIN
=
2
;
const
uint32_t
WARNING_BAD_CERT_TOP_ADD_EXCEPTION_FLAG_TIME
=
4
;
const
uint32_t
WARNING_BAD_CERT_TOP_CONFIRM_ADD_EXCEPTION_BASE
=
84
;
const
uint32_t
WARNING_BAD_CERT_TOP_CONFIRM_ADD_EXCEPTION_FLAG_UNTRUSTED
=
1
;
const
uint32_t
WARNING_BAD_CERT_TOP_CONFIRM_ADD_EXCEPTION_FLAG_DOMAIN
=
2
;
const
uint32_t
WARNING_BAD_CERT_TOP_CONFIRM_ADD_EXCEPTION_FLAG_TIME
=
4
;
}
;
