#
include
"
nsISupports
.
idl
"
interface
nsIURI
;
[
scriptable
uuid
(
61b6348a
-
09e1
-
4810
-
8057
-
f8cb3cec6ef8
)
]
interface
mozIPlacesAutoComplete
:
nsISupports
{
cenum
MatchBehaviors
:
8
{
MATCH_ANYWHERE
=
0
MATCH_BOUNDARY
=
2
MATCH_ANYWHERE_UNMODIFIED
=
4
}
;
cenum
SearchBehaviors
:
16
{
BEHAVIOR_HISTORY
=
1
<
<
0
BEHAVIOR_BOOKMARK
=
1
<
<
1
BEHAVIOR_TAG
=
1
<
<
2
BEHAVIOR_TITLE
=
1
<
<
3
BEHAVIOR_URL
=
1
<
<
4
BEHAVIOR_TYPED
=
1
<
<
5
BEHAVIOR_JAVASCRIPT
=
1
<
<
6
BEHAVIOR_OPENPAGE
=
1
<
<
7
BEHAVIOR_RESTRICT
=
1
<
<
8
BEHAVIOR_SEARCH
=
1
<
<
9
}
;
}
;
