#
include
"
nsISupports
.
idl
"
interface
nsIURI
;
interface
nsIVariant
;
[
scriptable
uuid
(
9759bd0e
-
78e2
-
4421
-
9ed1
-
c676e1af3513
)
]
interface
nsITaggingService
:
nsISupports
{
void
tagURI
(
in
nsIURI
aURI
in
nsIVariant
aTags
[
optional
]
in
unsigned
short
aSource
)
;
void
untagURI
(
in
nsIURI
aURI
in
nsIVariant
aTags
[
optional
]
in
unsigned
short
aSource
)
;
Array
<
AString
>
getTagsForURI
(
in
nsIURI
aURI
)
;
}
;
