#
include
"
nsISupports
.
idl
"
[
scriptable
function
uuid
(
ea26627b
-
d21a
-
4f97
-
b2d0
-
f8df7be24808
)
]
interface
PlacesCompletionCallback
:
nsISupports
{
void
complete
(
in
nsresult
status
)
;
}
;
