#
include
"
nsISupports
.
idl
"
#
include
"
nsIFile
.
idl
"
[
scriptable
uuid
(
32d35d21
-
181f
-
4630
-
8caa
-
a431e2ebad72
)
]
interface
mozIGeckoMediaPluginChromeService
:
nsISupports
{
void
addPluginDirectory
(
in
AString
directory
)
;
void
removePluginDirectory
(
in
AString
directory
)
;
void
removeAndDeletePluginDirectory
(
in
AString
directory
[
optional
]
in
boolean
defer
)
;
void
forgetThisSite
(
in
AString
site
in
AString
aPattern
)
;
void
forgetThisBaseDomain
(
in
AString
baseDomain
)
;
boolean
isPersistentStorageAllowed
(
in
ACString
nodeId
)
;
nsIFile
getStorageDir
(
)
;
}
;
