#
include
"
nsISupports
.
idl
"
interface
nsISDBCallback
;
interface
nsIVariant
;
[
scriptable
uuid
(
13f05bcf
-
715c
-
427e
-
aac8
-
df9b2c1ec1e3
)
]
interface
nsISDBRequest
:
nsISupports
{
[
must_use
]
readonly
attribute
nsIVariant
result
;
[
must_use
]
readonly
attribute
nsresult
resultCode
;
[
must_use
]
readonly
attribute
ACString
resultName
;
attribute
nsISDBCallback
callback
;
}
;
