#
include
"
nsISupports
.
idl
"
[
scriptable
builtinclass
uuid
(
08B4CF29
-
3D65
-
4E79
-
B522
-
A694C322ED07
)
]
interface
nsINativeOSFileResult
:
nsISupports
{
[
implicit_jscontext
]
readonly
attribute
jsval
result
;
readonly
attribute
double
dispatchDurationMS
;
readonly
attribute
double
executionDurationMS
;
}
;
[
scriptable
function
uuid
(
2C1922CA
-
CA1B
-
4099
-
8B61
-
EC23CFF49412
)
]
interface
nsINativeOSFileSuccessCallback
:
nsISupports
{
void
complete
(
in
nsINativeOSFileResult
result
)
;
}
;
[
scriptable
function
uuid
(
F612E0FC
-
6736
-
4D24
-
AA50
-
FD661B3B40B6
)
]
interface
nsINativeOSFileErrorCallback
:
nsISupports
{
void
complete
(
in
ACString
operation
in
long
OSstatus
)
;
}
;
[
scriptable
builtinclass
uuid
(
913362AD
-
1526
-
4623
-
9E6B
-
A2EB08AFBBB9
)
]
interface
nsINativeOSFileInternalsService
:
nsISupports
{
[
implicit_jscontext
]
void
read
(
in
AString
path
in
jsval
options
in
nsINativeOSFileSuccessCallback
onSuccess
in
nsINativeOSFileErrorCallback
onError
)
;
[
implicit_jscontext
]
void
writeAtomic
(
in
AString
path
in
jsval
buffer
in
jsval
options
in
nsINativeOSFileSuccessCallback
onSuccess
in
nsINativeOSFileErrorCallback
onError
)
;
}
;
%
{
C
+
+
#
define
NATIVE_OSFILE_INTERNALS_SERVICE_CID
{
0x63A69303
0x8A64
0x45A9
{
0x84
0x8C
0xD4
0xE2
0x79
0x27
0x94
0xE6
}
}
#
define
NATIVE_OSFILE_INTERNALS_SERVICE_CONTRACTID
"
mozilla
.
org
/
toolkit
/
osfile
/
native
-
internals
;
1
"
%
}
