#
include
"
nsISupports
.
idl
"
%
{
C
+
+
namespace
mozilla
{
namespace
dom
{
class
ContentParent
;
class
JSActorManager
;
}
}
%
}
[
ptr
]
native
ContentParentPtr
(
mozilla
:
:
dom
:
:
ContentParent
)
;
[
ptr
]
native
JSActorManagerPtr
(
mozilla
:
:
dom
:
:
JSActorManager
)
;
webidl
JSProcessActorParent
;
[
scriptable
builtinclass
uuid
(
81fc08b9
-
c901
-
471f
-
ab0d
-
876362eba770
)
]
interface
nsIDOMProcessParent
:
nsISupports
{
[
infallible
]
readonly
attribute
unsigned
long
long
childID
;
[
infallible
]
readonly
attribute
long
osPid
;
[
implicit_jscontext
]
JSProcessActorParent
getActor
(
in
ACString
name
)
;
JSProcessActorParent
getExistingActor
(
in
ACString
name
)
;
[
infallible
]
readonly
attribute
boolean
canSend
;
[
notxpcom
nostdcall
]
ContentParentPtr
AsContentParent
(
)
;
[
notxpcom
nostdcall
]
JSActorManagerPtr
AsJSActorManager
(
)
;
readonly
attribute
ACString
remoteType
;
}
;
