#
include
"
nsISupports
.
idl
"
%
{
C
+
+
namespace
mozilla
{
namespace
dom
{
class
ContentChild
;
}
}
%
}
[
ptr
]
native
ContentChildPtr
(
mozilla
:
:
dom
:
:
ContentChild
)
;
webidl
JSProcessActorChild
;
[
scriptable
builtinclass
uuid
(
b0c6e5f3
-
02f1
-
4f11
-
a0af
-
336fc231f3bf
)
]
interface
nsIDOMProcessChild
:
nsISupports
{
[
infallible
]
readonly
attribute
unsigned
long
long
childID
;
JSProcessActorChild
getActor
(
in
ACString
name
)
;
[
infallible
]
readonly
attribute
boolean
canSend
;
[
notxpcom
nostdcall
]
ContentChildPtr
AsContentChild
(
)
;
}
;
