#
include
"
nsISupports
.
idl
"
%
{
C
+
+
namespace
mozilla
{
namespace
dom
{
class
ContentChild
;
class
JSActorManager
;
}
}
%
}
[
ptr
]
native
ContentChildPtr
(
mozilla
:
:
dom
:
:
ContentChild
)
;
[
ptr
]
native
JSActorManagerPtr
(
mozilla
:
:
dom
:
:
JSActorManager
)
;
webidl
JSProcessActorChild
;
[
scriptable
builtinclass
uuid
(
b0c6e5f3
-
02f1
-
4f11
-
a0af
-
336fc231f3bf
)
]
interface
nsIDOMProcessChild
:
nsISupports
{
%
{
C
+
+
static
nsIDOMProcessChild
*
GetSingleton
(
)
;
%
}
[
infallible
]
readonly
attribute
unsigned
long
long
childID
;
[
implicit_jscontext
]
JSProcessActorChild
getActor
(
in
ACString
name
)
;
JSProcessActorChild
getExistingActor
(
in
ACString
name
)
;
[
infallible
]
readonly
attribute
boolean
canSend
;
[
notxpcom
nostdcall
]
ContentChildPtr
AsContentChild
(
)
;
[
notxpcom
nostdcall
]
JSActorManagerPtr
AsJSActorManager
(
)
;
}
;
