#
include
"
nsISupports
.
idl
"
webidl
FrameLoader
;
webidl
Element
;
[
scriptable
uuid
(
5fcffbb9
-
be62
-
49b1
-
b8a1
-
36e820787a74
)
]
interface
nsIHangReport
:
nsISupports
{
const
unsigned
long
SLOW_SCRIPT
=
1
;
const
unsigned
long
PLUGIN_HANG
=
2
;
readonly
attribute
unsigned
long
hangType
;
readonly
attribute
Element
scriptBrowser
;
readonly
attribute
ACString
scriptFileName
;
readonly
attribute
double
hangDuration
;
readonly
attribute
AString
addonId
;
readonly
attribute
ACString
pluginName
;
readonly
attribute
unsigned
long
long
childID
;
void
userCanceled
(
)
;
void
terminateScript
(
)
;
void
terminateGlobal
(
)
;
void
terminatePlugin
(
)
;
void
beginStartingDebugger
(
)
;
void
endStartingDebugger
(
)
;
bool
isReportForBrowserOrChildren
(
in
FrameLoader
aFrameLoader
)
;
}
;
