#
include
"
nsISupports
.
idl
"
webidl
FrameLoader
;
webidl
Element
;
[
scriptable
uuid
(
5fcffbb9
-
be62
-
49b1
-
b8a1
-
36e820787a74
)
]
interface
nsIHangReport
:
nsISupports
{
readonly
attribute
Element
scriptBrowser
;
readonly
attribute
ACString
scriptFileName
;
readonly
attribute
double
hangDuration
;
readonly
attribute
AString
addonId
;
readonly
attribute
unsigned
long
long
childID
;
void
userCanceled
(
)
;
void
terminateScript
(
)
;
void
beginStartingDebugger
(
)
;
void
endStartingDebugger
(
)
;
boolean
isReportForBrowserOrChildren
(
in
FrameLoader
aFrameLoader
)
;
}
;
