#
include
"
nsISupports
.
idl
"
interface
nsIURI
;
interface
nsIFile
;
interface
nsIInterfaceRequestor
;
interface
nsIArray
;
[
scriptable
uuid
(
2e97e5dd
-
467b
-
4aea
-
a1bb
-
6773c0f2beb0
)
]
interface
nsIParentalControlsService
:
nsISupports
{
const
short
DOWNLOAD
=
1
;
const
short
INSTALL_EXTENSION
=
2
;
const
short
INSTALL_APP
=
3
;
const
short
BROWSE
=
4
;
const
short
SHARE
=
5
;
const
short
BOOKMARK
=
6
;
const
short
ADD_CONTACT
=
7
;
const
short
SET_IMAGE
=
8
;
const
short
MODIFY_ACCOUNTS
=
9
;
const
short
REMOTE_DEBUGGING
=
10
;
const
short
IMPORT_SETTINGS
=
11
;
const
short
PRIVATE_BROWSING
=
12
;
const
short
DATA_CHOICES
=
13
;
const
short
CLEAR_HISTORY
=
14
;
const
short
MASTER_PASSWORD
=
15
;
const
short
GUEST_BROWSING
=
16
;
const
short
ADVANCED_SETTINGS
=
17
;
const
short
CAMERA_MICROPHONE
=
18
;
const
short
BLOCK_LIST
=
19
;
const
short
TELEMETRY
=
20
;
const
short
HEALTH_REPORT
=
21
;
const
short
DEFAULT_THEME
=
22
;
readonly
attribute
boolean
parentalControlsEnabled
;
readonly
attribute
boolean
blockFileDownloadsEnabled
;
boolean
isAllowed
(
in
short
aAction
[
optional
]
in
nsIURI
aUri
)
;
readonly
attribute
boolean
loggingEnabled
;
const
short
ePCLog_URIVisit
=
1
;
const
short
ePCLog_FileDownload
=
2
;
void
log
(
in
short
aEntryType
in
boolean
aFlag
in
nsIURI
aSource
[
optional
]
in
nsIFile
aTarget
)
;
}
;
