#
include
"
nsISupports
.
idl
"
[
scriptable
uuid
(
91917c98
-
a8f3
-
4c98
-
8f10
-
4afb872f54c7
)
]
interface
nsIHapticFeedback
:
nsISupports
{
cenum
HapticFeedbackType
:
8
{
ShortPress
=
0
LongPress
=
1
TextHandleMove
=
2
}
;
void
performSimpleAction
(
in
nsIHapticFeedback_HapticFeedbackType
effect
)
;
}
;
