#
include
"
nsISupports
.
idl
"
[
scriptable
function
uuid
(
DB242E01
-
E4D9
-
11d2
-
9DDE
-
000064657374
)
]
interface
nsIObserver
:
nsISupports
{
void
observe
(
in
nsISupports
aSubject
in
string
aTopic
in
wstring
aData
)
;
}
;
