#
include
"
nsISupports
.
idl
"
interface
nsIObserver
;
interface
nsISimpleEnumerator
;
[
scriptable
builtinclass
uuid
(
D07F5192
-
E3D1
-
11d2
-
8ACD
-
00105A1B8860
)
]
interface
nsIObserverService
:
nsISupports
{
void
addObserver
(
in
nsIObserver
anObserver
in
string
aTopic
[
optional
]
in
boolean
ownsWeak
)
;
void
removeObserver
(
in
nsIObserver
anObserver
in
string
aTopic
)
;
void
notifyObservers
(
in
nsISupports
aSubject
in
string
aTopic
[
optional
]
in
wstring
someData
)
;
%
{
C
+
+
nsresult
NotifyWhenScriptSafe
(
nsISupports
*
aSubject
const
char
*
aTopic
const
char16_t
*
aData
=
nullptr
)
;
%
}
nsISimpleEnumerator
enumerateObservers
(
in
string
aTopic
)
;
}
;
