#
include
"
nsIProperties
.
idl
"
interface
nsIInputStream
;
interface
nsIOutputStream
;
interface
nsISimpleEnumerator
;
%
{
C
+
+
#
include
"
mozilla
/
MemoryReporting
.
h
"
%
}
native
MallocSizeOf
(
mozilla
:
:
MallocSizeOf
)
;
[
scriptable
uuid
(
283EE646
-
1AEF
-
11D4
-
98B3
-
00C04fA0CE9A
)
]
interface
nsIPropertyElement
:
nsISupports
{
attribute
AUTF8String
key
;
attribute
AString
value
;
}
;
[
scriptable
builtinclass
uuid
(
706867af
-
0400
-
4faa
-
beb1
-
0dae87308784
)
]
interface
nsIPersistentProperties
:
nsIProperties
{
void
load
(
in
nsIInputStream
input
)
;
void
save
(
in
nsIOutputStream
output
in
AUTF8String
header
)
;
nsISimpleEnumerator
enumerate
(
)
;
AString
getStringProperty
(
in
AUTF8String
key
)
;
AString
setStringProperty
(
in
AUTF8String
key
in
AString
value
)
;
[
notxpcom
nostdcall
]
size_t
sizeOfIncludingThis
(
in
MallocSizeOf
aMallocSizeOf
)
;
}
;
