#
include
"
nsISupports
.
idl
"
%
{
C
+
+
#
include
<
windows
.
h
>
%
}
native
HKEY
(
HKEY
)
;
[
scriptable
uuid
(
2555b930
-
d64f
-
437e
-
9be7
-
0a2cb252c1f4
)
]
interface
nsIWindowsRegKey
:
nsISupports
{
const
unsigned
long
ROOT_KEY_CLASSES_ROOT
=
0x80000000
;
const
unsigned
long
ROOT_KEY_CURRENT_USER
=
0x80000001
;
const
unsigned
long
ROOT_KEY_LOCAL_MACHINE
=
0x80000002
;
const
unsigned
long
ACCESS_BASIC
=
0x00020000
;
const
unsigned
long
ACCESS_QUERY_VALUE
=
0x00000001
;
const
unsigned
long
ACCESS_SET_VALUE
=
0x00000002
;
const
unsigned
long
ACCESS_CREATE_SUB_KEY
=
0x00000004
;
const
unsigned
long
ACCESS_ENUMERATE_SUB_KEYS
=
0x00000008
;
const
unsigned
long
ACCESS_NOTIFY
=
0x00000010
;
const
unsigned
long
ACCESS_READ
=
ACCESS_BASIC
|
ACCESS_QUERY_VALUE
|
ACCESS_ENUMERATE_SUB_KEYS
|
ACCESS_NOTIFY
;
const
unsigned
long
ACCESS_WRITE
=
ACCESS_BASIC
|
ACCESS_SET_VALUE
|
ACCESS_CREATE_SUB_KEY
;
const
unsigned
long
ACCESS_ALL
=
ACCESS_READ
|
ACCESS_WRITE
;
const
unsigned
long
WOW64_32
=
0x00000200
;
const
unsigned
long
WOW64_64
=
0x00000100
;
const
unsigned
long
TYPE_NONE
=
0
;
const
unsigned
long
TYPE_STRING
=
1
;
const
unsigned
long
TYPE_BINARY
=
3
;
const
unsigned
long
TYPE_INT
=
4
;
const
unsigned
long
TYPE_INT64
=
11
;
[
noscript
]
attribute
HKEY
key
;
void
close
(
)
;
void
open
(
in
unsigned
long
rootKey
in
AString
relPath
in
unsigned
long
mode
)
;
void
create
(
in
unsigned
long
rootKey
in
AString
relPath
in
unsigned
long
mode
)
;
nsIWindowsRegKey
openChild
(
in
AString
relPath
in
unsigned
long
mode
)
;
nsIWindowsRegKey
createChild
(
in
AString
relPath
in
unsigned
long
mode
)
;
readonly
attribute
unsigned
long
childCount
;
AString
getChildName
(
in
unsigned
long
index
)
;
boolean
hasChild
(
in
AString
name
)
;
readonly
attribute
unsigned
long
valueCount
;
AString
getValueName
(
in
unsigned
long
index
)
;
boolean
hasValue
(
in
AString
name
)
;
void
removeChild
(
in
AString
relPath
)
;
void
removeValue
(
in
AString
name
)
;
unsigned
long
getValueType
(
in
AString
name
)
;
AString
readStringValue
(
in
AString
name
)
;
unsigned
long
readIntValue
(
in
AString
name
)
;
unsigned
long
long
readInt64Value
(
in
AString
name
)
;
ACString
readBinaryValue
(
in
AString
name
)
;
void
writeStringValue
(
in
AString
name
in
AString
data
)
;
void
writeIntValue
(
in
AString
name
in
unsigned
long
data
)
;
void
writeInt64Value
(
in
AString
name
in
unsigned
long
long
data
)
;
void
writeBinaryValue
(
in
AString
name
in
ACString
data
)
;
void
startWatching
(
in
boolean
recurse
)
;
void
stopWatching
(
)
;
boolean
isWatching
(
)
;
boolean
hasChanged
(
)
;
}
;
