#
include
"
nsISupports
.
idl
"
#
include
"
nsIAsyncInputStream
.
idl
"
#
include
"
nsIEventTarget
.
idl
"
[
scriptable
builtinclass
uuid
(
4baa2d6e
-
fee7
-
42df
-
ae3f
-
5fbebc0c267c
)
]
interface
imgIEncoder
:
nsIAsyncInputStream
{
const
uint32_t
INPUT_FORMAT_RGB
=
0
;
const
uint32_t
INPUT_FORMAT_RGBA
=
1
;
const
uint32_t
INPUT_FORMAT_HOSTARGB
=
2
;
void
initFromData
(
[
array
size_is
(
length
)
const
]
in
uint8_t
data
in
unsigned
long
length
in
uint32_t
width
in
uint32_t
height
in
uint32_t
stride
in
uint32_t
inputFormat
in
AString
outputOptions
)
;
void
startImageEncode
(
in
uint32_t
width
in
uint32_t
height
in
uint32_t
inputFormat
in
AString
outputOptions
)
;
void
addImageFrame
(
[
array
size_is
(
length
)
const
]
in
uint8_t
data
in
unsigned
long
length
in
uint32_t
width
in
uint32_t
height
in
uint32_t
stride
in
uint32_t
frameFormat
in
AString
frameOptions
)
;
void
endImageEncode
(
)
;
[
noscript
]
unsigned
long
getImageBufferUsed
(
)
;
[
noscript
]
charPtr
getImageBuffer
(
)
;
}
;
