#
include
"
nsISupports
.
idl
"
interface
imgINotificationObserver
;
interface
imgIRequest
;
interface
nsIChannel
;
interface
nsILoadGroup
;
interface
nsIPrincipal
;
interface
nsIStreamListener
;
interface
nsIURI
;
interface
nsIReferrerInfo
;
interface
nsISimpleEnumerator
;
webidl
Document
;
#
include
"
nsIRequest
.
idl
"
#
include
"
nsIContentPolicy
.
idl
"
[
scriptable
builtinclass
uuid
(
e61377d2
-
910e
-
4c65
-
a64b
-
428d150e1fd1
)
]
interface
imgILoader
:
nsISupports
{
const
unsigned
long
LOAD_CORS_ANONYMOUS
=
1
<
<
16
;
const
unsigned
long
LOAD_CORS_USE_CREDENTIALS
=
1
<
<
17
;
imgIRequest
loadImageXPCOM
(
in
nsIURI
aURI
in
nsIURI
aInitialDocumentURL
in
nsIReferrerInfo
aReferrerInfo
in
nsIPrincipal
aLoadingPrincipal
in
nsILoadGroup
aLoadGroup
in
imgINotificationObserver
aObserver
in
Document
aLoadingDocument
in
nsLoadFlags
aLoadFlags
in
nsISupports
cacheKey
[
optional
]
in
nsContentPolicyType
aContentPolicyType
)
;
imgIRequest
loadImageWithChannelXPCOM
(
in
nsIChannel
aChannel
in
imgINotificationObserver
aObserver
in
Document
aLoadingDocument
out
nsIStreamListener
aListener
)
;
}
;
