#
include
"
nsISupports
.
idl
"
interface
imgIRequest
;
interface
nsIPrincipal
;
interface
nsIProperties
;
interface
nsIURI
;
webidl
Document
;
%
{
C
+
+
namespace
mozilla
{
class
OriginAttributes
;
}
%
}
[
ptr
]
native
OriginAttributesPtr
(
mozilla
:
:
OriginAttributes
)
;
[
scriptable
builtinclass
uuid
(
bfdf23ff
-
378e
-
402e
-
8a6c
-
840f0c82b6c3
)
]
interface
imgICache
:
nsISupports
{
void
clearCache
(
in
boolean
chrome
)
;
[
noscript
]
void
removeEntry
(
in
nsIURI
uri
[
optional
]
in
Document
doc
)
;
void
removeEntriesFromPrincipalInAllProcesses
(
in
nsIPrincipal
aPrincipal
)
;
void
removeEntriesFromBaseDomainInAllProcesses
(
in
ACString
aBaseDomain
)
;
[
must_use
]
nsIProperties
findEntryProperties
(
in
nsIURI
uri
[
optional
]
in
Document
doc
)
;
void
respectPrivacyNotifications
(
)
;
[
noscript
notxpcom
]
void
clearCacheForControlledDocument
(
in
Document
doc
)
;
}
;
