#
include
"
nsISupports
.
idl
"
#
include
"
nsISerializable
.
idl
"
interface
nsIPrincipal
;
interface
nsIURI
;
[
scriptable
builtinclass
uuid
(
3ec40331
-
7cf0
-
4b71
-
ba2a
-
2265aab8f6bc
)
]
interface
nsICookieJarSettings
:
nsISerializable
{
[
infallible
]
readonly
attribute
unsigned
long
cookieBehavior
;
[
infallible
]
readonly
attribute
boolean
isFirstPartyIsolated
;
[
infallible
]
readonly
attribute
boolean
shouldResistFingerprinting
;
[
infallible
]
readonly
attribute
boolean
rejectThirdPartyContexts
;
[
infallible
]
readonly
attribute
boolean
limitForeignContexts
;
[
infallible
]
readonly
attribute
boolean
blockingAllThirdPartyContexts
;
[
infallible
]
readonly
attribute
boolean
blockingAllContexts
;
[
infallible
]
attribute
boolean
partitionForeign
;
[
infallible
]
readonly
attribute
boolean
isOnContentBlockingAllowList
;
readonly
attribute
AString
partitionKey
;
unsigned
long
cookiePermission
(
in
nsIPrincipal
aPrincipal
)
;
void
initWithURI
(
in
nsIURI
aURI
in
boolean
aIsPrivate
)
;
}
;
